### PR TITLE
GitHub Actions: run units target on MSYS2

### PR DESCRIPTION
**Pull request by leleliu008**

### CODE REVIEW

**Comment by masatake** [comment]
@k-takata, could you review this one?

**Comment by masatake** [comment]
@leleliu008, if you don't get a review from @k-takata in a week, please, merge this.

**Comment by leleliu008** [comment]
@masatake OK.

**Comment by k-takata** [comment]
Looks okay for the first step.
To enable "make check" on Windows, see win32/appveyor.bat. It uses "make check APPVEYOR=1 PYTHON=py".
jansson, libxml2, and libyaml can be installed to enable additional features.

**Comment by leleliu008** [comment]
@k-takata No matter whether use `PYTHON=py` or not, the `make check` always failed when `MSYSTEM=MINGW32` and `MSYSTEM=MINGW64`, the reported error logs as follows:
```
D:/a/ctags2/ctags2/Tmain\tag-relative-option.d\stdout-diff.txt

	--- D:/a/ctags2/ctags2/Tmain/tag-relative-option.d/stdout-actual.txt	2021-02-01 08:11:51.364205500 +0000
	+++ "./Tmain\\tag-relative-option.d/stdout-expected.txt"	2021-02-01 08:09:29.486804200 +0000
	@@ -2 +2 @@
	-never:   ./input.c -> D:/a/ctags2/ctags2/Tmain/tag-relative-option.d/input.c
	+never:   ./input.c -> /abs/input.c
	@@ -7 +7 @@
	-never:   input.c -> D:/a/ctags2/ctags2/Tmain/tag-relative-option.d/input.c
	+never:   input.c -> /abs/input.c
	@@ -11,4 +11,4 @@
	-default: /abs/input.c -> D:/a/ctags2/ctags2/Tmain/tag-relative-option.d/input.c
	-never:   /abs/input.c -> D:/a/ctags2/ctags2/Tmain/tag-relative-option.d/input.c
	-no:      /abs/input.c -> D:/a/ctags2/ctags2/Tmain/tag-relative-option.d/input.c
	-yes:     /abs/input.c -> D:/a/ctags2/ctags2/Tmain/tag-relative-option.d/input.c
	+default: /abs/input.c -> /abs/input.c
	+never:   /abs/input.c -> /abs/input.c
	+no:      /abs/input.c -> /abs/input.c
	+yes:     /abs/input.c -> /abs/input.c
```

by the way, I read the `win32/appveyor.bat`, I'm confused that why you do not test `MSYSTEM=MSYS` , and why you skip the `make check` when `MSYSTEM=MINGW64`, is there exists particular reasons?

**Comment by k-takata** [comment]
It seems that the failures are caused by the difference of the path of AppVeyor and GHA.
I think that there is a script to convert full paths in the test results to relative paths. (I don't remember where the script is, though.) 

The reason why I skipped some tests is I wanted to reduce the testing time because AppVeyor cannot run multiple jobs in parallel in the free plan. On the other hand, GHA can run multiple jobs in parallel, so we don't need to skip them.
(MSYSTEM=MSYS is very similar to Cygwin. MSYSTEM=MINGW64 is very similar to MSYSTEM=MINGW32.)

**Comment by leleliu008** [comment]
@k-takata I found that do `make check` in /c/Windows/System32/ctags works fine when `MSYSTEM=MINGW64`

**Comment by leleliu008** [comment]
@k-takata It works fine when `MSYSTEM=MSYS`.

**Comment by k-takata** [comment]
How about this? (not tested)

```diff
--- a/Tmain/tag-relative-option.d/run.sh
+++ b/Tmain/tag-relative-option.d/run.sh
@@ -35,7 +35,7 @@ fi
     ${CTAGS} $O --_xformat="always:  $F -> %F"  --tag-relative=always $F
 } | {
 	# Normalize driver letter
-    sed -e 's|C:|/c|g'
+    sed -e 's|C:|/c|g' -e 's|D:|/d|g'
 } | {
 	# Unescape
 	sed -e 's|\\\\|\\|g'
```

**Comment by leleliu008** [comment]
@k-takata I have created a new issue(#2833) about this.

**Comment by masatake** [comment]
Great!

**Comment by leleliu008** [comment]
I don't run `make roundtrip` when `MSYSTEM=MINGW32` and `MSYSTEM=MINGW64` due to #2850

**Comment by masatake** [comment]
When 14 days (two weeks) passed after pushing with `--force` you can merge your change without a response from the reviewer.

**Pull request merged**
