### PR TITLE
R: rewrite the parser

### LINKED ISSUE #2393: R parser does not recognize `=` based assignment
(
Thank you for contacting us.

If you are reporting an issue with the parsing output, please fill
the following template.  As your custom CTags configuration can
affect results, please always use `--options=NONE` as the first
option when running `ctags`.

Otherwise, delete the template and write your issue from scratch.
Examples may help developers understanding your issue better.

Use GitHub web interface and markdown notation.
Using mail results broken text rendering that makes
the developers go crazy.
)

*****

The name of the parser: R

The command line you used to run ctags:

```
$ ctags --options=NONE *
```

The content of input file:
```{r}
test_function_1 = function() {
  print("This function does not appear in tag file.")
}

other_function  <- function() {
  print("This function appears in tag file.")
}

```

The tags output you are not satisfied with:

```
other_function	test_function_1.R	/^other_function  <- function() {$/;"	f
```

The tags output you expect:

```
other_function	test_function_1.R	/^other_function  <- function() {$/;"	f
test_function_1	/tmp/foo.r	/^test_function_1 = function() {$/;"	f
```

The version of ctags:

```
$ ctags --version
Universal Ctags 0.0.0(a3c87ab), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jan  6 2020, 14:54:04
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +case-insensitive-filenames, +packcc

```

How do you get ctags binary:

(
brew install on Mac OS 10.13
)

### PR DESCRIPTION
**Pull request by masatake**
Close #2393.

Still considering how to handle 'a$b'.
The original parser may capture 'a$b'. However,  capturing just 'b' looks better.
In that case, I would like to resolve a.
In that case, the symbol table feature developed at #2427 is needed.

Class related codes are not implemented yet.

### CODE REVIEW

**Comment by suntzuisafterU** [comment]
Hey, I pulled the branch from your fork and was not able to build it for some reason.  I can build the ctags master branch, not sure what the difference is.

I am on OSX.

**Comment by masatake** [comment]
Do you have an error in building ctags or a trouble about git operation?
If what you got is the former one, could you show me the error message?

**Comment by suntzuisafterU** [comment]
It's a build issue. I couldn't find the documentation for how to run it so I just ran autoconfig then make. It gave an error about no symbols for x86_64.  Sorry I'm afk at the moment.

So I can build the master branch of ctags but can't remember how it was configured.

**Comment by masatake** [comment]
gcc, gnu make, automake, autoconf, and pkg-config must be installed.
```
cd ctags
bash ./autogen.sh
./configure
make 
vi input.r
./ctags -o - input.r
```

**Comment by suntzuisafterU** [comment]
I have verified all dependencies and followed your instructions.  I had the same error.  Here is the output:

```
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libctags.a(libctags_a-trace.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libctags.a(libctags_a-cxx_debug.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libctags.a(libctags_a-cxx_debug_type.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libctags.a(libctags_a-debug.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libctags.a(libctags_a-trace.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libctags.a(libctags_a-cxx_debug.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libctags.a(libctags_a-cxx_debug_type.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libctags.a(libctags_a-debug.o) has no symbols
  CCLD     ctags
Undefined symbols for architecture x86_64:
  "_R_TRACE_ENTER", referenced from:
      _parseStatement in libctags.a(libctags_a-r.o)
      _parseRightSide in libctags.a(libctags_a-r.o)
  "_R_TRACE_LEAVE", referenced from:
      _parseStatement in libctags.a(libctags_a-r.o)
      _parseRightSide in libctags.a(libctags_a-r.o)
  "_R_TRACE_TOKEN", referenced from:
      _findRTags in libctags.a(libctags_a-r.o)
  "_R_TRACE_TOKEN_TEXT", referenced from:
      _parseStatement in libctags.a(libctags_a-r.o)
      _parseRightSide in libctags.a(libctags_a-r.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [ctags] Error 1
make: *** [all] Error 2
```

**Comment by masatake** [comment]
Very strange. The debug mode is partially enabled . I cannot imge the reason.

I would like you to try both:
```
$ cd ctags
$ make clean; ./configure --enable-debugging;make 
```
and
```
$ cd ctags
$ make clean; ./configure --disable-debugging;make 
```

**Comment by suntzuisafterU** [comment]
Just built with the debugging enabled flag successfully.  Strange

**Comment by suntzuisafterU** [comment]
Found one missed variable.
I modified the file below as follows to show that `a` survives in the scope of `f`
```
 cat Units/parser-r.r/r-scope.d/input-3.r
f <- function () {
        d <- (
          1 + 2 + 3 + (a
        <- 4) + 5)

        print(a)


}

f()
```

```
./ctags -o - Units/parser-r.r/r-scope.d/input-3.r
d       Units/parser-r.r/r-scope.d/input-3.r    /^      d <- ($/;"      v       function:f
f       Units/parser-r.r/r-scope.d/input-3.r    /^f <- function () {$/;"        f
```

**Comment by suntzuisafterU** [comment]
From the r-extended.d directory, we miss the library attachment and sourcing of a local file.  I am not sure how ctags generally handles this.

```
./ctags -o - Units/parser-r.r/r-extended.d/input.r
.First  Units/parser-r.r/r-extended.d/input.r   /^.First <- function() {$/;"    f
```

```
r-extended.d$ cat input.r
# From:
# https://cran.r-project.org/doc/manuals/r-release/R-intro.html#Customizing-the-environment
.First <- function() {
  options(prompt="$ ", continue="+\t")  # $ is the prompt
  options(digits=5, length=999)         # custom numbers and printout
  x11()                                 # for graphics
  par(pch = "+")                        # plotting character
  source(file.path(Sys.getenv("HOME"), "R", "mystuff.R"))
                                        # my personal functions
  library(MASS)                         # attach a package
}


(base)  (masatake-R-rewrite)
r-extended.d$ cat expected.tags
.First	input.r	/^.First <- function() {$/;"	f
MASS	input.r	/^  library(MASS)                         # attach a package$/;"	l
file.path(Sys.getenv("HOME"	input.r	/^  source(file.path(Sys.getenv("HOME"), "R", "mystuff.R"))$/;"	s

```

**Comment by suntzuisafterU** [comment]
I also noticed in the file r-scoped/input.r that the following line:

```
f5 <- function(a5) c(1,
...
```

Defines a5 as an argument to f5, and this is not picked up in the output: 
```
./ctags -o - Units/parser-r.r/r-scope.d/input.r
c00     Units/parser-r.r/r-scope.d/input.r      /^c00 = 1$/;"   g
c01     Units/parser-r.r/r-scope.d/input.r      /^c01 <- 2$/;"  g
c02     Units/parser-r.r/r-scope.d/input.r      /^c02 <<- 3$/;" g
c50     Units/parser-r.r/r-scope.d/input.r      /^f5((c50 = 4))$/;"     g
c51     Units/parser-r.r/r-scope.d/input.r      /^f5(c51 <- 4)$/;"      g
c52     Units/parser-r.r/r-scope.d/input.r      /^f5(c52 <<- 4)$/;"     g
f0      Units/parser-r.r/r-scope.d/input.r      /^f0 <- function() {$/;"        f
f1      Units/parser-r.r/r-scope.d/input.r      /^f1 <- function(a1) {$/;"      f
f2      Units/parser-r.r/r-scope.d/input.r      /^f2 <- function(a20, a21) {$/;"        f
f4      Units/parser-r.r/r-scope.d/input.r      /^f4 <- function() c02 +$/;"    f
f5      Units/parser-r.r/r-scope.d/input.r      /^f5 <- function(a5) c(1,$/;"   f
r0      Units/parser-r.r/r-scope.d/input.r      /^   r0 <- c00 + c01 + c02$/;"  v       function:f0
r1      Units/parser-r.r/r-scope.d/input.r      /^   r1 = c00 + c01 + c02 + a1$/;"      v       function:f1
r2      Units/parser-r.r/r-scope.d/input.r      /^   r2 <<- c00 + c01 + c02 + a20 + a21$/;"     v       function:f2
r5      Units/parser-r.r/r-scope.d/input.r      /^r5 <- 3,$/;"  v       function:f5
```

**Comment by masatake** [comment]
> Just built with the debugging enabled flag successfully. Strange
I found its reason. I will push the fix for it.

**Comment by suntzuisafterU** [comment]
I have reviewed all the provided test cases, I have one more observation; when
```
r1 = 0
f <- function() {
  r1 <<- r1 + 1
}

show(f())
show(f())


r1 = 37

g <- function() {
  r1 <- r1 + 1
}

show(g())
show(g())
```

Is executed, the output is:
```
1
2
38
38
```

Because the `<<-` operator escapes and updates the outer scope variable, instead of making a new one.

Sorry for the delay in getting back to you, hopefully this helps.

**Comment by masatake** [comment]
@suntzuisafterU, thank you very much.
source and library are not handled yet. handling them is not hard. I can implement the code for them later.

I must fix the other items you spotted first.

**Comment by masatake** [comment]
```
 cat Units/parser-r.r/r-scope.d/input-3.r
f <- function () {
        d <- (
          1 + 2 + 3 + (a
        <- 4) + 5)

        print(a)


}

f()

./ctags -o - Units/parser-r.r/r-scope.d/input-3.r
d       Units/parser-r.r/r-scope.d/input-3.r    /^      d <- ($/;"      v       function:f
f       Units/parser-r.r/r-scope.d/input-3.r    /^f <- function () {$/;"        f
```
This one may be fixed in the new commits.

**Comment by masatake** [comment]
```
r1 = 0
f <- function() {
  r1 <<- r1 + 1
}

show(f())
show(f())


r1 = 37

g <- function() {
  r1 <- r1 + 1
}

show(g())
show(g())

```

In this case, r1 on the left side of '<<-' and '<-' are not definition. They should be captured as reference tags because they are just updating the value of variable.
The definitions are at the first line 'r1 = 0'. This one introduces a new `r1`.

I found one derived input.
```
f <- function() {
  r1 <<- 1
}

show(r1)
```

In this case 'r1' is defined in the code f.

To make a better tags file, ctags can know whether a name is already appeared or not.
This functionality is needed ont only the R parser but also...all the parsers.
I"m working on this topic at  #2413.

With the symbol table, the R parser can know whether r1 is defined already or not.

```
f <- function() {
  r1 <<- 1
}
```
In this case, r1 is not defined before parsing f. So we can say r1 is defined here.

```
f <- function() {
  r1 <<- 1
}
g <- function() {
  r1 <<- 2
}
```
ctags works in lexical level. So r1 in f and r1 in g are captured as definition tags.

What I cannot find the way how I should do is scope.
```
f <- function() {
  r1 <<- 1
}
```

In R's semantic, the scope of r1 is empty; r1 is in the top level namespace.
However, I'm not happy with this. I would like to attach the information "r is defined during running f()"
to the tag for r1.  In that case how do I call the field for it? The name executionScope hits me.

```
f <- function () {
  g <- function () {
     r1 <<- 1
  }
}
```
In this case the tag entry for r1 is...
```
f     .... kind:function
g    ...  kind:functionVar scope:f
r1   .... kind:functionVar scope:f exectuionScope:f.g
```  

executionScope is not special for R. So it it better to make it short: xscope.

Maybe a better term is defined in compiler theory.
I have to think more about this topic.

**Comment by masatake** [comment]
```
I also noticed in the file r-scoped/input.r that the following line:

f5 <- function(a5) c(1,
...

Yes. I'm thinking about capturing a1 with another kind tag: parameter.
Adding this may be easy.

So the most important one in this situation is ... deciding how we should do with "<<-".

**Comment by suntzuisafterU** [comment]
In this example:

```
r1 = 0
f <- function() {
  r1 <<- r1 + 1
}

show(f())
show(f())


r1 = 37

g <- function() {
  r1 <- r1 + 1  # This defines a local variable r1, and also implicitly returns it
}

show(g())
show(g())
```


There are actually 2 instances of variables with the symbol r1.
The r1 value that is local to g is also implicitly returned.

Also, when a variable is defined within a function via `<<-`, it can redefine variables already
existing in the global scope.  Then really there can be multiple statements that may be responsible for defining one variable in the global scope.  

Also note that:
```
a0 <- "Here"

f <- function() {
  a0 <- 42
  g <- function() {
    a0 <<- 99
  }
  show(a0)
  g()
  show(a0)
}

f()

show(a0)

```

Prints the following:
```
42
99
Here
```

Indicating that `<<-` simply redefines the smallest enclosing scopes variable with the same name, or defines the variable in the global scope if it does not exist.


Handling multiple definitions in the same scope may be problematic, but semantically this
is what is happening.  There may not be an easy solution.

**Comment by masatake** [comment]
Using newly introduced facility called "symbol table", I have refined the original pull request.

TODO
* support file extension ".s" again,
* improve coverage of test cases,
* add notes about the behaviour of R to dccs/parser-r.rst.

The last one may be important when thinking about improving JavaScript parser.

**Comment by masatake** [comment]
The coverage of the scanner is too low.

**Pull request merged**
