### PR TITLE
Support VC2015

### PR DESCRIPTION
**Pull request by k-takata**
* Import the latest packcc.
* Fix regex.

### CODE REVIEW

**Comment by k-takata** [comment]
I will merge this in a few days if there's no objection.

**Comment by masatake** [comment]
Could you squash
5d11a90 and 
96527a1 into one?

**Comment by k-takata** [comment]
Squashed.
I also updated the commit message and explained why I used `size_t` for this.

**Comment by masatake** [comment]
In https://github.com/universal-ctags/ctags/blob/master/main/htable.h#L54
I use intptr_t. Is this can be a trouble on building ctags on MinGW?

**Comment by masatake** [comment]
Intead, how about defining intptr_t in mk_mingw.mak or somewhere?
So we can use intptr_t in our code.

**Comment by k-takata** [comment]
Hmm, at least current CI passes even you uses `intptr_t`.
Is any header needed for using `intptr_t` on a old MinGW?

**Comment by k-takata** [comment]
Maybe `stdint.h`? You include it from `htable.h`.

**Comment by masatake** [comment]
Yes!
```
[yamato@slave]~/var/ctags-github% ./ctags -o - /usr/include/stdint.h | grep ^intptr_t
intptr_t	/usr/include/stdint.h	/^typedef int			intptr_t;$/;"	t	typeref:typename:int
intptr_t	/usr/include/stdint.h	/^typedef long int		intptr_t;$/;"	t	typeref:typename:long int
```

**Comment by masatake** [comment]
If stdint.h is not available on the platform, we have to define it in the .mak.
It seems that intptr_t is introduced in c99. So I expect it is available on any platform.
If not, u-ctags cannot be built in many various reasons.

**Comment by k-takata** [comment]
I think we should add `-DHAVE_STDINT_H` in mk_mingw.mak. I will try it later.

**Comment by k-takata** [comment]
The CI succeeded.

**Comment by masatake** [comment]
Fine! LGTM.

**Pull request merged**
