### PR TITLE
Test cases under review needed.r language vim

### PR DESCRIPTION
**Pull request by dkearns**
These tests are OK; they reflect the current state of the parser. 

However, I did notice that variables seem to be missed by the parser in a couple of situations. I'll file a bug report or fix them when I've had a better look.

### CODE REVIEW

**Comment by masatake** [comment]
`*.b` suffix can be used for marking/filling a bug. 
See `Gathering test cases for known bugs` in http://docs.ctags.io/en/latest/units.html .

**Comment by masatake** [comment]
Thank you very much!

**Comment by dkearns** [comment]
As an aside, thanks for all the documentation. I haven't read it all yet but it is appreciated.

**Comment by masatake** [comment]
Comments for documentation is really welcome. The documentation is critical bottle-neck for releasing.

**Pull request merged**
