### PR TITLE
Fortran interface and prototype

### PR DESCRIPTION
**Pull request by QingmingHe**
+ Trun on Fortran interface by default.
+ Add prototype kind to record subprogram prototypes inside interface. This kind is turned off by default. See the discussion in #339.

### CODE REVIEW

**Comment by vhda** [comment]
Excellent!

**Comment by masatake** [comment]
Thank you.

Could you cherry-pick following patch into your PR?
https://github.com/masatake/ctags/commit/5dacaa6f14e0b142d0027c506fdd73015c8241d0

**Comment by masatake** [comment]
I will open a PR for following change
https://github.com/masatake/ctags/commit/75a9d68cbcc1989ac7abec109bbe0a2979e75a39

**Comment by QingmingHe** [comment]
> Can I ask you to review at that time?

Yes. It's my pleasure.

**Comment by masatake** [comment]
Thank you.

BTW, do you have an interest to maintain the fortran parser (and other parts) as a member of this project? This project needs a person who knows all the target language, ctags and open source development. I know you have more patches to be merged to  u-ctags:-)

If you have an interest, could you write yourself in docs/developers.rst and make a PR for it?

**Comment by QingmingHe** [comment]
I'm very interested in this project and it's quite a honor to be part of you! I'll open a PR later to add my self.

**Pull request merged**
