### PR TITLE
ReStructuredText: add target kind

### PR DESCRIPTION
**Pull request by masatake**
A target appears as following:

  .. _something-target:

or

  .. _ `something target`:

TODO: Do the same on the other languages for documentation
like TeX.

Suggested by @blueyed in #1777.

Signed-off-by: Masatake YAMATO <yamato@redhat.com>

### CODE REVIEW

**Comment by masatake** [comment]
@b4n, you may have interest on this item because this can be ported to geany.

**Comment by blueyed** [comment]
I think it should be more strict maybe:

> Hyperlink targets may be named or anonymous. Named hyperlink targets consist of an explicit markup start (".. "), an underscore, the reference name (no trailing underscore), a colon, whitespace, and a link block:

Sphinx only generates a target for the last one, whereas this PR creates tags for all of them:

```rst
.. _       	     `section target1`   :
.. _       	     `section target2`:
.. _`section target3`  :
.. _`section target4`:
```

**Comment by masatake** [comment]
Updated.

Escaping with backslash is handled, too. 
```
.. _abc\:efg:
```

In this case, ctags records this as:
```
abc\\:efg
```
in tags file.

**Comment by blueyed** [comment]
Awesome, thanks!

**Comment by masatake** [comment]
@b4n, thank you.

**Pull request merged**
