### PR TITLE
docs: Testing a PR locally before being merged

### PR DESCRIPTION
**Pull request by hirooih**
Describes how to test a PR locally before being merged.

### CODE REVIEW

**Review by masatake — APPROVED** [review]

**Comment by masatake** [comment]
I thought I had to write about it.
Thank you very much.

**Comment by hirooih** [comment]
You are welcome.
Thank you for teaching me this tips!

**Comment by k-takata** [comment]
The official GitHub document is available:
https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally

```
$ git fetch origin pull/ID/head:BRANCHNAME
$ git checkout BRANCHNAME
```

**Comment by hirooih** [comment]
@k-takata san,

First I found this, but it did not work.

```
$ git checkout -b test
$ git remote -v
origin  https://github.com/hirooih/ctags.git (fetch)
origin  https://github.com/hirooih/ctags.git (push)
upstream        https://github.com/universal-ctags/ctags.git (fetch)
upstream        https://github.com/universal-ctags/ctags.git (push)
$ git fetch upstream pull/3057/head:TEMP-debug-segmentation-faults-on-MSYS2-MINGW64
fatal: Refusing to fetch into current branch refs/heads/TEMP-debug-segmentation-faults-on-MSYS2-MINGW64 of non-bare repository
$ 
```

What's wrong?

**Comment by k-takata** [comment]
Aren't you going to fetch the PR directly into the current branch?

If you want to merge the PR into your current branch, you can use `FETCH_HEAD`.
```
$ git fetch upstream pull/3057/head
$ git merge FETCH_HEAD
```

**Comment by hirooih** [comment]
@k-takata san,

I found what was wrong with me.

```
$ git fetch upstream pull/3057/head:TEMP-debug-segmentation-faults-on-MSYS2-MINGW64
fatal: Refusing to fetch into current branch refs/heads/TEMP-debug-segmentation-faults-on-MSYS2-MINGW64 of non-bare repository
$ 
```

Before executing this command I made a branch `TEMP-debug-segmentation-faults-on-MSYS2-MINGW64`.  But the command above also tries to create a branch `TEMP-debug-segmentation-faults-on-MSYS2-MINGW64` and then failed.

And I found that the 2nd way was described in [6.3 GitHub - Maintaining a Project](https://git-scm.com/book/en/v2/GitHub-Maintaining-a-Project).

Thank you very much.

I've created a PR #3087 following your advice.

**Pull request merged**
