### PR TITLE
Roundtrip test

### LINKED ISSUE #685: How to test readtags.c?
I am running into a problem with readtag.c

I use this in my notepad++ plugin but when run it on this file, it crashes my plugin.
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/test/examples/x.cxx

readtags has a problem parsing the "M" tag that gets generated, most likely because of the "\" at the end of the search pattern. Note that this x.cxx file compiles just fine.

I am still struggling to build readtags.exe with any of the Windows compilers. So debugging the exact problem is a bit hard ATM, but I will get there :-)

I want to know if we have a way to test this readtags parser? If not, any thought how we can create proper tests for readtags?

### PR DESCRIPTION
**Pull request by masatake**
Close #685.

### CODE REVIEW

**Comment by masatake** [comment]
@ffes, could you try this?

**Comment by masatake** [comment]
...I should provide the way to run this under valgrind.

**Comment by masatake** [comment]
Whether should I use "--" or "-" as a separator between options and name arguments?

**Comment by ffes** [comment]
I just tried your adjusted readtags.c and it fixes the problem! Thanks!!!

**Comment by ffes** [comment]
Just tested with the new readtags.c on two other (rather large) source trees at the office where I had similar problems, but didn't had/took time to investigate the cause of the problems. They both now work as expected as well, so apparently it was the same problem. So again, thanks! :-)

**Pull request merged**
