### PR TITLE
ci: upload coverage also to codecov

### PR DESCRIPTION
**Pull request by blueyed**
Could be done also from CircleCI maybe?

### CODE REVIEW

**Comment by blueyed** [comment]
Rebased.

**Comment by masatake** [comment]
I expect you will remove `[WIP]` when this pr is ready to merge (or review).

**Comment by blueyed** [comment]
@masatake 
I think it is good for now.

**Comment by masatake** [comment]
Thank you.

**Comment by blueyed** [comment]
You're welcome! :)

**Pull request merged**
