### PR TITLE
Lisp: add def{struct,type,method,class,generic,parameter} kinds and definer field

### LINKED ISSUE #4120: Lisp: Common Lisp OOP/type parsing
The name of the parser: lisp

The command line you used to run ctags:

```
$ ctags --options=NONE source/*.lisp source/mode/*.lisp libraries/*/*.lisp
```

In the root dir of [Nyxt browser](https://github.com/atlas-engineer/nyxt)

The tags output you are not satisfied with:

```
cursor	libraries/text-buffer/text-buffer.lisp	/^(defclass cursor (cluffer-simple-line::right-sticky-cursor)$/;"	Y
customize-instance	source/user-classes.lisp	/^(defgeneric customize-instance (object &key &allow-other-keys)$/;"	Y
renderer-history-entry	source/renderer/gtk.lisp	/^(defstruct renderer-history-entry$/;"	Y
render-functions	source/mode/macro-edit.lisp	/^(defmethod render-functions ((macro-editor macro-edit-mode))$/;"	Y
prompter:object-attributes	source/mode/hint.lisp	/^(defmethod prompter:object-attributes :around ((element plump:element) (source hint-source))$/;"	Y
```

All of these marked as unknown. More semantic markers won't hurt. Something like `t`/`c`/`s` (type/class/struct) and `m` (method)? I personally prefer `t`/`type` as that's the term Common Lisp docs use for classes and types (not structs, confusingly, but structs are types too!)

```
cursor	libraries/text-buffer/text-buffer.lisp	/^(defclass cursor (cluffer-simple-line::right-sticky-cursor)$/;"	t (or c=class?)
customize-instance	source/user-classes.lisp	/^(defgeneric customize-instance (object &key &allow-other-keys)$/;"	f
renderer-history-entry	source/renderer/gtk.lisp	/^(defstruct renderer-history-entry$/;"	t (or s=struct?)
rememberable-mode-invocation	source/auto-rules.lisp	/^(deftype rememberable-mode-invocation ()$/;"	t
render-functions	source/mode/macro-edit.lisp	/^(defmethod render-functions ((macro-editor macro-edit-mode))$/;"	m
prompter:object-attributes	source/mode/hint.lisp	/^(defmethod prompter:object-attributes :around ((element plump:element) (source hint-source))$/;"	m
```

See [defmethod](https://www.lispworks.com/documentation/HyperSpec/Body/m_defmet.htm), [defgeneric](https://www.lispworks.com/documentation/HyperSpec/Body/m_defgen.htm), [defclass](https://www.lispworks.com/documentation/HyperSpec/Body/m_defcla.htm), [deftype](https://www.lispworks.com/documentation/HyperSpec/Body/m_deftp.htm), and [defstruct](https://www.lispworks.com/documentation/HyperSpec/Body/m_defstr.htm) (notice that the name can be a parenthesized list `(name options ...)`!) for exact parsing BNF.

-----------------------------------------------------

The version of ctags:

```
$ ctags --version
Universal Ctags 6.1.0(p6.1.20241117.0), Copyright (C) 2015-2023 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Nov 18 2024, 17:31:59
  URL: https://ctags.io/
  Output version: 0.0
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml, +packcc, +optscript, +pcre2
```

How do you get ctags binary: via pacman on Arch Linux

### PR DESCRIPTION
**Pull request by masatake**
Close #4120.

- [x] man pages for EmacsLisp and Lisp must be added.
- [x] introduce a data structure representing the difference between Lisp and EmacsLisp.
- [ ] L_isdef and L_isquote should be unified.

### CODE REVIEW

**Comment by aartaka** [comment]
Looks good to me!

-----------------------------------

Sorry for being so chaotic, but can you also add `defparameter` as the `v`ariable definer? It's the same as `defvar` in regards to parsing and the type of entities it creates—variables.

**Comment by masatake** [comment]
I added the `parameter/p` kind. "definer:" field  is for language objects tagged as `unknown/Y.`

**Comment by aartaka** [comment]
> I added the `parameter/p` kind. 

Semantically, `defparameter` defines variables, as there are no parameter objects in Common Lisp. Can you use `v` instead?

> "definer:" field is for language objects tagged as `unknown/Y.`

Ah, okay then.

**Comment by masatake** [comment]
> Semantically, defparameter defines variables, as there are no parameter objects in Common Lisp. Can you use v instead?

Unifying variables and parameters is the job of client tools.
ctags should provide raw information to the client tools.

**Comment by aartaka** [comment]
So be it then :ok_hand:

**Pull request merged**
