### PR TITLE
buildsys: add .ctags.d/*.ctags to EXTRA_DIST

### PR DESCRIPTION
**Pull request by masatake**
Signed-off-by: Masatake YAMATO <yamato@redhat.com>

### CODE REVIEW

**Comment by k-takata** [comment]
Typo: `.ctagd.d` -> `.ctags.d`

**Comment by masatake** [comment]
@k-takata, thank you. Updated.

**Comment by masatake** [comment]
Looks strange.

**Comment by masatake** [comment]
I have wasted the time for meaningless debugging.

**Pull request merged**
