### PR TITLE
core: Add development area pseudo tag

### PR DESCRIPTION
**Pull request by vhda**
* Revert original to using original URL pseudo tag and add new development tag
  pointing to github area.
* Update copyright date.

### CODE REVIEW

**Comment by Pyrohh** [comment]
Should the copyright date not be 2015?

**Comment by vhda** [comment]
Thanks for spotting that.
The change was originally created still last year and I did not give the necessary attention to the diff while splitting the changes into different PRs.

**Comment by Pyrohh** [comment]
LGTM

**Comment by masatake** [comment]
I think we don't need development area pseudo tag anymore.
Can I close this?

**Comment by ffes** [comment]
I also think it is OK to close this one. If not @vhda please reopen.

**Comment by vhda** [comment]
That's fine by me.
But please review that file, I think we need to discuss all those values.

**Comment by masatake** [comment]
@vhda, now we set our own value to PROGRAM_URL, https://github.com/universal-ctags/ctags.
(This can be changed to http://ctags.io.)

For a while, I think it is enough for us. The most concerned thing was that a bug report about our implementation went to sf.net. This was really bad thing.  Now we don't have to care about it. The user can reach us.

**Comment by vhda** [comment]
:thumbsup:

**Pull request closed without merging**
