### PR TITLE
Add Haskell parser from Geany

### PR DESCRIPTION
**Pull request by techee**
Haskell <https://en.wikipedia.org/wiki/Haskell_%28programming_language%29>

### CODE REVIEW

**Comment by masatake** [comment]
Can I ask you to provide a test case for LiterateHaskell?
This is the first time to hear about it.

**Comment by techee** [comment]
> This is the first time to hear about it.

Yeah, same here. Not sure if anyone is crazy enough to use it:

https://www.haskell.org/onlinereport/literate.html

**Comment by masatake** [comment]
If Haskel code is embedded in latex code, I think using Tex parser will be better.
Real lhs language processor may just ignore Latex code part.
However, ctags should make tags for the Latex code part, too.

Give me time.

**Comment by techee** [comment]
The question really is whether the literate haskell part is any useful and whether it shouldn't be removed completely. I can't really imagine that anyone would code this way.

**Comment by techee** [comment]
I've just checked and in Geany we don't use the literate haskell part. Personally, I'd just remove it. Should I do it?

**Comment by masatake** [comment]
> I've just checked and in Geany we don't use the literate haskell part. Personally, I'd just remove it. Should I do it?

No, you should not do.

Instead, could you resolve the conflict?

**Comment by masatake** [comment]
Thank you very much.

**Pull request merged**
