### PR TITLE
docs: man page with non-ASCII character (#2901, #2903, #2905) 

### PR DESCRIPTION
**Pull request by masatake**
See #2905.

### CODE REVIEW

**Comment by masatake** [comment]
```
2021-03-09T09:03:49.3794638Z Traceback (most recent call last):
2021-03-09T09:03:49.3795322Z   File "./misc/units.py", line 1317, in <module>
2021-03-09T09:03:49.3796540Z     main()
2021-03-09T09:03:49.3797688Z   File "./misc/units.py", line 1314, in main
2021-03-09T09:03:49.3799708Z     sys.exit(func(subparser, *sys.argv[1:]))
2021-03-09T09:03:49.3801198Z   File "./misc/units.py", line 1227, in action_tmain
2021-03-09T09:03:49.3802926Z     ret = tmain_run(res.tmain_dir, build_dir, UNITS)
2021-03-09T09:03:49.3804386Z   File "./misc/units.py", line 1168, in tmain_run
2021-03-09T09:03:49.3805800Z     tmain_compare_result(build_topdir)
2021-03-09T09:03:49.3807334Z   File "./misc/units.py", line 999, in tmain_compare_result
2021-03-09T09:03:49.3808714Z     print("\t" + l, end='')
2021-03-09T09:03:49.3810468Z   File "D:/a/_temp/msys/msys64/mingw64/lib/python3.8/encodings/cp1252.py", line 19, in encode
2021-03-09T09:03:49.3812452Z     return codecs.charmap_encode(input,self.errors,encoding_table)[0]
2021-03-09T09:03:49.3816487Z UnicodeEncodeError: 'charmap' codec can't encode character '\ufffd' in position 39: character maps to <undefined>
2021-03-09T09:03:49.3932438Z make: *** [Makefile:6071: tmain] Error 1
```

**Comment by leleliu008** [comment]
```
	--- D:/a/ctags/ctags/Tmain/input-encoding-option.d/tags-actual.txt	2021-03-09 09:03:31.593756900 +0000
	+++ ./Tmain/input-encoding-option.d/tags-expected.txt	2021-03-09 09:01:00.580626200 +0000
Traceback (most recent call last):
  File "./misc/units.py", line 1317, in <module>
	@@ -0,0 +1,14 @@
    main()
	+!_TAG_FILE_ENCODING	UTF-8	//
  File "./misc/units.py", line 1314, in main
	+!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
    sys.exit(func(subparser, *sys.argv[1:]))
	+!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
  File "./misc/units.py", line 1227, in action_tmain
	+!_TAG_OUTPUT_EXCMD	mixed	/number, pattern, mixed, or combineV2/
    ret = tmain_run(res.tmain_dir, build_dir, UNITS)
	+!_TAG_OUTPUT_FILESEP	slash	/slash or backslash/
  File "./misc/units.py", line 1168, in tmain_run
	+!_TAG_OUTPUT_MODE	u-ctags	/u-ctags or e-ctags/
    tmain_compare_result(build_topdir)
	+!_TAG_PATTERN_LENGTH_LIMIT	96	/0 for no limit/
  File "./misc/units.py", line 999, in tmain_compare_result
	+!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
    print("\t" + l, end='')
	+!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
  File "D:/a/_temp/msys/msys64/mingw64/lib/python3.8/encodings/cp1252.py", line 19, in encode
	+!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
	+!_TAG_PROGRAM_VERSION	5.9.0	//
UnicodeEncodeError: 'charmap' codec can't encode character '\ufffd' in position 39: character maps to <undefined>
	+Foo	input.java	/^	public Foo() { \/\/ コンストラクタ$/;"	m	class:Foo
	+Foo	input.java	/^class Foo { \/\/ Fooクラス$/;"	c
make: *** [Makefile:6071: tmain] Error 1
```

why `D:/a/ctags/ctags/Tmain/input-encoding-option.d/tags-actual.txt` is empty?

**following command output noting:**
```
./ctags.exe --verbose --pseudo-tags=-TAG_PROC_CWD --input-encoding=utf-8 --input-encoding-java=shift_jis --input-encoding-javascript=euc-jp -o tags Tmain/input-encoding-option.d/input.js Tmain/input-encoding-option.d/input.java
```

**following command output as expected:**
```
./ctags.exe --verbose --pseudo-tags=-TAG_PROC_CWD --input-encoding=utf-8 --input-encoding-java=cp2312 --input-encoding-javascript=euc-jp -o tags Tmain/input-encoding-option.d/input.js Tmain/input-encoding-option.d/input.java
```

**Comment by masatake** [comment]
Times cures all.

**Comment by leleliu008** [comment]
image

**Pull request merged**
