### PR TITLE
add artifacts to appveyor.yml

### PR DESCRIPTION
**Pull request by kozo2**
https://ci.appveyor.com/project/kozo2/ctags/build/1.0.2

### CODE REVIEW

**Comment by masatake** [comment]
Could you tell me the benefit of this change in short?

**Comment by kozo2** [comment]
It seems there is no release and downloads in https://ctags.io/
https://ci.appveyor.com/api/buildjobs/wcujskoqjae8wba8/artifacts/ctags.exe
might be useful for who don't want to build ctags themselves.

**Comment by masatake** [comment]
My understanding is that Windows user can try the latest ctags without building.

With your change  Witndows users can get the latest binary from 
https://travis-ci.org/universal-ctags/ctags/artifacts/ctags.exe?

Am I correct?

**Comment by kozo2** [comment]
Yes, right. > My understanding is...

No, the link is  from appveyor not from travis. > With your change...
https://ci.appveyor.com/project/kozo2/ctags/build/1.0.2

users can get the latest binary from 
https://ci.appveyor.com/project/APPVEYORUSERNAME/ctags/build/FOREACHBUILD

I will update README.md.

**Comment by masatake** [comment]
> I will update README.md.

Thanks in advance.

**Comment by masatake** [comment]
@k-takata, I have a questoin about appveyor.
As far as seeing URL, at travis-ci we have our organization(universal-ctags) own directory like https://travis-ci.org/universal-ctags/ctags/builds/114738509 .

In other hands, at appveyor we don't have such directory and my account is embedded in URL like  https://ci.appveyor.com/project/masatake/ctags/build/1.0.729. 

Is this o.k. ? I wonder what happens if I die today...

**Comment by vhda** [comment]
@masatake don't you dare doing that us! ;)

**Comment by masatake** [comment]
o.k. I will use my account. Using my account is better than using @kozo2's account:-P

**Comment by masatake** [comment]
@kozo2, thank you.

**Pull request merged**
