### PR TITLE
Improve BASIC support

### PR DESCRIPTION
**Pull request by dkearns**
- Adds the *.bm extension (used for BASIC include files).
- Fixes a bug where comments with trailing colons were matched as labels.
- Reviews the old BASIC and BlitzBASIC test cases.

### CODE REVIEW

**Comment by masatake** [comment]
Thank you. Please remove "WIP" when this pull request is ready to be merged.

**Comment by masatake** [comment]
@dkearns, how do you do?
I reviewed all the changes. Though you marked "WIP", these changes are acceptable.
Can I merge this?

BTW, thank you for reviewing files under "review-needed.r".

**Comment by dkearns** [comment]
@masatake Sorry, I've been sidetracked so I'll come back to this later.

Yes, please merge.

**Comment by masatake** [comment]
Thank you. Especially about reviewing the "review-needed.r" test cases.

**Pull request merged**
