### PR TITLE
Units, Perl: review tests under review-needed.r

### PR DESCRIPTION
**Pull request by dkearns**
Moved all tests to parser-perl.r

Renamed Package.pm.d to lowercase equivalent as per the prevailing
style.

Fixes issue #943.

### CODE REVIEW

**Comment by dkearns** [comment]
@masatake I just noticed that you tend to use your fork for originating pull requests. Would you like me to delete this one and do the same?

**Comment by masatake** [comment]
> @masatake I just noticed that you tend to use your fork for originating pull requests. Would you like me to delete this one and do the same?

Yes, I would like you to do the same as I do. Basically we should not make an extra branch at universal-ctags official repository unless you have a strong reason.

**Comment by masatake** [comment]
@dkearns, anyway I will merge this.

**Comment by masatake** [comment]
Thank you.

**Comment by masatake** [comment]
Thank you. I guess you may have much more patch:-P.
Feel free to add yourname to docs/developers.rst. 
I would like to know the area of your interests.

**Pull request merged**
