### PR TITLE
Tag macros and header files in dts

### PR DESCRIPTION
**Pull request by masatake**
See the each commit log and the change in the test case.

### CODE REVIEW

**Comment by ARivottiC** [comment]
Nice, I was wondering about this but didn't had the time. Thank you @masatake.

**Comment by masatake** [comment]
@ARivottiC, I have a question about dts.
As far as reading dts and dtsi files in the latest linux kernel code, I cannot find any line where phandle is used. What does it mean?  (labels are used widely.)

**Comment by ARivottiC** [comment]
@masatake, a phandle is a reference for another node:

node1 { ... }
node2 {
    a-property = <&node1>
}

When converting Device Tree Blobs (dtb) to dts, you'll get something like this:

node1 { 
    phandle = <0x01>
}
node2 {
    a-property = <0x01>
}

**Comment by masatake** [comment]
@ARivottiC, do you mean we can see lines using phandle only when converting Device Tree Blobs (dtb) to dts?

**Comment by ARivottiC** [comment]
@masatake that's the use case I'm used to. In fact, my contribution is due to the fact I was comparing two dtb files and it was a pain going back and fourth with the phandle references.

**Comment by masatake** [comment]
```
node1 { ... }
node2 {
a-property = <&node1>
}
```
How about node1?
When reading  `a-property = <&node1>` line of the original dts file, I guess the reader may want to know the line where node1 is defined.

**Comment by ARivottiC** [comment]
My bad! "node1" is a label, should be something like:

node1: node@0 {...}

**Comment by masatake** [comment]
I see. Thank you.

**Comment by masatake** [comment]
I would like to ask you one more question.

As far as reading kernel code `};` is used to close an elemenet(?). But elements in your examples are closed
with just `}'. I cannot find `;`. Do you have any idea about this difference?

(I'm working on implementing scope in dts. To track the scope I have to the closer of elements.)

**Comment by ARivottiC** [comment]
Again you are right. I forgot the ;.

**Comment by masatake** [comment]
Thank you. I will add ';' to the test case.

**Pull request merged**
