### PR TITLE
appveyor: Additional fixes for #1445

### PR DESCRIPTION
**Pull request by k-takata**
* It is not recommended to update only specified packages. (ArchWiki says so.)
  Use `pacman -Suy` as usual.
* Use `checkupdates` to check if there are any updates.
* Remove unused toolchain before updating so that reduce the time for updating.
  (Unfortunately, it takes about 3 ~ 5 minutes even with this workaround.)
* Use default setting when updating Cygwin packages.
* Stop building msys2 binary before testing MSVC binary. This reduces about 30 sec.
* Use 64-bit Cygwin instead of 32-bit version. 64-bit version is about 1 minute faster.

### CODE REVIEW

**Comment by k-takata** [comment]
Tests on AppVeyor take 30 minutes after this change. Very long...

**Comment by k-takata** [comment]
I reduced the build time on AppVeyor, but still take nearly 30 minutes.
Maybe there are two options to reduce the build time:

* Build both 64-bit and 32-bit MSYS2 builds in one job.
  This will reduce overhead of updating MSYS2 system, but the build script becomes complex.
* Stop creating a zip package for each build and stop updating MSYS2 system.
  Use AppVeyor's scheduled build to create Windows zip packages instead. It would be enough to create a zip package once a day.

**Comment by k-takata** [comment]
> Maybe there are two options to reduce the build time:

I think that the second option is the best. I have updated the build script.

* For normal builds:
  * Don't create zip packages.
  * Stop updating msys2 packages.
  * Test only on 32-bit msys2, 64-bit msvc and 64-bit cygwin.
    Skip testing on 64-bit msys2.
* For scheduled daily builds or tagged builds:
  * Create zip packages and test on both 32- and 64-bit msys2.

Normal builds now take less than 15 minutes.
https://ci.appveyor.com/project/masatake/ctags/build/1.0.2177
Scheduled builds take about 20 minutes.
https://ci.appveyor.com/project/k-takata/ctags/build/1.0.204

To make this work, @masatake you need to change the setting of AppVeyor.
See: https://www.appveyor.com/docs/build-configuration/#scheduled-builds
Open "Settings" -> "General" -> "Build schedule", then set to `0 0 * * *` if you want to run the daily builds on 0:00 UTC.
What do you think?

**Comment by masatake** [comment]
@k-takata, currently we use AppVeyor on my account. How do you think use your account instead?
So you can do everything you want, and is good for us. Anyway I will take a look about the schedule.

**Comment by k-takata** [comment]
As far as I know, I don't have enough github permissions to run AppVeyor on my account.
Another option would be that you invite me as a collaborator on AppVeyor. I haven't use AppVeyor's team feature, though.

**Comment by masatake** [comment]
> As far as I know, I don't have enough github permissions to run AppVeyor on my account.

Now I add you to "Code/CI-Admin". As far as I know this one attach you to the highest(?) permission to you.
If you still have a trouble, I will look into AppVeyor's team feature.

**Comment by k-takata** [comment]
Now I'm setting up a new AppVeyor account for this project.
Cf. http://help.appveyor.com/discussions/questions/1154-appveyor-account-for-github-organizations

The project URL is:
https://ci.appveyor.com/project/universalctags/ctags
(Actually I wanted to use `universal-ctags` but it became `universalctags`. Not sure why.)

**Comment by k-takata** [comment]
@masatake 
I added you as a collaborator of universalctags AppVeyor account.
And now, two webhooks are installed on this github project. So I disabled your AppVeyor webhook.

**Comment by k-takata** [comment]
Oops. I mistakenly disabled my new webhook instead of masatake's one. Fixed.

**Comment by k-takata** [comment]
@masatake 
I think I should add my name in `docs/developers.rst` as a maintainer of appveyor setting.
The document says "Keep the list in alphabetical order.", but it is not kept so...

**Comment by masatake** [comment]
> I think I should add my name in docs/developers.rst as a maintainer of appveyor setting.
The document says "Keep the list in alphabetical order.", but it is not kept so...

Can I ask you to fix the order  when adding your name to the list?

**Comment by k-takata** [comment]
I setup scheduled builds to run at 0:00 UTC.
The first daily build will be executed about 7 hours later from now. Let's see what happen.

> Can I ask you to fix the order when adding your name to the list?

okay.

**Comment by k-takata** [comment]
https://ci.appveyor.com/project/universalctags/ctags/build/1.0.7
The first daily build has been built fine.

**Pull request merged**
