### PR TITLE
main: revise the code for rendering pattern field

### PR DESCRIPTION
**Pull request by masatake**
The responsibility for rendering pattern field was not clear.
json and ctags writers did their own way.

This commit moves the rendering code to field.c and make the
writers use functions exported from field.c.

Signed-off-by: Masatake YAMATO <yamato@redhat.com>

### CODE REVIEW

**Comment by tmm1** [comment]
👍 very nice cleanup.

**Comment by masatake** [comment]
Thank you. I will merge this after passing the test on CI.

**Comment by masatake** [comment]
Updated. A file tag has not pattern. (As you mentioned in a comment in .c file.)

**Comment by masatake** [comment]
I will squash some of commits.

**Pull request merged**
