### PR TITLE
Set return value when option file already considered

### PR DESCRIPTION
**Pull request by ffes**
This fixes issue #349

### CODE REVIEW

**Comment by masatake** [comment]
Could you try to make a test under Tmain?

**Comment by masatake** [comment]
I found extra hack was needed in ctags/tmain side. So I wrote a test case for this one by myself. Thank you.

**Comment by vhda** [comment]
Seeing this PR being closed without merging left me confused. Had to check the commit log to understand what happened.

**Comment by masatake** [comment]
@vhda, I'm sorry. I added extra commits to the merged branch.
Should I merge before adding extra commits?

**Comment by vhda** [comment]
Don't worry too much, it's just that I mostly track the updates through github's emails. When this type of things happen or when commits are directly pushed I miss those updates.
But you could have merged, rebased your commits over the latest commit and PR those updates. Although this requires a bit more work, it would give more visibility to the changes, specially if people work like I do :)

**Pull request closed without merging**
