### PR TITLE
main,docs(web),cosmetic: update code comment

### PR DESCRIPTION
**Pull request by jafl**

### CODE REVIEW

**Comment by masatake** [comment]
It seems that d89c9f279766479ff02ef6ca519a1637b418fee6, a chnage I introduced ago, causes a trouble.

[Units/parser-javascript.r/1880687.js.d/input.js](https://github.com/universal-ctags/ctags/pull/3424/commits/f50fb86dbd623e92d7d1594ec029b87a9467d9b2#diff-f31b95120b6ea91dcf46b0b2d091314d2ef1cb8bbb74a85c3ece5a63e166f675) I will try to find the way not to include this change.

**Comment by masatake** [comment]
I hope #3425 eliminates the trouble of the unexpected change.
I will merge #3425 soon. So could you wait for a while?

I would like to write what to do when a developer encounters the same trouble to our document.
So I want to understand what happens more.

Could you tell me your editor and OS?
I'm using Emacs on GNU/Linux.

**Comment by masatake** [comment]
I merged #3425. Could you rebase this change on the latest master branch?

After rebasing, "git restore Units/parser-javascript.r/1880687.js.d/input.js" may work well.

So, after rebasing, you may want to do...
```
git reset HEAD^
git restore Units/parser-javascript.r/1880687.js.d/input.js
git add docs/internal.rst main/entry.h
git commit ...
```

This may be applicable to your #3363, too.

**Comment by jafl** [comment]
> Could you tell me your editor and OS? I'm using Emacs on GNU/Linux.

I'm using Code Crusader on MacOS.

**Comment by masatake** [comment]
@jafl Is the change for Units/parser-javascript.r/1880687.js.d/input.js intentional?
If yes, I would like you to split the commit into two. I never say split this pull request into two.

If not, the steps I showed may help you delete unintentional change from your commit.

**Comment by jafl** [comment]
It was not intentional.  I removed it from the PR.

**Review by masatake — APPROVED** [review]

**Pull request merged**
