### PR TITLE
travis-ci: do out-of-tree build

### PR DESCRIPTION
**Pull request by masatake**

### CODE REVIEW

**Comment by masatake** [comment]
It works!

**Comment by masatake** [comment]
It seems that the change has no effect.

**Comment by k-takata** [comment]
Coverage status looks incorrect after this PR. It cannot be 100%.

**Comment by masatake** [comment]
@k-takata, thank you. 
I will inspect this.

**Comment by masatake** [comment]
Fixed. Thank you.

**Pull request merged**
