### PR TITLE
GitHub Actions: run units target on freebsd

### PR DESCRIPTION
**Pull request by leleliu008**

### CODE REVIEW

**Comment by masatake** [comment]
Thank you. LGTM. Before merging could you change the commit header to "GitHub Actions: run units target on freebsd" ?

**Comment by masatake** [comment]
roundtrip test reports many warnings about sed.
You can choose one of
(1) removing roundtrip target from the test set,
(2) install gnu sed and use it, or
(3) fix the sed command line (as far as I can remember it is very complicated). Any of them is acceptable.

**Comment by leleliu008** [comment]
@masatake 
1. the warning of sed utility has been fixed.
2. do you wish me to squash `6cdb815` and `1829d3b` into one commit?

**Comment by masatake** [comment]
> 1. the warning of sed utility has been fixed.

Great!

> 2. do you wish me to squash 6cdb815 and 1829d3b into one commit?

Yes. You know what I want.

**Review by masatake — APPROVED** [review]

**Comment by masatake** [comment]
I will merge this. 

@k-takata, please let us know if there is something wrong in the pull request.

**Pull request merged**
