### PR TITLE
javascript: improved parsing of anonymous functions

### PR DESCRIPTION
**Pull request by jafl**
This is much simpler than #2005

### CODE REVIEW

**Comment by jafl** [comment]
@masatake If I do a major refactor of `parseStatement` to break it up, will that cause major pain for any of your other jscript.c PR's?

**Comment by masatake** [comment]
Incredible!

**Review by masatake — APPROVED** [review]

**Comment by masatake** [comment]
Let's ignore the testing on NetBSD.

**Comment by masatake** [comment]
> @masatake If I do a major refactor of `parseStatement` to break it up, will that cause major pain for any of your other jscript.c PR's?

I submitted #3433 and #3435. However, I don't care if your future pull request breaks them. Refactoring has a much higher priority!

**Comment by masatake** [comment]
BTW if you want to let users of the JavaScript parser know the design of the parser, you can write a man page for it. See https://docs.ctags.io/en/latest/man-pages.html and https://docs.ctags.io/en/latest/man/ctags-lang-python.7.html as examples.

**Pull request merged**
