### PR TITLE
R: support vector, list, data.frame and named attributes in them

### LINKED ISSUE #2823: R,R6Class: jump to anonFunc####
Sorry if I missed the docs, I have an R6 object in `R` which have methods defined inside a list, and I have the same methods written in `C++` classes. `ctags` generated both `R` and `C++` method but the R one is named with `anonFuncxxx`, which I cannot jump to and not found when e.g. using `fzf` search (in `Vim`), e.g.

```R
|240  anonFunc75e1a69f0103  GitHub/eppasm/R/infections.R  /^infect_mix = function(hivpop, artpop, ii|
```

```C++
|2399 infect_mix  GitHub/eppasm/src/infectionProcesses.cpp  /^void popC::infect_mix (hivC& hivpop, a| 
```

how could I jump to the R's one using its name?

### PR DESCRIPTION
**Pull request by masatake**
Close #2823.

With this change, ctags can extract in  https://github.com/kklot/eppasm/blob/1988/R/popClass.R.
```
$ u-ctags  --kinds-R=+n --fields=+ne  -o - popClass.R | grep ^infect_mix
infect_mix	popClass.R	/^infect_mix = function(hivpop, artpop, ii) {$/;"	n	line:381	vector:popFunc	end:402	constructor:function
```

DONE:
-  split the last commit into smaller ones (if possile), and
-  write a man page for R parser (and its subparsers).

### CODE REVIEW

**Comment by masatake** [comment]
It seems that data.frame can have name attributes.

**Comment by kklot** [comment]
I `brew unlink ctags`, build and install [your branch](https://github.com/masatake/ctags/tree/R-support-vector-and-nameattr) and run; there is a warning (did I do something wrong?)

```bash
ctags --kinds-R=+n --fields=+ne  -o - popClass.R
ctags: Warning: Unsupported kind: 'n' for --kinds-R option
```

There are outputs, but without `infect_mix` and some weird catches like this one.

```
'Thiscanbedonedirectlywith`	popClass.R	/^    'This can be done directly with `<-` using pop_object$data'$/;"vline:38
````

**Comment by masatake** [comment]
See [`https://gist.github.com/masatake/590f0cc44a69786aca7cb83dd0fb1afb`](https://gist.github.com/masatake/590f0cc44a69786aca7cb83dd0fb1afb) . I'm using Fedora33.

**Comment by kklot** [comment]
Thanks, I think have those new options `c` and `n` now, but still no `infect_` shows :/ . I'm using Mac though.

```
$ ctags --list-kinds=R
f  functions
l  libraries
s  sources
g  global variables
v  function variables
z  function parameters inside function definitions [off]
c  vector explicitly created with `c()'
n  names attribtes in a vector
$ctags --kinds-R=+n --fields=+ne  -o - popClass.R | grep ^infect_
```

My output tags [tags.zip](https://github.com/universal-ctags/ctags/files/5861499/tags.zip)

**Comment by masatake** [comment]
I guess we are using different input files. I'm not sure this is the reason of differences.

```
[jet@note]~/var/ctags-new% sha1sum /tmp/eppasm/R/popClass.R
sha1sum /tmp/eppasm/R/popClass.R
f2928337ba8480633bb45cc3571aeaf6e16ba249  /tmp/eppasm/R/popClass.R
[jet@note]~/var/ctags-new% grep -n save_prev_n_inc /tmp/eppasm/R/popClass.R
grep -n save_prev_n_inc /tmp/eppasm/R/popClass.R
371:save_prev_n_inc = function() {
[jet@note]~/var/ctags-new% (cd /tmp/eppasm/R; git log --oneline  | head)
(cd /tmp/eppasm/R; git log --oneline  | head)
71767c7 looping by pointers
76d98dc take out year dimension with View class
48d7ebf change classes to struct
8568f23 add Jeff's parameter classes
e489761 separate fitmod() contents
77c8258 add lines to fitting functions to fit other models
120f5d9 run with Model, StateSpace, Parameters, outputSEXP classes
d412152 speed up from 5x to 3x vs current code
9467072 delete old files
47d0b26 integer to logical
```

**Comment by masatake** [comment]
I'm sorry. It seems that I'm looking at popClass.R in a wrong branch.

**Comment by masatake** [comment]
What I should use as an input is https://github.com/kklot/eppasm/blob/1988/R/infections.R.
```
[jet@note]~/var/ctags-new% sha1sum ./infections.R
sha1sum ./infections.R
860f53477c25ceeb9c040587305ed51a911cce85  ./infections.R
[jet@note]~/var/ctags-new% ./ctags --options=NONE --sort=no --kinds-R=+n --fields=+ne  -o - ./infections.R  | grep ^infect_mix
./ctags --options=NONE --sort=no --kinds-R=+n --fields=+ne  -o - ./infections.R  | grep ^infect_mix
ctags: Notice: No options will be read from files or environment
infect_mix	./infections.R	/^infect_mix = function(hivpop, artpop, ii) {$/;"	n	line:5	vector:infectFns	end:66	constructor:function
```

**Comment by kklot** [comment]
silly me, I should have caught that I'm on a different file. Yes it works now, thanks.

**Review by kaycoinsUSA — APPROVED** [review]
Done

**Comment by masatake** [comment]
Nont only c and data.frame but also list supports the name attributes.
In addition, signatures of functions have similar form.
I wonder I can unify the code for parsing them.

**Comment by masatake** [comment]
I find many inconsistent code in R paresr during working on this pull request.
I will fix the inconsistent code first.

**Comment by masatake** [comment]
This should be rebased on #2844.

**Pull request merged**
