### PR TITLE
adding forth ctags (optlib based)

### PR DESCRIPTION
**Pull request by masatake**
(@masatake converted to the original forth.c proposed in #3809 to forth.ctags.)

### CODE REVIEW

**Comment by masatake** [comment]
@farvardin we need more test cases that show this optlib-based implementation doesn't satisfy you.

What I need are pairs of (input.forth, expecected.tags).

**Comment by farvardin** [comment]
> @farvardin we need more test cases that show this optlib-based implementation doesn't satisfy you.
> 
> What I need are pairs of (input.forth, expecected.tags).

It should be satisfying :)
It just doesn't look comptatible with geany, but other IDE are using ctags anyway...

I've put some examples there:

https://github.com/universal-ctags/ctags/pull/3809#discussion_r1321365984

**Comment by farvardin** [comment]
> What I need are pairs of (input.forth, expecected.tags).

I've managed to make a working optlib regex:

```
--kinddef-Forth=w,word,words
--kinddef-Forth=v,variable,variables
--kinddef-Forth=c,constant,constants

--regex-Forth=/^:[[:space:]]*([^[:space:]]+)/\1/w/
--regex-Forth=/^(variable|VARIABLE)[[:space:]]*([^[:space:]]+)/\2/v/
--regex-Forth=/^([[:alnum:]]+)[[:space:]](constant|CONSTANT)[[:space:]]*([^[:space:]]+)/\3/c/
```

it should catch correctly to give this result:

```
DUMMY1	input.fth	/^10 constant DUMMY1$/;"	c
DUMMY2	input.fth	/^12 constant DUMMY2$/;"	c
dummy3	input.fth	/^variable dummy3$/;"	v
dummy4	input.fth	/^variable dummy4$/;"	v
dummy5	input.fth	/^VARIABLE dummy5$/;"	v
fizz?	input.fth	/^: fizz?  $/;"	w
buzz?	input.fth	/^: buzz?  $/;"	w
fizz-buzz?	input.fth	/^: fizz-buzz?  $/;"	w
do-fizz-buzz	input.fth	/^: do-fizz-buzz  $/;"	w
```

I'll make a PR ASAP (on a branch this time)

**Comment by masatake** [comment]
See #3812.

**Pull request closed without merging**
