### PR TITLE
main: Fix double inclusion of OptionLoadingStage typedef

### PR DESCRIPTION
**Pull request by vhda**
Fix for #466

### CODE REVIEW

**Comment by masatake** [comment]
As you know already this comes from circular dependencies in header inclusion. 

I could find the best way when I introduced OptionLoadingStage.

How about moving all *Option to options.h?
I cannot say it is the best but I feel moving just processXcmdOption is a bit inconsistent with other process*Option functions.

**Comment by vhda** [comment]
What you say makes sense and it apparently works.
Other than the `/process.*Option/` functions, do you think we should move any other definitions to options.h?

**Comment by masatake** [comment]
I think  /print.*Option/ also should be moved to options.h.

**Comment by vhda** [comment]
From a coherency point of view, should we move anything else?

**Comment by masatake** [comment]
No. I think we should not move anymore.

**Comment by vhda** [comment]
Could you please check now?

**Comment by masatake** [comment]
Fine, thank you.

**Comment by vhda** [comment]
Simple changes, so I won't wait longer for merging :)

**Pull request merged**
