### PR TITLE
Locate packcc in build directory instead of the source

### PR DESCRIPTION
**Pull request by Myz**
This should fix a Out-of-source or nested build.

Related to #2029.

### CODE REVIEW

**Comment by b4n** [comment]
Looks reasonable.  We should have an out-of-tree build on CI I guess, it's always nice to catch these kind of things early.

**Comment by masatake** [comment]
NOTE: out-of-tree build can be done with `cd $(mktemp -d) && git clone https://github.com/universal-ctags/ctags.git && cd ctags && ./autogen.sh && mkdir mybuild && cd mybuild && ../configure && make -j10` as @Myz written in @2029.

**Comment by masatake** [comment]
Thank you!

**Comment by Myz** [comment]
Anytime

**Pull request merged**
