### PR TITLE
Fix tests on *BSD

### PR DESCRIPTION
**Pull request by oridb**
/bin/sh is not bash. misc/units contains bashisms. The simplest solution is to invoke it using bash.

### CODE REVIEW

**Comment by masatake** [comment]
Debian people may want removing dependency to bash.

**Comment by masatake** [comment]
Could you try #935?

**Comment by oridb** [comment]
#935 seems to work on FreeBSD. I'll try on a couple of other /bin/sh implementations later, but if removing bashisms, I'll close this.

**Comment by masatake** [comment]
Thank you for the verification.

**Pull request closed without merging**
