### PR TITLE
Javascript ES6 methods, test for #780

### PR DESCRIPTION
**Pull request by hoschi**
As said in #1068 I want to contribute tests. For #1068 there is already a test in the commit of @b4n. So, I created a test for #780 instead.

### CODE REVIEW

**Comment by masatake** [comment]
Thank you.

I'm surprised at the notation ` A.getPropName() + 'test'`.
I wonder how this should be recorded in tags file. Obviously this is not a name. This is code generating a name of method.  I wonder such code should be recorded or not. If we should decide to record such code, I think we should provide the way to distinguish the code from the name to client tools that read tags file.

One of the approach is introducing new kind. Here  G(generatedMethod) is used as an example:
```
A.getPropName() + 'test'     input.js        /^    [A.getPropName() + 'test']() {$/;"      G       class:Obj
'gen' + 2     input.js        /^    *['gen' + 2]() {$/;"      G       class:Obj
```

How do you think about this?

**Comment by hoschi** [comment]
Good point! I thought not much about it, because I thought ctags has already a way to handle this dynamic properties for other languages. I see it is a problem, at least for editors (client tools example). The editor needs to recognize the whole string "'gen' + 2" as "a tag", for e.g. jumping to its definition/usage.

In my opinion your suggestion is sound. Gather the information, but don't treat it as a normal tag. Should I change the test cases to match your example? I can also remove the special syntax from this PR and create a second one, if you need more time to think about the problem/solution.

**Comment by masatake** [comment]
> The editor needs to recognize the whole string "'gen' + 2" as "a tag", for e.g. jumping to its definition/usage.

I don't have much chance to use Javascript. However, I cannot image the situation that a user of the editor specifies "''gen' + 2" as "a tag" for jumping.

In my limited experiencel "'gen' + 2"  tag can be used only for navigating and summarizing.
See http://docs.ctags.io/en/latest/contributions.html#specific-to-add-new-parser-and-or-new-kind-role
In the page, my assumption about how client tools utilizes tags file is written.

Do you think a kind of tool can utilize "'gen' + 2" for auto completion and jumping? 


Above I wrote is only a question coming from my curiosity. The question is never the reason to reject this pull request. However, the question is quite important for writing a good parser.

Splitting a test case into two is good idea. Let's use `G` as a kind letter for the generated names.
It is nice to add a short document about test case like README (https://github.com/universal-ctags/ctags/blob/master/Units/parser-python.r/newlines-cr.b/README) or DESC.rst(
https://github.com/masatake/ctags/blob/70f3db4f0c9d9ed862bda1077e8f3a218dc336ec/Units/parser-m4.r/m4-quotestring.b/DESC.rst).

I'm planning to generage  docs/known-issues.rst by merging all DESC.rst under Units directory.

**Comment by hoschi** [comment]
> Do you think a kind of tool can utilize "'gen' + 2" for auto completion and jumping?

I thought about something like that:
```
var Obj = {
    myMethod(a, b) {
    },
	*myGenerator(a, b) {
	},
	[A.getPropName() + 'test']() {
	},
	*['gen' + 2]() {
	}
}

var result = Obj['gen' + 2]();
```
Where the user wants to jump from the last line to the definition of the method. But in 99% of cases I can image, the developer would store the (dynamic) name of a method in constant or variable:
```
const dynamicMethodName = 'gen' + 2;
var Obj = {
    myMethod(a, b) {
    },
	*myGenerator(a, b) {
	},
	[A.getPropName() + 'test']() {
	},
	*[dynamicMethodName]() {
	}
}

var result = Obj[dynamicMethodName]();
```

> In my limited experiencel "'gen' + 2" tag can be used only for navigating and summarizing.

This would be a more realistic usage of the generated tags of this kind. E.g. an code outliner.

> It is nice to add a short document about test case like README or DESC

What would you see in this document for this PR? Is moving the comment lines from input.js with references to spec/examples to DESC.rst enough?

My next actions gathered from your response are:
* [ ] move generated method names into own PR, change tags file as mentoined above
* [ ] create a DESC.rst which points to this discussion for new PR
* [ ] create DESC.rst for this PR

**Comment by masatake** [comment]
Hm...ctags is a tool for tagging *names*. We are talking about expressions generating names.
Basically I think ctags should not deal with the expressions.

Do you have an interest in being maintainer of the javascript parser?
(I'm always looking for good parser maintainers.)

**Comment by hoschi** [comment]
> Hm...ctags is a tool for tagging names. We are talking about expressions generating names.
Basically I think ctags should not deal with the expressions.

I lost the context here.

> Do you have an interest in being maintainer of the javascript parser?
(I'm always looking for good parser maintainers.)

I'm pretty busy with my day job and unfortunately don't have the time to be a maintainer, at least yet. Would that involve writing C(++) code? Thanks anyway for thinking about me as parser maintainer :)

Can you answer my question about the content in the DESC file, so I can start tackling the todos?

**Comment by masatake** [comment]
> 
>
>>   Hm...ctags is a tool for tagging names. We are talking about expressions generating names.
>>    Basically I think ctags should not deal with the expressions.
>
> I lost the context here.
I'm sorry. 
How do I say... What you expected to Javascript parser of ctags is very different from what ctags can do now. ctags can record names and extra informatoins.

```
A.getPropName() + 'test'
```

This it not a name. This is an expression. ctags cannot record an expression.

I have an example which tells how difficult to handle an expression in ctags.

```
A.getPropName () + /* comment */ + 'test'
```
This is a valid expression. In this case what ctags should record as a tag?

* `A.getPropName () /* comment */ + 'test'`,
* `A.getPropName () + 'test'`,
* `A.getPropName ()+'test'`, or
* `A.getPropName()+'test'`.

To make tags file useful, the expression must be normalized when recording.
I don't know well about Javascript, but I guess there is no standard rule for normalizing an expression.
If we just deal with names, we don't have to think about normalization. (An exception is ObjectiveC.)

This is a just one minor example. The main part of ctags may need to be extended for recording expressions. 
How? I don't know. Someone who really want to record expressoins in ctags has to study how to extend ctags for recording expressions.

If we cannot find such person, I think we should abort recording expressions.

So I would like to merge shrunken version of the orignal test case:

input.js:
```
var Obj = {
    myMethod(a, b) {
    },
    *myGenerator(a, b) {
    },
    [A.getPropName() + 'test']() {
    },
    *['gen' + 2]() {
    }
}
```

expected.tags may contain only myGenerator and myMethod. In such case, the intent of test case is so obvious. Therefore no extra documentation is needed.

**Comment by masatake** [comment]
I'm sorry. I wrote too many things.
Let's start from adding small things. Complicated things can be dealt with later.

**Comment by hoschi** [comment]
Thanks for the deep explanation. I rebased and changed the PR to only contain myMethod and myGenerator.

**Comment by masatake** [comment]
Thank you.

**Pull request merged**
