### PR TITLE
build-sys: fix out-of-source builds failed due to No such directory: Units and Tmain

### LINKED ISSUE #2789: Out-of-source builds failed due to No such directory: Units and Tmain
run the following commands in the terminal:

```
git clone https://github.com/universal-ctags/ctags
cd ctags
./autogen.sh
mkdir build.d
cd build.d
../configure --prefix=$PWD/output
make clean
```

`make clean` failed and output logs as follow:

```
Cleaning test units
No such directory: /root/ctags/build.d/Units
Cleaning main part tests
No such directory: /root/ctags/build.d/Tmain
make: *** [clean-tmain] Error 1
```

resolved patch:
```
--- a/makefiles/testing.mak
+++ b/makefiles/testing.mak
@@ -140,8 +140,7 @@ units: $(CTAGS_TEST)

 clean-units:
        $(SILENT) echo Cleaning test units
-       $(SILENT) builddir=$$(pwd); \
-               $(SHELL) $(srcdir)/misc/units clean $${builddir}/Units
+       $(SILENT) $(SHELL) $(srcdir)/misc/units clean $(srcdir)/Units

 #
 # VALIDATE-INPUT Target
@@ -201,8 +200,7 @@ tmain: $(CTAGS_TEST) $(READ_TEST)

 clean-tmain:
        $(SILENT) echo Cleaning main part tests
-       $(SILENT) builddir=$$(pwd); \
-               $(SHELL) $(srcdir)/misc/units clean-tmain $${builddir}/Tmain
+       $(SILENT) $(SHELL) $(srcdir)/misc/units clean-tmain $(srcdir)/Tmain

 tlib: $(MINI_GEANY_TEST)
        $(V_RUN) \
```

### PR DESCRIPTION
**Pull request by leleliu008**
fix #2789

### CODE REVIEW

**Comment by masatake** [comment]
I'll inspect the reason why a test case,unreadable-input/stderr-compare,  fails.

**Comment by k-takata** [comment]
Is this PR correct?
When building out of source, the source directory should not be changed. Then no need to clean `$(srcdir)/Units` and `$(srcdir)/Tmain`.
The problem is that `$${builddir}/Units` and `$${builddir}/Tmain` don't exist before running the tests. So, I think that we should just ignore the error when `Units` and `Tmain` don't exist.

**Comment by masatake** [comment]
@k-takata, I agree.

The following change may fix #2789. 
```
diff --git a/makefiles/testing.mak b/makefiles/testing.mak
index b1a329df..1faf0a84 100644
--- a/makefiles/testing.mak
+++ b/makefiles/testing.mak
@@ -140,8 +140,10 @@ units: $(CTAGS_TEST)
 
 clean-units:
        $(SILENT) echo Cleaning test units
-       $(SILENT) builddir=$$(pwd); \
-               $(SHELL) $(srcdir)/misc/units clean $${builddir}/Units
+       $(SILENT) if test -d $$(pwd)/Units; then \
+               builddir=$$(pwd); \
+               $(SHELL) $(srcdir)/misc/units clean $${builddir}/Units; \
+       fi
 
 #
 # VALIDATE-INPUT Target
@@ -201,8 +203,10 @@ tmain: $(CTAGS_TEST) $(READ_TEST)
 
 clean-tmain:
        $(SILENT) echo Cleaning main part tests
-       $(SILENT) builddir=$$(pwd); \
-               $(SHELL) $(srcdir)/misc/units clean-tmain $${builddir}/Tmain
+       $(SILENT) if test -d $$(pwd)/Tmain; then \
+               builddir=$$(pwd); \
+               $(SHELL) $(srcdir)/misc/units clean-tmain $${builddir}/Tmain; \
+       fi
 
 tlib: $(MINI_GEANY_TEST)
        $(V_RUN) \
```

**Comment by masatake** [comment]
I implemented the idea suggested by @k-takata. See #2807.

**Comment by leleliu008** [comment]
@masatake  Yeah, I see.

**Pull request closed without merging**
