### PR TITLE
JavaScript: Add support for Unicode escape sequences

### PR DESCRIPTION
**Pull request by b4n**
Handle both kind of Unicode escape sequences inside strings and identifiers:

`"\u" Hex4Digits`: Hex4Digits is a 4 digits hexadecimal value representing a UTF-16 word (e.g. either a code point or a high or low surrogate).

`"\u{" HexDigits "}"`: HexDigits is any number of hexadecimal digits representing a Unicode code point (so must have an actual value less than or equal to 0x10FFFF).

Note: the previous code handling escape sequences outside string literals didn't seem to follow anything from the ECMAScript standard, so was simply removed.

See http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-262.pdf §11.8.4 "String Literals" for the definition of "UnicodeEscapeSequence".

### CODE REVIEW

**Comment by b4n** [comment]
Okay, OSX and MSVC should be all fixed now

**Comment by masatake** [comment]
I would like to review this after you merge the other pull requests you submitted.

**Comment by masatake** [comment]
I will review wihin this week.

**Comment by masatake** [comment]
Sorry, still I cannot find time for reviewing.  Please, wait for awhile.

**Comment by masatake** [comment]
MY TODO: 
It is nice that a parser can specify the sizeof ungetchBuf of inputFile when opening an input file.
This change specifies it 8 bytes statically.
openInputFile may have ability to do it. However, The consideration for nestedInputStream may be needed. Dynamic ungetchBuf may be needed to write a parser for Jinja2.

**Comment by masatake** [comment]
MY TODO:

The name of feature "multibyte" is really bad name. We should call it "iconv" or something.

**Comment by masatake** [comment]
I'm sorry to be late to review and merge this pull request.
Thank you.

**Pull request merged**
