### PR TITLE
man: Write about missing options

### PR DESCRIPTION
**Pull request by k-takata**
There are some options missing from the man page.
This PR adds them.
Some explanations are copied from news.rst.

(@masatake This is still WIP, and I pushed this to this repository (not mine) so that you can also update this branch.)

### CODE REVIEW

**Comment by k-takata** [comment]
Related: #657, (#1871)

**Comment by masatake** [comment]
> (@masatake This is still WIP, and I pushed this to this repository (not mine) so that you can also update this branch.)

I see. I must add (and/or update) descriptions for the options.

**Comment by k-takata** [comment]
Squashed two commits into one.
@masatake Do we have anything that needs to be written, or is this enough (as a first step)?

**Comment by masatake** [comment]
Please, wait for a week till merging.
I would like to enumerate TODO imtes releated to this issue.

**Comment by masatake** [comment]
> @masatake Do we have anything that needs to be written, or is this enough (as a first step)?

YES, please. Now I can image what parts of man pages should be updated.

**Comment by k-takata** [comment]
So, this is enough for the first step, and you will enhance the man pages later in separate PRs, right?

**Comment by masatake** [comment]
> So, this is enough for the first step, and you will enhance the man pages later in separate PRs, right?

YES.

**Comment by masatake** [comment]
To explain --list-mline-regex-flags, we have to explain "what is  mline regex parser?".

**Comment by k-takata** [comment]
OK, I merge this.

**Comment by k-takata** [comment]
After I merged this, I noticed the following error:

```
RST2MAN   man/ctags.1
man/ctags.1.rst:1454: (ERROR/3) Unexpected indentation.
```

It looks that this part is wrong:

```
``--pseudo-tags=[+|-]ptag``
``--pseudo-tags=*``
	Enable/disable emitting pseudo tag named ptag.
```

Maybe this should be:

```
``--pseudo-tags=[+|-]ptag``, ``--pseudo-tags=*``
	Enable/disable emitting pseudo tag named ptag.
```

or:

```
``--pseudo-tags=[[+|-]ptag|*]``
	Enable/disable emitting pseudo tag named ptag.
```

Not sure which is better.

**Pull request merged**
