### PR TITLE
tmain: remove generated files when doing make clean

### LINKED ISSUE #502: make clean doesn't clean test results in Tmain directory
E.g.

```
$ make check
$ make clean
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        Tmain/alias-for-unknown-language.d/stderr-actual.txt
        Tmain/alias-for-unknown-language.d/stderr-diff.txt
        Tmain/corpus-for-unknown-language.d/stderr-actual.txt
        Tmain/corpus-for-unknown-language.d/stderr-diff.txt
        Tmain/dot-ctags-with-indentation.d/stderr-actual.txt
        Tmain/dot-ctags-with-indentation.d/stderr-diff.txt
...
```

### PR DESCRIPTION
**Pull request by masatake**
Close #502.

### CODE REVIEW

**Comment by b4n** [comment]
`clean-tmain` doesn't seem to be hooked to `clean`, is that desired?

**Comment by masatake** [comment]
Oh, I will fix it.

**Comment by masatake** [comment]
Updated. Thank you.

**Comment by k-takata** [comment]
I confirmed that `make clean` cleans under `Tmain` directory.

**Comment by masatake** [comment]
Thank you, guys.

**Pull request merged**
