### PR TITLE
Add .gitignore, .hgignore and *~ emacs backup files to the built-in exclusion list

### PR DESCRIPTION
**Pull request by masatake**
Signed-off-by: Masatake YAMATO <yamato@redhat.com>

### CODE REVIEW

**Comment by ffes** [comment]
LTGM

**Comment by masatake** [comment]
Thank you for reviewing.

**Comment by b4n** [comment]
LGTM too.  But you might want to also add `.gitattributes` and `.mailmap` to the list maybe?

**Comment by masatake** [comment]
@b4n, thank you. 

None really needs following optlib?

> [yamato@x201]~/var/ctags-github% cat data/optlib/mailmap.ctags
cat data/optlib/mailmap.ctags
--langdef=mailmap
#--map-mailcap=+(.mailmap)
--mailmap-map=+(.mailmap)
--regex-mailmap=/^#.*$//{exclusive}
--regex-mailmap=/^([^<]{1,}) {1,}<.*/\1/n,name/{exclusive}
[yamato@x201]~/var/ctags-github% ./ctags -o - --options=data/optlib/mailmap.ctags ~/var/linux/.mailmap  | head -5
./ctags -o - --options=data/optlib/mailmap.ctags ~/var/linux/.mailmap  | head -5
Aaron Durbin	/home/yamato/var/linux/.mailmap	/^Aaron Durbin <adurbin@google.com>$/;"	n
Adam Oldham	/home/yamato/var/linux/.mailmap	/^Adam Oldham <oldhamca@gmail.com>$/;"	n
Adam Radford	/home/yamato/var/linux/.mailmap	/^Adam Radford <aradford@gmail.com>$/;"	n
Adrian Bunk	/home/yamato/var/linux/.mailmap	/^Adrian Bunk <bunk@stusta.de>$/;"	n
Al Viro	/home/yamato/var/linux/.mailmap	/^Al Viro <viro@ftp.linux.org.uk>$/;"	n

**Comment by b4n** [comment]
> None really needs following optlib?

Oops :)
If it's useful to people, keep it, I really don't mind, I just thought about those when seeing `.gitignore` and friends.

Though, if tagging mailmap is useful, it raises the question whether tagging other dofiles like .*ignore wouldn't be?  I can't seem to imagine a use case, but neither would I have thought one would want to tag mailmaps, so I might just not see a use case.

**Comment by masatake** [comment]
It's a bit joke.

However, we reach the critical question: what is ctags?

My idea:
In a line in a file something name is defined, the name, the line number and the file should be tagged.
Here the name has associated value including NULL.

Applying to mailmap:
The name of person is defined in the mailcap file. Here an associated value is mail address.
Someone may say the mail address is definedin the file. In this case an associate value is the name of person. I should introduce a,address, too.

I cannot find naturally way to apply my idea to .gitignore.

... I will merge the current commits.  I would like to make this mailmap thing pending.
I will write "what should be tagged" in "criteria.rst".
I want people, especially you to review the document.

**Comment by masatake** [comment]
(As far as reading the man page of git short-log, the mailmap format is not so simple as I expected.)

**Pull request merged**
