### PR TITLE
man-test: new test harness

### PR DESCRIPTION
**Pull request by masatake**
`man-test` is a new test harness for testing examples in per-language man pages (man/ctags-lang-\*.7.rst.in).

If you have python3, you can run it with "make man-test."

TODO:
- ~documentation for writing a test case~
- ~running on CI/CD environment~

### CODE REVIEW

**Comment by masatake** [comment]
It seems that `{` is a metacharacter on Cygwin.

**Comment by hirooih** [comment]
This is a good idea.  But I'm concerned about two issues.

- restricting contents (format) of man page
- restricting the name of input file.

ex. https://docs.ctags.io/en/latest/man/ctags-lang-julia.7.html

There must be the following lines in the document.

```
“input.jl”
```

and

```
“output.tags” with “--options=NONE -o - --extras=+r --fields=+rzK input.jl”
```

I think it is better not to force such restriction.
How about using original [directive](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#directives) of reStructuredText?

```
From input file;

.. MAKE_TEST::input

.. code-block:: Julia

	using X0

.. MAKE_TEST::options -o - --extras=+r --fields=+rzKZ foo.jl

ctags outputs the following tags with option “-o - --extras=+r --fields=+rzK foo.jl”;

.. MAKE_TEST::output

.. code-block:: tags

	X1	foo.jl	/^import X1.a, X2.b, X3$/;"	kind:module	roles:namespace
	X2	foo.jl	/^import X1.a, X2.b, X3$/;"	kind:module	roles:namespace
	X3	foo.jl	/^import X1.a, X2.b, X3$/;"	kind:module	roles:imported
	a	foo.jl	/^import X1.a, X2.b, X3$/;"	kind:unknown	scope:module:X1	roles:imported
	b	foo.jl	/^import X1.a, X2.b, X3$/;"	kind:unknown	scope:module:X2	roles:imported

```

I delete `--options=NONE`, because it is not necessary for readers.  Test script should add it and a developer can handle it if he/she knows about it from contributsions.rst.
The last word of MAKE_TEST:options will be the name of input file.

Another idea is forcing the first line of output as a command line as I did for examples in ctags(1).

```
From input file;

.. MAKE_TEST::input

.. code-block:: Julia

	using X0

.. MAKE_TEST::output

ctags outputs the following tags;

.. code-block:: console

	$ ctags -o - --extras=+r --fields=+rzK foo.jl
	X1	foo.jl	/^import X1.a, X2.b, X3$/;"	kind:module	roles:namespace
	X2	foo.jl	/^import X1.a, X2.b, X3$/;"	kind:module	roles:namespace
	X3	foo.jl	/^import X1.a, X2.b, X3$/;"	kind:module	roles:imported
	a	foo.jl	/^import X1.a, X2.b, X3$/;"	kind:unknown	scope:module:X1	roles:imported
	b	foo.jl	/^import X1.a, X2.b, X3$/;"	kind:unknown	scope:module:X2	roles:imported

```

Again, test script should add  `--options=NONE`.

One good point of this is no warning by Pygments.

Above is just my idea.  Feel free to ignore if you don't like it.

**Comment by hirooih** [comment]
> restricting the name of input file.

There may be no such restriction.  I did not read your script.
I wrote this because you changed names of input files on this pull-request.

**Comment by masatake** [comment]
Thank you for the comment.

My script forces the naming of the input file as you guessed.

I like your idea, embedding the command line for testing.
 
```
From input file;

.. man-test:: TITILE
       :features: XML
       :language: 

.. code-block:: XSLT

	INPUT

ctags outputs the following tags; (or something as you want to write)

.. man-expect:: 
.. code-block:: console

	$ ctags -o - --extras=+r --fields=+rzK foo.xslt
	X1	foo.jl	/^import X1.a, X2.b, X3$/;"	kind:module	roles:namespace
	X2	foo.jl	/^import X1.a, X2.b, X3$/;"	kind:module	roles:namespace
	X3	foo.jl	/^import X1.a, X2.b, X3$/;"	kind:module	roles:imported
	a	foo.jl	/^import X1.a, X2.b, X3$/;"	kind:unknown	scope:module:X1	roles:imported
	b	foo.jl	/^import X1.a, X2.b, X3$/;"	kind:unknown	scope:module:X2	roles:imported

```

The options and input file name can be extracted from the first line started from `$`.
The purpose of `:features:` and `:language:` is the same as that in `units` target.

I wonder I can borrow some ideas from here:
https://www.sphinx-doc.org/ja/master/usage/extensions/doctest.html

**Pull request merged**
