### PR TITLE
cxx: Fix EOF handling in tokenizer

### LINKED ISSUE #1111: Segmentation fault on large projects
When trying to run `ctags -R` on large projects it segfaults.

I have run a valgrind check:
~~~
==15076== Memcheck, a memory error detector
==15076== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==15076== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==15076== Command: /usr/local/bin/ctags -R
==15076== 
==15076== Warning: set address range perms: large range [0x16439028, 0x26439058) (noaccess)
==15076== Warning: set address range perms: large range [0x7aef0040, 0x9aef0040) (undefined)
==15076== Warning: set address range perms: large range [0x3aeef028, 0x5aeef058) (noaccess)
==15076== Invalid write of size 1
==15076==    at 0x42AEA2: cxxParserParseNextToken (cxx_parser_tokenizer.c:1231)
==15076==    by 0x4285E4: cxxParserParseBlock (cxx_parser_block.c:164)
==15076==    by 0x427D43: cxxParserMain (cxx_parser.c:1304)
==15076==    by 0x4142D1: createTagsWithFallback1 (parse.c:2124)
==15076==    by 0x415A76: parseFile (parse.c:2206)
==15076==    by 0x40C6C6: createTagsForEntry (main.c:259)
==15076==    by 0x40C64C: recurseIntoDirectory (main.c:145)
==15076==    by 0x40C71F: createTagsForEntry (main.c:255)
==15076==    by 0x40C64C: recurseIntoDirectory (main.c:145)
==15076==    by 0x40C71F: createTagsForEntry (main.c:255)
==15076==    by 0x40C64C: recurseIntoDirectory (main.c:145)
==15076==    by 0x40C71F: createTagsForEntry (main.c:255)
==15076==  Address 0x9aef0040 is 0 bytes after a block of size 1,073,741,824 alloc'd
==15076==    at 0x4A06C20: realloc (vg_replace_malloc.c:662)
==15076==    by 0x418ECA: eRealloc (routines.c:237)
==15076==    by 0x41A70C: vStringAutoResize (vstring.c:34)
==15076==    by 0x42AEB4: cxxParserParseNextToken (cxx_parser_tokenizer.c:1231)
==15076==    by 0x4285E4: cxxParserParseBlock (cxx_parser_block.c:164)
==15076==    by 0x427D43: cxxParserMain (cxx_parser.c:1304)
==15076==    by 0x4142D1: createTagsWithFallback1 (parse.c:2124)
==15076==    by 0x415A76: parseFile (parse.c:2206)
==15076==    by 0x40C6C6: createTagsForEntry (main.c:259)
==15076==    by 0x40C64C: recurseIntoDirectory (main.c:145)
==15076==    by 0x40C71F: createTagsForEntry (main.c:255)
==15076==    by 0x40C64C: recurseIntoDirectory (main.c:145)
==15076== 
==15076== Invalid write of size 1
==15076==    at 0x42AB21: cxxParserParseNextToken (cxx_parser_tokenizer.c:1231)
==15076==    by 0x4285E4: cxxParserParseBlock (cxx_parser_block.c:164)
==15076==    by 0x427D43: cxxParserMain (cxx_parser.c:1304)
==15076==    by 0x4142D1: createTagsWithFallback1 (parse.c:2124)
==15076==    by 0x415A76: parseFile (parse.c:2206)
==15076==    by 0x40C6C6: createTagsForEntry (main.c:259)
==15076==    by 0x40C64C: recurseIntoDirectory (main.c:145)
==15076==    by 0x40C71F: createTagsForEntry (main.c:255)
==15076==    by 0x40C64C: recurseIntoDirectory (main.c:145)
==15076==    by 0x40C71F: createTagsForEntry (main.c:255)
==15076==    by 0x40C64C: recurseIntoDirectory (main.c:145)
==15076==    by 0x40C71F: createTagsForEntry (main.c:255)
==15076==  Address 0x9aef0040 is 0 bytes after a block of size 1,073,741,824 alloc'd
==15076==    at 0x4A06C20: realloc (vg_replace_malloc.c:662)
==15076==    by 0x418ECA: eRealloc (routines.c:237)
==15076==    by 0x41A70C: vStringAutoResize (vstring.c:34)
==15076==    by 0x42AEB4: cxxParserParseNextToken (cxx_parser_tokenizer.c:1231)
==15076==    by 0x4285E4: cxxParserParseBlock (cxx_parser_block.c:164)
==15076==    by 0x427D43: cxxParserMain (cxx_parser.c:1304)
==15076==    by 0x4142D1: createTagsWithFallback1 (parse.c:2124)
==15076==    by 0x415A76: parseFile (parse.c:2206)
==15076==    by 0x40C6C6: createTagsForEntry (main.c:259)
==15076==    by 0x40C64C: recurseIntoDirectory (main.c:145)
==15076==    by 0x40C71F: createTagsForEntry (main.c:255)
==15076==    by 0x40C64C: recurseIntoDirectory (main.c:145)
==15076== 
==15076== 
==15076== Process terminating with default action of signal 11 (SIGSEGV)
==15076==  Access not within mapped region at address 0x9AEF1000
==15076==    at 0x42AEA2: cxxParserParseNextToken (cxx_parser_tokenizer.c:1231)
==15076==    by 0x4285E4: cxxParserParseBlock (cxx_parser_block.c:164)
==15076==    by 0x427D43: cxxParserMain (cxx_parser.c:1304)
==15076==    by 0x4142D1: createTagsWithFallback1 (parse.c:2124)
==15076==    by 0x415A76: parseFile (parse.c:2206)
==15076==    by 0x40C6C6: createTagsForEntry (main.c:259)
==15076==    by 0x40C64C: recurseIntoDirectory (main.c:145)
==15076==    by 0x40C71F: createTagsForEntry (main.c:255)
==15076==    by 0x40C64C: recurseIntoDirectory (main.c:145)
==15076==    by 0x40C71F: createTagsForEntry (main.c:255)
==15076==    by 0x40C64C: recurseIntoDirectory (main.c:145)
==15076==    by 0x40C71F: createTagsForEntry (main.c:255)
==15076==  If you believe this happened as a result of a stack
==15076==  overflow in your program's main thread (unlikely but
==15076==  possible), you can try to increase the size of the
==15076==  main thread stack using the --main-stacksize= flag.
==15076==  The main thread stack size used in this run was 10485760.
==15076== 
==15076== HEAP SUMMARY:
==15076==     in use at exit: 1,075,238,803 bytes in 1,877 blocks
==15076==   total heap usage: 11,182 allocs, 9,305 frees, 2,189,763,576 bytes allocated
==15076== 
==15076== LEAK SUMMARY:
==15076==    definitely lost: 0 bytes in 0 blocks
==15076==    indirectly lost: 0 bytes in 0 blocks
==15076==      possibly lost: 0 bytes in 0 blocks
==15076==    still reachable: 1,075,238,803 bytes in 1,877 blocks
==15076==         suppressed: 0 bytes in 0 blocks
==15076== Reachable blocks (those to which a pointer was found) are not shown.
==15076== To see them, rerun with: --leak-check=full --show-reachable=yes
==15076== 
==15076== For counts of detected and suppressed errors, rerun with: -v
==15076== ERROR SUMMARY: 8065 errors from 2 contexts (suppressed: 6 from 6)
Segmentation fault (core dumped)
~~~

I am using CentOS 6.

### PR DESCRIPTION
**Pull request by techee**
Since EOF is typically defined as -1, we need to check the value of
g_cxx.iChar before indexing g_aCharTable.

Fixes #1111.

### CODE REVIEW

**Comment by techee** [comment]
@zegervdv Can you test?

**Comment by b4n** [comment]
Looks reasonable.  The Travis failures are odd though (esp. as some Lua test also fails with clang)

**Comment by techee** [comment]
> The Travis failures are odd though (esp. as some Lua test also fails with clang)

It's timeouts - I think the test machine was just busy.

**Comment by masatake** [comment]
For "timeout" rerun the testing.

**Comment by zegervdv** [comment]
The fix works, thanks!

**Pull request merged**
