### PR TITLE
buildsys,mvc: Support packcc

### PR DESCRIPTION
**Pull request by k-takata**
Support packcc on MSVC.

### CODE REVIEW

**Comment by k-takata** [comment]
Hmm, it seems that packcc causes runtime error when compiled by VC2013.
It works fine when compiled by VC2015.

**Comment by masatake** [comment]
Do you have VC2013 on your local PC?
Debugging only on Appveyor is really painful...

**Comment by k-takata** [comment]
I tested locally and I found that a null pointer access occurs inside fprintf. So, it might be a problem of VC2013.
I also found another problem. Packcc uses "z" flag to print size_t variables, but VC2013 doesn't support the "z" flag of printf. VC supports it from VC2015. So, it might be better to support packcc only from VC2015.

**Comment by k-takata** [comment]
Note that https://github.com/universal-ctags/packcc/pull/1 is needed for building with VC2015.

**Comment by masatake** [comment]
> So, it might be better to support packcc only from VC2015.

...I don't have any objection for this.

**Comment by k-takata** [comment]
Ah, defining `SIZE_T_FMT_CHAR` to `"I"` fixes the problem.

**Comment by k-takata** [comment]
Okay, now the build succeeded and the varlink tests passed:
https://ci.appveyor.com/project/universalctags/ctags/builds/26092806/job/2hjnwt7vi6tdd8k5#L3221

**Comment by masatake** [comment]
Excellent! Feel free to merge the change.

**Comment by k-takata** [comment]
I'm going to change some more.
* Remove an unused variable.
* Make mk_mvc.mak and mk_mingw.mak more similar. Some variables are defined differently. Make them the same.

**Comment by k-takata** [comment]
I also removed the boolean definitions and included stdbool.h like #2151.
It was needed for making some variable definitions the same between mk_mvc.mak and mk_mingw.mak.

**Comment by k-takata** [comment]
I will merge this in a few days if there's no objection.

**Pull request merged**
