### PR TITLE
JavaScript: extract arrow functions

### PR DESCRIPTION
**Pull request by masatake**
Extracting `id` in 
```
var id = (x) => {
  return x;
}
```

### CODE REVIEW

**Comment by masatake** [comment]
I found I should add a support "..." in "function (x, ...a) {" first.
This one should be done after adding the support for "...".

**Comment by masatake** [comment]
I will update this pull request after @jafl accepts #3434.

**Comment by masatake** [comment]
Rebased on #3434.

**Comment by masatake** [comment]
I will rebase this one on the latest master branch.

**Review by jafl — APPROVED** [review]

**Comment by masatake** [comment]
@jafl, thank you for reviewing.
I will merge this after rebasing.

**Pull request merged**
