### PR TITLE
Misc: Replace true/false with TRUE/FALSE

### PR DESCRIPTION
**Pull request by pragmaware**
Minor fixes.

### CODE REVIEW

**Comment by masatake** [comment]
LKGTM. Thanks.

**Comment by codebrainz** [comment]
Why use non-standard macros (with no namespace prefix) when `true` and `false` are part of the standard library? Seems like it would be better to do the opposite replacement across the whole code base.

**Comment by t-b** [comment]
What C standard support is required for compiling utags? If C99 than stdbool.h can always be used [1] and mybool.h can be ditched. 

[1]: https://en.wikibooks.org/wiki/C_Programming/C_Reference/stdbool.h

**Comment by masatake** [comment]
You are right. We can use stdbool.h.
I will merge this PR for consistency. Can I ask you to make a PR for 
using stdbool.h then?

**Comment by t-b** [comment]
@masatake I'll come up with a PR.

**Pull request merged**
