### PR TITLE
Markdown: rewrite in C (based on #3233)

### PR DESCRIPTION
**Pull request by masatake**
This pull request is based on #3233 proposed by @techee. @masatake made minor changes.

The rewritten parser does the same as the original regex-based parser, but it is more than 10 times faster!

```
[yamato@dev64]~/var/codebase% CTAGS_EXE=/home/yamato/var/ctags-github/ctags-Regex ./codebase ctags Markdown
version: 5e6ab4b6
features: +wildcards +regex +gnulib_regex +iconv +option-directory +xpath +json +interactive +sandbox +packcc +optscript +pcre2
log: results/5e6ab4b6,Markdown............,..........,time......,default...,2021-12-24-00:27:22.log
tagsoutput: /dev/null
cmdline: + /home/yamato/var/ctags-github/ctags-Regex --quiet --options=NONE --sort=no --options=profile.d/maps --totals=yes --languages=Markdown -o - -R code/markdown-corpus code/progit code/selinux-handbook
686 files, 322854 lines (24506 kB) scanned in 2.0 seconds (12462 kB/s)
19246 tags added to tag file

real	0m2.014s
user	0m1.967s
sys	0m0.035s
+ set +x
[yamato@dev64]~/var/codebase% CTAGS_EXE=/home/yamato/var/ctags-github/ctags-C ./codebase ctags Markdown
version: 258b9cbd
features: +wildcards +regex +gnulib_regex +iconv +option-directory +xpath +json +interactive +sandbox +packcc +optscript +pcre2
log: results/258b9cbd,Markdown............,..........,time......,default...,2021-12-24-00:27:34.log
tagsoutput: /dev/null
cmdline: + /home/yamato/var/ctags-github/ctags-C --quiet --options=NONE --sort=no --options=profile.d/maps --totals=yes --languages=Markdown -o - -R code/markdown-corpus code/progit code/selinux-handbook
686 files, 322854 lines (24506 kB) scanned in 0.1 seconds (164033 kB/s)
19112 tags added to tag file

real	0m0.190s
user	0m0.172s
sys	0m0.015s
+ set +x
```

### CODE REVIEW

**Comment by techee** [comment]
@masatake Thanks for taking care of this PR and benchmarking it. I'm actually surprised the regex parser was so fast - previously we used to get more like 100x difference in speed. Out of curiosity, is this using GNU regex or the pcre2 one?

**Comment by masatake** [comment]
The original parser uses GNU regex.
The original parser is not written as a  LINE-ORIENTED regex parser.
The original parser is written as a stateful multi-table regex parser.
So the number of matching may be fewer than you assumed.

**Comment by masatake** [comment]
I tried pcre2.

```
yamato@dev64]~/var/codebase% CTAGS_EXE=/home/yamato/var/ctags-github/ctags-pcre ./codebase ctags Markdown
version: 9bb75f09
features: +wildcards +regex +gnulib_regex +iconv +option-directory +xpath +json +interactive +sandbox +packcc +optscript +pcre2
log: results/9bb75f09,Markdown............,..........,time......,default...,2021-12-24-02:55:17.log
tagsoutput: /dev/null
cmdline: + /home/yamato/var/ctags-github/ctags-pcre --quiet --options=NONE --sort=no --options=profile.d/maps --totals=yes --languages=Markdown -o - -R code/markdown-corpus code/progit code/selinux-handbook
686 files, 322854 lines (24506 kB) scanned in 1.0 seconds (25474 kB/s)
19246 tags added to tag file

real	0m1.003s
user	0m0.976s
sys	0m0.021s
+ set +x
```

C * 10 = PCRE = GNU/2

**Comment by techee** [comment]
> The original parser is written as a stateful multi-table regex parser.

That will probably be it.

**Comment by masatake** [comment]
@techee, I found an incorrect assumption in your pull request.

See https://raw.githubusercontent.com/Maijin/awesome-asm/master/README.md
```markdown
Awesome Assembler [[wiki]](https://en.wikipedia.org/wiki/Assembly_language#Assembler)
----------
![](http://i.imgur.com/tr6tTZE.png)

A curated list of awesome Assembler :)

----------

Assembler List
----------
```

Unlike reStructuredText, in Markdown, it seems that a heading like "Assembler List" can be longer than the separator coming after the heading "----------".

Can I ask you to provide a fix?

**Comment by techee** [comment]
> Can I ask you to provide a fix?

Done, see #3236.

**Comment by techee** [comment]
>> The original parser is written as a stateful multi-table regex parser.

> That will probably be it.

Thinking about it more I actually think the reason is the nature of the regexes themselves for markdown - they check what's at the beginning of the line like `#`, `=`, `-` and if it's not present, they fail quickly. With the original html parser we had in Geany regexes were checking for certain html tags which could appear anywhere on the line and then the regex has to perform many more comparisons in the string.

**Comment by masatake** [comment]
See #3236.

**Pull request closed without merging**
