### PR TITLE
Enable coveralls

### LINKED ISSUE #384: Utilize coverall
I don't want to open more issues:-P But this is worth to be opened.

Does anyone have interest this area?
I wrote a small initial version and made a branch enable-gcov.
Feel free hacking it.

### PR DESCRIPTION
**Pull request by masatake**
Close #384.

### CODE REVIEW

**Comment by masatake** [comment]
For me, it is ready to be merged.

@k-takata, could you look at this?

**Comment by k-takata** [comment]
I will look into it tonight.
One comment, the service name is coverall**s**, I think.

**Comment by masatake** [comment]
@k-takata, thank you. I have to fix my commit log. I will do "git push --force" again.

**Comment by k-takata** [comment]
Seems good.
BTW I have a [commit](https://github.com/k-takata/ctags/commit/f2b971ff2ce4661f529fc1823705ad6f3e0a0209) to make Travis-CI faster. I will create a new PR after this PR is merged.

**Comment by masatake** [comment]
@k-takata, thank you for reviewing. I'm waiting the PR:-)

**Pull request merged**
