### PR TITLE
JavaScript: handle spread syntax

### PR DESCRIPTION
**Pull request by masatake**
Related to #3435.

---

    JavaScript: handle spread syntax
    
    With this change, the parser skip "..." and the subsequent expression.
    
    ref. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

### CODE REVIEW

**Comment by masatake** [comment]
I must add a reference to a page describing the spread operator.

**Comment by leleliu008** [comment]
@masatake our GitHub Actions BSD workflows alwasy fails these days. I have no idea how to fix it. The only way is waiting GitHub Actions Team's fix. Reference: https://github.com/actions/runner-images/issues/8730

**Comment by masatake** [comment]
@leleliu008 Thank you. Could you make a "temporarily disabling" pull request and merge it?

**Comment by leleliu008** [comment]
> @leleliu008 Thank you. Could you make a "temporarily disabling" pull request and merge it?

Done via https://github.com/universal-ctags/ctags/pull/3848

**Review by jafl — APPROVED** [review]

**Comment by masatake** [comment]
It seems that "spread operator" is a term in TypeScript.
After reading https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax, "spread syntax" is the term I should use here.

**Pull request merged**
