### PR TITLE
php: Skip class and trait use not to confuse typerefs

### PR DESCRIPTION
**Pull request by b4n**
Fixes #4007

@alquerci This contains a squashed version of your initial test.  Does this look good to you?

### CODE REVIEW

**Comment by masatake** [comment]
@b4n Could you use `.b` extension for the test case dir in [0ee4816](https://github.com/universal-ctags/ctags/pull/4009/commits/0ee481667d65f3838d0a80be20c4e81aaf7184a6) instead of `.d`?
See https://docs.ctags.io/en/latest/testing-parser.html#gathering-test-cases-for-known-bugs about `.b`.

Then, convert the extension to `.d` extension in [dad1538](https://github.com/universal-ctags/ctags/pull/4009/commits/dad15384a4dc6c25bf397ed0f517d3e87eb00468) that provides the fix.

**Review by alquerci — APPROVED** [review]
LGTM

**Comment by b4n** [comment]
@masatake yeah sure, done.

**Review by masatake — APPROVED** [review]

**Comment by masatake** [comment]
@b4n thank you.

**Pull request merged**
