### PR TITLE
Automake:  various updates

### PR DESCRIPTION
**Pull request by masatake**

### CODE REVIEW

**Comment by leleliu008** [comment]
`fgetpos` and `fsetpos` functions are introduced in Android API 24, but we compiled with Android API 21, that's why we received a error. I think applying following patch will do the trick.

```diff
diff --git a/.github/workflows/cross-compile-android-ndk-on-mac.yml b/.github/workflows/cross-compile-android-ndk-on-mac.yml
index 11cc6651..337d04ff 100644
--- a/.github/workflows/cross-compile-android-ndk-on-mac.yml
+++ b/.github/workflows/cross-compile-android-ndk-on-mac.yml
@@ -37,7 +37,7 @@ jobs:
           TOOLCHAIN_BIN_DIR=$TOOLCHAIN_BASE_DIR/bin
           SYSROOT=$TOOLCHAIN_BASE_DIR/sysroot
 
-          export CC=$TOOLCHAIN_BIN_DIR/armv7a-linux-androideabi21-clang
+          export CC=$TOOLCHAIN_BIN_DIR/armv7a-linux-androideabi24-clang
           export AR=$TOOLCHAIN_BIN_DIR/llvm-ar
           export RANLIB=$TOOLCHAIN_BIN_DIR/llvm-ranlib
 
diff --git a/.github/workflows/cross-compile-android-ndk-on-ubuntu.yml b/.github/workflows/cross-compile-android-ndk-on-ubuntu.yml
index 37e33fab..640b5238 100644
--- a/.github/workflows/cross-compile-android-ndk-on-ubuntu.yml
+++ b/.github/workflows/cross-compile-android-ndk-on-ubuntu.yml
@@ -38,7 +38,7 @@ jobs:
           TOOLCHAIN_BIN_DIR=$TOOLCHAIN_BASE_DIR/bin
           SYSROOT=$TOOLCHAIN_BASE_DIR/sysroot
 
-          export CC=$TOOLCHAIN_BIN_DIR/armv7a-linux-androideabi21-clang
+          export CC=$TOOLCHAIN_BIN_DIR/armv7a-linux-androideabi24-clang
           export AR=$TOOLCHAIN_BIN_DIR/llvm-ar
           export RANLIB=$TOOLCHAIN_BIN_DIR/llvm-ranlib
```

**Comment by masatake** [comment]
@leleliu008 Thank you. I'll wait for you meriging #3829.

**Comment by leleliu008** [comment]
@masatake  Merged. You could rebase it now.

**Comment by masatake** [comment]
@leleliu008 thank you!

**Pull request merged**
