### PR TITLE
Add a `dist` make target to create a tarball

### PR DESCRIPTION
**Pull request by b4n**
One possible approach for easily creating a tarball.  It creates tarballs of the Git contents and names it after the current git tag or revision.
See #182.

### CODE REVIEW

**Comment by masatake** [comment]
I tried and found that configure is not included in  the tar.gz file generated from dist target.
We may have to write our own version based on maintainer.mak and @b4n's patch.

**Comment by b4n** [comment]
> I tried and found that configure is not included in the tar.gz file generated from dist target.

Indeed, because it's a generated file (not tracked in the repository).

If we want a tarball that doesn't require autoconf & friends to be used (e.g. to distribute *configure* and all the extra files like *missing*, *mkinstalldirs*, *install-sh*, *depcomp* and whatnot) we probably should use the Autotools facility for that.  However, I'm not sure if it's possible without using Automake -- and apparently it's hard to use Automake to build a software named `ctags` because it has builtin support for generating CTags files and the likes which conflict with it.

However, how relevant is it to distribute the various files generated by autoconf & friends out of *configure.ac*?  The advantage is allows someone to use the tarball without having autoconf, but how actually do that?  Linux distributions for one thing don't generally care, and often re-generate those files anyway (e.g. Debian always (?) does with *dh-autoreconf*).  So yeah, one less dependency is nice, but do someone caring to build from sources really care about the autoconf dependency?

**Comment by nenadalm** [comment]
according to the help: https://github.com/fishman/ctags/blob/cfffbcf2c574fa391672a7dc5443d76735e049c3/maintainer.mak#L208

I've tried to merge this into my fork and then I run:
```shell
$ autoreconf
$ ./configure
$ make
$ make dist
$ cp ctags-da56977.tar.gz /tmp/ctags/
$ cd /tmp/ctags
$ tar -xf ctags-da56977.tar.gz
$ cd ctags-da56977
$ make -f maintainer.mak release-rpm-2.5
```

and it told me:
```
make: *** No rule to make target `release-rpm-2.5'.  Stop.
```

(the same when I try to run the last command from the repository folder)

it's probably not related with this PR - wasn't sure where sure I put it

**Comment by b4n** [comment]
@nenadalm the tarball generated by that PR doesn't include the configure script and Makefiles, you need to generate them like you do from the Git repository (`autoreconf -vfi && ./configure`).

**Comment by nenadalm** [comment]
inside of the extracted tarball
```
$ autoreconf -vfi
$ ./configure
$ make -f maintainer.mak release-rpm-2.5
```
the last command ends with the error agan:
```
make: *** No rule to make target `release-rpm-2.5'.  Stop.
```

**Comment by nenadalm** [comment]
maybe I need different version of make in case it works for others?

```shell
$ make -v
GNU Make 3.82
Built for x86_64-redhat-linux-gnu
Copyright (C) 2010  Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by b4n** [comment]
Doesn't work on the Git repository either.  I have no idea why nor how it's supposed to work, but it's not the tarball's fault.

**Comment by nenadalm** [comment]
ok, so I'll move it to another issue. thanks

**Comment by masatake** [comment]
We should not make a release till #182 is solved.

**Comment by steveno** [comment]
For the record, #182 was closed.

**Comment by mike-burns** [comment]
I added `dist` in #676, among other targets.

**Comment by masatake** [comment]
The situation is much changed; automake is introduced.
We have reliable `make dist` now. So I would like to close this.
 @mike-burns gets the kudos for it.

There is still a critical issue. Where we should define the version number: main/ctags.h, configure.ac or/and our git repository with "git tag".

**Pull request closed without merging**
