### PR TITLE
Address the build process with macports on macOS

### PR DESCRIPTION
**Pull request by lightingghost**

### CODE REVIEW

**Comment by masatake** [comment]
@lightingghost, thank you very much.

@cweagans, can I ask you to review this?
This is related to #1606.

**Comment by cweagans** [comment]
These instructions will work, but they do not produce a universal-ctags binary built against the macports-installed iconv. If it were up to me, we wouldn't support macports _at all_ (Homebrew is where the majority of Mac users are moving these days), but if we're going to, then I guess this is an okay solution.

**Comment by b4n** [comment]
If the _libiconv versions are literal equivalents to the _iconv ones we expect, what about suggesting `CPPFLAGS=-D_iconv=_libiconv -D_iconv_open=_libiconv_open -D_iconv_close=_libiconv_close` instead?

**Comment by cweagans** [comment]
^ sounds like a better path forward. I would recommend changing the universal ctags port to do that automatically. Having macports not rename those symbols would be the ideal case, though.

**Comment by masatake** [comment]
See #1615.

**Comment by masatake** [comment]
@lightingghost, ping.

**Comment by lightingghost** [comment]
@masatake I am sorry I missed your previous comments. I have just tested your branch for fixing the problem, it works for me.

**Comment by masatake** [comment]
@lightingghost, thank you for testing. My branch is merged.

**Pull request closed without merging**
