### PR TITLE
CXX: Fix cpp branching in the namespace statement. 

### PR DESCRIPTION
**Pull request by pragmaware**
Fixes parsing of Qt's qnamespace.h and similar.

### CODE REVIEW

**Comment by pragmaware** [comment]
Had to do a few commits to make this work because of a broken unit test by the way.
Squash when merging.

**Comment by masatake** [comment]
What kind of bug do you fix?

**Comment by pragmaware** [comment]
qnamespace.h from Qt contains an ugly construct:

```
#ifdef SOMETHING
  namespace
#else
  class
#endif
  NAME
```

with this change only one #ifdef branch is chosen and parsing does not stop.
This is how cpp in general works, it was just broken in the namespace case.

**Comment by masatake** [comment]
Thank you for the explanation.
I would like you to add it to your commit log.

If the issue is reproduced only when "-o -" or "-f -" arguments, I'm afraid that the issue is related to 
https://github.com/universal-ctags/ctags/pull/2427/commits/75114a494862f0b6bd7d1181d542119e685c3bc1 in #2427.

**Comment by pragmaware** [comment]
I think it never worked properly in the namespace case. I've kind-of-noticed it a long time ago while doing work stuff but somehow never remembered to investigate it.

**Comment by pragmaware** [comment]
Done.

**Pull request merged**
