### PR TITLE
Units: add a test case about #930

### PR DESCRIPTION
**Pull request by masatake**
Signed-off-by: Masatake YAMATO <yamato@redhat.com>

### CODE REVIEW

**Comment by masatake** [comment]
Updated.

**Comment by masatake** [comment]
... Instead of making c++ parser accept c input, switching to C parser from C++ parser in upper layer may be better in clean design. The issue is performance. For switching fro C+ parser to C parser, the contests of .h file must be parsed for detecing the language of input (pre parse.)

**Comment by masatake** [comment]
Updated. bool is a keyword both in C and C++.

**Comment by codebrainz** [comment]
> bool is a keyword both in C and C++.

`bool` isn't a keyword in C, it's a standard library macro defined in `stdbool.h`, if it matters for your test.

**Comment by masatake** [comment]
@codebrainz, thank you. I will update the commits again.

**Pull request merged**
