### PR TITLE
Cxx: fix memory leak in field attaching

### LINKED ISSUE #2524: Cxx: memory leak in fcc4853e
```
$ git checkout fcc4853e; bash autogen.sh && ./configure && make -j 9 && make units UNITS=templates2 VG=1
...
Summary (see CMDLINE.tmp to reproduce without test harness)
------------------------------------------------------------
  #passed:                                0
  #FIXED:                                 0
  #FAILED (broken args.ctags?):           0
  #FAILED (unexpected-exit-status):       0
  #FAILED (unexpected-output):            0
  #TIMED-OUT (10s):                       0
  #skipped (features):                    0
  #skipped (languages):                   0
  #known-bugs:                            0
  #valgrind-error:                        1
	parser-cxx.r/templates2
$ cat  Units/parser-cxx.r/templates2.d/VALGRIND.tmp 
==11260== Memcheck, a memory error detector
==11260== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==11260== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==11260== Command: ./ctags --verbose --options=NONE --optlib-dir=+./Units/parser-cxx.r/templates2.d/optlib -o - --options=./Units/parser-cxx.r/templates2.d/args.ctags ./Units/parser-cxx.r/templates2.d/input.cpp
==11260== Parent PID: 11157
==11260== 
==11260== 
==11260== HEAP SUMMARY:
==11260==     in use at exit: 106 bytes in 2 blocks
==11260==   total heap usage: 5,459 allocs, 5,457 frees, 287,882 bytes allocated
==11260== 
==11260== 106 bytes in 2 blocks are definitely lost in loss record 1 of 1
==11260==    at 0x4C2EE3B: malloc (vg_replace_malloc.c:309)
==11260==    by 0x412635: eMalloc (routines.c:220)
==11260==    by 0x412851: eStrdup (routines.c:329)
==11260==    by 0x475918: attachParserField (entry.c:983)
==11260==    by 0x42F8DC: cxxTagSetField (cxx_tag.c:519)
==11260==    by 0x42F8DC: cxxTagHandleTemplateFields (cxx_tag.c:555)
==11260==    by 0x429CEC: cxxParserEmitFunctionTags (cxx_parser_function.c:1641)
==11260==    by 0x42AF24: cxxParserExtractFunctionSignatureBeforeOpeningBracket (cxx_parser_function.c:1780)
==11260==    by 0x42949E: cxxParserParseBlockHandleOpeningBracket (cxx_parser_block.c:148)
==11260==    by 0x428F68: cxxParserParseBlockInternal (cxx_parser_block.c:674)
==11260==    by 0x428F68: cxxParserParseBlock (cxx_parser_block.c:755)
==11260==    by 0x4274E2: cxxParserMain (cxx_parser.c:1842)
==11260==    by 0x40F515: createTagsForFile (parse.c:3337)
==11260==    by 0x40F515: createTagsWithFallback1 (parse.c:3463)
==11260==    by 0x40F766: createTagsWithFallback (parse.c:3549)
==11260==    by 0x40F766: parseMio (parse.c:3708)
==11260== 
==11260== LEAK SUMMARY:
==11260==    definitely lost: 106 bytes in 2 blocks
==11260==    indirectly lost: 0 bytes in 0 blocks
==11260==      possibly lost: 0 bytes in 0 blocks
==11260==    still reachable: 0 bytes in 0 blocks
==11260==         suppressed: 0 bytes in 0 blocks
==11260== 
==11260== For counts of detected and suppressed errors, rerun with: -v
==11260== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```

### PR DESCRIPTION
**Pull request by masatake**
Close #2524.

When attaching a field to a tag, the original code calls
attachParserField() wrong way. The caller must own the field value
passed to attachParserField(); the caller must free the memory
object for the value after calling makeTagEntry().
However, the original code didn't do so. As the result, the memory
object for the value was leaked.

This change introduces the parser trash box. After calling
attachParserField(), the caller puts the memory object to the trash
box; the memory object is freed when parsing the current input file is
completed.

### CODE REVIEW

**Comment by masatake** [comment]
@pragmaware, I made a minimal fix with the parser trash box. 
However, I'm not sure this is acceptable or not.
If we don't use the parser trash box, the change for fixing may large.

**Comment by masatake** [comment]
@pragmaware, I updated the comments for attachParserField in 99fdd16.

**Comment by pragmaware** [comment]
OK, so it's case B. Much clearer now.

**Comment by masatake** [comment]
Thank you for reviewing.

**Pull request merged**
