### PR TITLE
Remove non-posix make flag --no-print-directory from autogen.sh

### PR DESCRIPTION
**Pull request by mqudsi**
This fixes the remaining BSD build issues after the recent bmake fixes
were merged into master. Discussed in #1554. Closes #1554.

### CODE REVIEW

**Comment by mqudsi** [comment]
Just for reference, as seen in the GNU Make man page:

```
       -w, --print-directory
            Print a message containing the working directory before and after
            other processing.  This may be useful for tracking down errors
            from complicated nests of recursive make commands.

       --no-print-directory
            Turn off -w, even if it was turned on implicitly.
```

I'm not sure what implicitly turns on `-w`. Perhaps `-d` which prints debugging info (which isn't specified). We should be OK without `--no-print-directory`.

**Comment by masatake** [comment]
LGTM.

**Comment by codebrainz** [comment]
> I'm not sure what implicitly turns on -w.

It's explained somewhat in [the online docs](https://www.gnu.org/software/make/manual/html_node/Options-Summary.html) after the part you quoted:

> Print a message containing the working directory both before and after executing the makefile. This may be useful for tracking down errors from complicated nests of recursive make commands. See Recursive Use of make. __(In practice, you rarely need to specify this option since ‘make’ does it for you; see The [‘--print-directory’](https://www.gnu.org/software/make/manual/html_node/_002dw-Option.html#g_t_002dw-Option) Option.)__

So I guess because of the `-f` it's considered a submake, or maybe because of the specified make file including other make files. Either way, it's definitively the default behaviour I've observed in my own Make files.

**Comment by masatake** [comment]
Thank you.

**Pull request merged**
