### PR TITLE
Cobol: introduce a parser specific parameter named "format" to switch cobol dialects about source code (based on #2067) format

### PR DESCRIPTION
**Pull request by masatake**
@b4n, could you look at the last commit of this PR?

I introduced a parameter for switching a format in a Cobol parser.
I introduced a CobolFixed parser.  There are Cobol, CobolFixed, CobolFree, and CobolVariable parsers.

Cobol parser is for u-ctags users.
The rest parsers are for Geany.

./ctags --list-languages just prints Cobol only. The rest is invisible. u-ctags users can specify an input format with `--param-Cobol:format=fixed|free|variable` option.

You can run one of three directly with /ctags --language-force=CobolX where X is one of Fixed, Free, or Variable. This means Geany can specify one of the explicitly.

I don't write a test for my change yes.

If it looks acceptable, please, cherry-pick the last one.

### CODE REVIEW

**Comment by b4n** [comment]
Thinking about this a little more, I'm wondering if the argument is convenient at all for a library consumer… the thing is that it kind of affect *which* language is parsed, not really details of how like could be the `-D` for C.
So a library consumer would have to set the options *every single time* it calls the parser, in case another call changed the option: if the consumer want to parse e.g. fixed and free formats because the user has opened one file of each, then it has to set that parameter each time it switches from one to the other, or more simply each time it calls the parser.

It's not necessarily a problem, it's just an extra initialization that the caller ought to do in all cases, which to me sounds kind of like separate parsers.  From what I gathered grepping in the current code, the parser-specific arguments we have seem not quite similar to that.

What do you think?

**Comment by masatake** [comment]
Even with the changes that I proposed in #2076 (or without them), the parsers for each format are there.
I didn't remove any parser in  #2076.
So the client like Geany can choose a proper Cobol parser from 3 format specific parsers.


Next, I will write about the command line interface (CLI).
I have not inspected the details but in the current u-ctags, but there is no way to switch values for the parameter per input file. But let's forget it.
* https://github.com/universal-ctags/ctags/issues/1889
* https://github.com/universal-ctags/ctags/issues/1883
* https://github.com/universal-ctags/ctags/pull/1884


I think having a format-neutral COBOL parser is better. Here, the format-neutral means the format used in the parser can be switched with the "format" parser specific parameter.
It seems that the format used in a COBOL source file can be specified in the file.
See "1.3.16. Format of Program Source Lines" in https://open-cobol.sourceforge.io/HTML/gnucobpg.html

I think CobolFixed, CobolFree, and CobolVariale should not handle the format specification in the file.
e.g. Even if ">> FORMAT IS FIXED" is specified, CobolVariable parser should ignore it because "Variable" is specified by the user running ctags.

The format-neutral COBOL parser can handle the source line format specification.
That means I have to add one more parameter: ```--param-Cobol:inline-source-format=[yes]|no```.
The parameter allows the COBOL parser to override the format that a user-specified with --param-Cobol:format.

We can remove the format-neutral COBOL parser by adding the inline-source-format parameter to the format-specific parsers ( CobolFixed, CobolFree, and CobolVariale). Instead of introducing the inline-source-format parameter, statically allowing the format-specific parsers to switch the format by the source line format specification is technically possible, of course.

**Comment by b4n** [comment]
> I didn't remove any parser in #2076.
So the client like Geany can choose a proper Cobol parser from 3 format specific parsers.

I know they are still there for the moment, but I though I understood you planned on removing them once we had library API to set parameters.  And my comment was solely on this, whether the option made sense outside of the ctags CLI.  And my conclusion for the moment is that I'm not sure it makes much sense for a library, but I don't mind either.

> It seems that the format used in a COBOL source file can be specified in the file.
See "1.3.16. Format of Program Source Lines" in https://open-cobol.sourceforge.io/HTML/gnucobpg.html

Interesting, I didn't know that.

> I think CobolFixed, CobolFree, and CobolVariale should not handle the format specification in the file.

Whether a parser should not handle that if it was selected I don't know, it depends what a compiler would do.  I would myself expect the format lines to always be handled and have precedence over whatever is specified on the command line, and the command line acts just like a format line before the input.  But I'd have to check what's actually happening.
Depending on this, we should or should not have an extra option to ignore those.  Well, we could always have one, but it'd be a lot less useful.

**Comment by masatake** [comment]
> So a library consumer would have to set the options every single time it calls the parser, in case another call changed the option: if the consumer want to parse e.g. fixed and free formats because the user has opened one file of each, then it has to set that parameter each time it switches from one to the other, or more simply each time it calls the parser.

A user has to choose a parser from 3 or has to set a format from 3. A user has to do either anyway.

I don't like to provide 3 parsers for Cobol in user-visible way.
I think this is not abnormal idea.
GNU Cobol compiler provides `-fixed` option. It doesn't provide a separate command for compiling fixed formatted input.  https://open-cobol.sourceforge.io/HTML/gnucobpg.html#index-Fixed-Format-Mode
A cobol editing mode for GNU emacs has a parameter named cobol-source-format
(https://gist.github.com/Edward-H/6768e7dc53ea3dd2adca ).

Even if we remove three format specific parsers, I think there is no impact on Geany users.
Following figures show what I mean.

cobol

**Comment by masatake** [comment]
Rebased.

**Pull request closed without merging**
