### PR TITLE
Fix msys2 ExecutableName

### PR DESCRIPTION
**Pull request by k-takata**
When compiled with MSYS2, `ExecutableName` was not set properly.
There were two problems:

1. `MSDOS_STYLE_PATH` was not defined when using autotools on MSYS2.
2. File extension was not removed from `ExecutableName`.

Related: #494

### CODE REVIEW

**Comment by masatake** [comment]
I want the command line passed to a compiler short.
Instead of passing -D to the compiler utilizing config.h is better.

I think AC_DEFINE or AC_DEFINE_UNQUOTE will help us.

Following patch is not tested.

```
diff --git a/configure.ac b/configure.ac
index f6ebad5..ccd66cf 100644
--- a/configure.ac
+++ b/configure.ac
@@ -117,6 +117,8 @@ AH_TEMPLATE([NEED_PROTO_FTRUNCATE],
 	a prototype for, or a type mismatch using, the following function, define
 	this label and remake.])
 
+AH_TEMPLATE([EXEEXT],
+	[File extension for exectables.])
 
 
 # Report system info
@@ -396,6 +398,8 @@ AC_C_CONST
 AC_OBJEXT
 AC_EXEEXT
 
+AC_DEFINE(EXEEXT)
+
 AC_MSG_CHECKING(if struct stat contains st_ino)
 AC_TRY_COMPILE([#include <sys/stat.h>
 				#include <stdlib.h>], [
```

**Comment by k-takata** [comment]
> I think AC_DEFINE or AC_DEFINE_UNQUOTE will help us.

AC_DEFINE didn't work but AC_DEFINE_UNQUOTE worked. Thanks.

**Comment by masatake** [comment]
LGTM.

**Comment by vhda** [comment]
This is making my _spider sense_ tingle...
Shouldn't we update the Units scripts instead of changing the output of the ctags command?
I'm particularly concerned about the removal of the extension. I understand that it is very, **very** unlikely that we ever have both a `ctags.exe` and a `ctags.com` (or `.bat`) installed in the same system, but in Windows the executable name includes the extension and is essential to uniquely identify the program.
I will not oppose to this change, but I'd like to state my position nevertheless :)

**Comment by masatake** [comment]
@k-takata, does following patch helps you?

```
diff --git a/misc/units b/misc/units
index 4361820..775736a 100755
--- a/misc/units
+++ b/misc/units
@@ -1667,6 +1667,10 @@ tmain_run ()
 	r=$?
 	echo $r > ${subdir}/exit-actual.txt
 
+	sed -i -e 's|^ctags.exe|ctags|' ${subdir}/stderr-actual.txt
+	sed -i -e 's|^ctags.cmd|ctags|' ${subdir}/stderr-actual.txt
+	sed -i -e 's|^ctags.bat|ctags|' ${subdir}/stderr-actual.txt
+
 	if [ $r = $CODE_FOR_IGNORING_THIS_TMAIN_TEST ]; then
 	    run_result skip '/dev/null' "$(cat ${subdir}/stdout-actual.txt)"
 	    for a in ${subdir}/*-actual.txt; do

```

I don't want to touch "*-actual.txt" to avoid being confused.
We should introduce "*-filtered.txt" like units test harness does. But we can do it later.

**Comment by k-takata** [comment]
Updated.
I don't think we need to care about ".cmd", ".bat" or some other extensions, only ".exe" is enough.

**Comment by masatake** [comment]
Fine!

Let's go ahead.

**Pull request merged**
