### PR TITLE
Tmain: Fix `make distcheck`

### PR DESCRIPTION
**Pull request by k-takata**
`make distcheck` sets the source directories readonly. So, temporary files or output files should be written in $BUILDDIR. Otherwise, tests will fail with permission errors.

`make distcheck` is important when we create a release.

### CODE REVIEW

**Comment by k-takata** [comment]
Still this error is shown:

```
ERROR: files left in build directory after distclean:
./optlib/RSpec.c
./optlib/cmake.c
./optlib/ctags-optlib.c
./optlib/elixir.c
./optlib/elm.c
./optlib/gdbinit.c
./optlib/inko.c
./optlib/man.c
./optlib/markdown.c
./optlib/passwd.c
./optlib/pod.c
./optlib/puppetManifest.c
./optlib/qemuhx.c
./optlib/scss.c
./optlib/systemtap.c
./peg/varlink.c
./peg/varlink.h
Makefile:4888: recipe for target 'distcleancheck' failed
```

**Comment by k-takata** [comment]
I focus only on Tmain, units and tlib in this PR.
I will create another PR for the issue I wrote above that target 'distcleancheck' fails.

**Comment by masatake** [comment]
@k-takata, do you use misc/review?
If not, try it. I believe you like it.

It may help you in test case improvements.

If you got a failure in units or tmain, run the script.
You can inspect a test case and its result interactively.

**Comment by k-takata** [comment]
Oh, I haven't used it. I will try.

**Pull request merged**
