### PR TITLE
build: Arrange compiler and linker option specifings

### LINKED ISSUE #585: [Proposal] Arrange compiler/linker option specifings in Makefile.in
I propose arranging some compiler and linker option specifings in Makefile.in.

Target Makefile.in lines are:
```
SPARSEFLAGS=-Wsparse-all
COVERAGE_CFLAGS=--coverage
COVERAGE_LDFLAGS=--coverage
ALL_CFLAGS = $(CFLAGS) --std=gnu99 -Wall $(COVERAGE_CFLAGS)
```

* `-Wsparse-all`: would be specified via `AC_SUBST([CGCC_CFLAGS])` via  `AC_ARG_VAR([CGCC_CFLAGS])` ~~`AC_ARG_WITH([sparse-warning-flags])`~~ at configure.ac. and also, add `--with-sparse-cgcc` configure option.
* `--coverage` (CFLAGS): would be specified via `AC_SUBST([COVERAGE_CFLAGS])` via `AC_ARG_ENABLE([coverage-gcov])` ~~`AC_ARG_ENABLE([coverage])`~~ at configure.ac.
* `--coverage` (LDFLAGS): would be specified via `AC_SUBST([COVERAGE_LDFLAGS])` via `AC_ARG_ENABLE([coverage-gcov])` ~~`AC_ARG_ENABLE([coverage])`~~ at configure.ac.
* `--std=gnu99`: would be specified via `AC_SUBST([EXTRA_CFLAGS])` via `AC_ARG_VAR([EXTRA_CFLAGS])` at configure.ac.
* `-Wall` would be specified via `AC_SUBST([WARNING_CFLAGS])` via `AC_ARG_VAR([WARNING_CFLAGS])` at configure.ac.

### PR DESCRIPTION
**Pull request by p-montanus**
Arranging some compiler and linker option specifings in Makefile.in.
fix #585.

Target Makefile.in lines are:
```
SPARSEFLAGS=-Wsparse-all
COVERAGE_CFLAGS=--coverage
COVERAGE_LDFLAGS=--coverage
ALL_CFLAGS = $(CFLAGS) --std=gnu99 -Wall $(COVERAGE_CFLAGS)
```

Add configure options:
```
  --with-sparse-cgcc      use Sparse 'compiler wrapper' cgcc as C compiler [no]
  --enable-coverage-gcov  enable 'gcov' coverage testing tool [no]
```
    
Add configure arg-vars:
```
  CGCC_CFLAGS             cgcc specific flags [-Wsparse-all]
  EXTRA_CFLAGS            extra C compiler flags [-std=gnu99]
  WARNING_CFLAGS          C compiler warning flags [-Wall]
 ```

configure arg-vars can be specified like this:
```
$ ./configure EXTRA_CFLAGS='-std=c99' WARNING_CFLAGS='-Wall -Wextra'
```
or
```
$ EXTRA_CFLAGS='-std=c99' WARNING_CFLAGS='-Wall -Wextra' ./configure
```

### CODE REVIEW

**Comment by masatake** [comment]
@p-montanus, thank you.

I would like you to add/update help target of Makefile.in and/or docs/building.rst file.
Please, put some examples written here to these files.

**Comment by p-montanus** [comment]
One more commit added, to mention some configure options at docs/tips.rst.

**Comment by masatake** [comment]
Other than `PRETTY_ARG_VAR` explanation, LGTM.

**Comment by masatake** [comment]
A prefix agreed in our team is needed when one wants to (re)organize the codes. 
In the main part of C code, I have introduced kind_, flags_, and so on. I have long vision for changing the code and I strongly want to reorganize them.

About build-script, 
if you have a plan or vision, you can give a prefix as you need. building consensus is done in reviewing process.  We have good reviewers.

If you have a plan or vision, but you cannot find a good prefix/name, you can delay giving a prefix/name. In this case, PRETTY_ARG_VAR is enough. I asked adding a comment but I didn't ask changing the macro name. `AC_ARG_WIHT__WITH_DEFAULT` is just an idea. The name is helpful for me to understand the macro. However, if the explanation is given as comments, people including I can understand the intention of macro.

If you don't have a plan or vision, just use the original name: PRETTY_ARG_VAR.

**Comment by p-montanus** [comment]
@masatake, thank you for advising.

revised git comment, and added explanation for macro.

**Comment by masatake** [comment]
@p-montanus, thank you.

**Pull request merged**
