### PR TITLE
Fortran: support --fields=+S

### PR DESCRIPTION
**Pull request by QingmingHe**
Parse signature of Fortran subprogram and prototype. The signature of Fortran language has three forms:

1. No function arguments at all
```Fortran
   subroutine suba
   end subroutine
```
2. No function arguments but with parens
```Fortran
   subroutine suba()
   end subroutine
```
3. With function arguments
```Fortran
   subroutine suba(a, b)
     interger :: a, b
   end subroutine
```

In the first and second case, signature will set to NULL and will not write to tags file. In the last case, signature will be written with **--fields=+S** options.

### CODE REVIEW

**Comment by masatake** [comment]
> subroutine suba(a, b)
     interger :: a, b
   end subroutine

It seems that "(a, b)" is recorded as signature.

I got a question. Following code is valid in Fortran?
> subroutine suba(a, b)
     someThingOtherType :: a, b
   end subroutine

If, yes, I think users may want the type informations are also recorded like
> signature:(a, b)someThingOtherType :: a, b

**Comment by QingmingHe** [comment]
Code like this is normal and beautiful:
```Fortran
subroutine suba(a, b)
  someThingOtherType :: a, b
end subroutine
```
Its' easy to get the type information here. But Fortran compiler also recognize ugly code like this:
```Fortran
subroutine suba(a, b)
  real c
  real d
  integer :: a, e
  real(my_kind), allocatable, intent(in) :: b(:,:)
end subroutine
```
Type of **a** and **b** is declared after other local variables. It' a tricky for ctags to get the type information for that ctags report **suba**, **c**, **d**, **a**, **e**, **b** in a sequence (The local variables are also reported in Fortran parser). Ctags cannot get the type information of **a** before it parses **integer :: a, e**. But if ctags parse this statement just for obtaining signature, it will lose the information of **c** and **d**. Ctags can not parse backward as far as I know.

**Comment by masatake** [comment]
Did you know cork API?
With extending cork API, you can implement forward referencing.

Look at docs/internal.rst.

When you call makeTagEntry with "suba", you will get an index. Let's call the index I_suba.
After parsing integer :: a, e and real(my_kind), allocatable, intent(in) :: b(:,:), you can ready to
build perfect signature string. With the string you can update the signature slot of I_suba.

Currently the API is minimized. However, if you need you can extend it.

cork API will help you to delay the decision about what should be written to tags file.

If you don't think about such perfect solution now, let's think about forward compatibility.
If there is perfect code for generating signature string, how the output format is?
Try to make the current imperfect output subsets of the perfect output.

Do I make sense?

@b4n, could you give us input about this topic. I guess signature strings may be utilized in geany. 
From the tool side, what is a preferred solution?

**Comment by QingmingHe** [comment]
Let's summon @b4n again.
Say the source code is
```Fortran
subroutine suba(a, b)
  real c
  real d
  integer :: a, e
  real(my_kind), allocatable, intent(in) :: b(:,:)
end subroutine
```
I've two ideas to show the signature.
The first one is include type data along with argument variables:
```
signature:(interger :: a, real(my_kind), allocatable, intent(in) :: b(:,:))
```
Or show variables in the first parens and type information in the second:
```
signature:(a, b)(integer :: a, real(my_kind), allocatable, intent(in) :: b(:,:))
```
I vote for the second for that I tend to give argument variable a long_and_detailed name such as **material**, **geometry** rather than **a**, **b**. The data inside first parens is adequate. If I want to get more information, I'd like to jump to the definition directly as jump via etags is convenient in Emacs. I can hardly find the name of variable in the first case. For user who want to get variable names along with type information, he can refer to the second parens.
Besides, it's easy to make it an option to determine whether show data inside first or second parens via eldoc-mode of Emacs (I dont know other editors).

**Comment by masatake** [comment]
The second one is o.k.

> signature:(a, b)(integer :: a, real(my_kind), allocatable, intent(in) :: b(:,:))

(a, b) part is must and you already implemented it. Could you merge this change?
The rest is optional and you will implement it, won't you:-P

Don't forget escaping tabs in the rest part.

**Comment by b4n** [comment]
Sorry for the delay.

Well, signatures are typically used for 2 things by tools:
1. Calltips (hinting to the user, the most common usage)
2. Getting the list of parameter names, and possibly types.

For 1, IMO we need something that is natural for the language.  What most (all?) parers do is they just report whatever was used as the signature in the code -- typically everything inside the parentheses for non-K&R C-style things.

2 however is a hack, and requires extra understanding of the particular languages.  We could have a unified signature format, but that wouldn't be a really great solution here.  If we really want to support that, we probably should rather introduce a new "parameter" kind that works like local variables.

So IMO only the calltip usage is really important, and there it is directly targeted as the programmer, so it should IMO be as natural as possible for the language.  If Fortran uses `subroutine suba(a, b) integer :: a, b`, IMO the signature for subroutine `suba` should be `(a, b) integer :: a, b` -- or maybe `(a, b) integer:: a integer:: b`, but IMO it's better and simpler to just respect what was in the actual code.
But basically, use whatever feels the more natural for a Fortran programmer I guess.

**Comment by masatake** [comment]
@b4n, thank you very much.

My understanding is that the parenthesis  are not needed in the 2nd proposed format.

> signature:(a, b) integer :: a, real(my_kind), allocatable, intent(in) :: b(:,:)

@QingmingHe, could do as you think better based on the criteria given by @b4n.

**Comment by QingmingHe** [comment]
> My understanding is that the parenthesis are not needed in the 2nd proposed format.

It seems more natural to have parenthesis in the second. We can understand that the first is a succinct signature and the second is a detailed one.

**Comment by b4n** [comment]
Well, I don't know Fortran but I would tent to agree with @masatake given your code examples.  But again, it's not very important as it's basically just something human-readable.

**Comment by QingmingHe** [comment]
o.k. it's just a personal taste to have parenthesis. I will accept the second format. What I really cares is how to show function API via Emacs eldoc.

**Comment by QingmingHe** [comment]
Is the discussion applicable to other languages? Will other parser write signature like this:
```
(name1, name2) type of name1, type of name2
```

**Comment by b4n** [comment]
> Is the discussion applicable to other languages? Should other parser other than C parser write signature like this: […]

IMO no, they should write whatever is natural for the language, e.g. probably reproduce the language's own syntax there.

**Comment by QingmingHe** [comment]
But it will make it hard for outer tools to parse signature and do some useful things without unified format.

**Comment by QingmingHe** [comment]
Or at least, there should be some rules. Maybe classify into three kinds of language:
1. c-style.
```
(type name1, type name2)
```
2. type-free
```
(name1, name2)
```
3. some style I can't give it a name
```
(name1, name2) type of name1, type of name2
```

**Comment by b4n** [comment]
As I said earlier, while currently parsing the arguments might be needed for some features, it's IMO not the way to go.  If we want to support this, we should probably simply add an extra tag type (or field, but probably rather type) for arguments, that would work like variables: name and type.  This would be a lot more robust and easy than parsing an argument list, and wouldn't require "foreign" calltips.

Having unified calltips would probably be okay-ish for languages like C, C++, Java, JavaScript, PHP (but what about `$` in the identifiers?), maybe even Fortran, but probably not all languages.
Also, it becomes quite complex to parse with some types, e.g. in C `(void(*)(void(*)(int a, void *d) f, void* d) f, void *d, int a)` is perfectly valid, but very subtle to parse.

**Comment by b4n** [comment]
> Maybe classify into three kinds of language: […]

Types 1 and 3 seem to be identical in what they provide, so having both would go against uniformity.
If we *really* wanted a uniform format, I'd rather go for `([[type] arg1[, [type] arg2[, ...]]])` (e.g. C-style, with the type being optional), but once again IMO it's fragile and not the way to go if we want to let callers understand parameters.

**Comment by b4n** [comment]
(BTW type 3 is mostly K&R C)

**Comment by QingmingHe** [comment]
Type 3 is not k&r c. It's languages declaring types of arguments outside parenthesis like Fortran.

**Comment by b4n** [comment]
> Type 3 is not k&r c. It's languages declaring types of arguments outside parenthesis like Fortran.

Well, K&R style is this:
```C
int mul(a, b)
  int a;
  int b;
{
  return a*b;
}
```
Seems pretty similar to me :)

**Comment by QingmingHe** [comment]
BTW, no signature generated for K&R style functions (I just test the example you gives). Is it a bug?

**Comment by b4n** [comment]
> BTW, no signature generated for K&R style functions (I just test the example you gives). Is it a bug?

Indeed, and yeah it must be a bug.  The version of the C parser in Geany does handled those correctly (well, it only gives the part within the parentheses, but still)

**Comment by QingmingHe** [comment]
> The rest is optional and you will implement it, won't you:-P

o.k. In the first step I will replace Ancestors by cork API. They seem do the same thing.

**Pull request merged**
