### PR TITLE
docs(web): write about codebase

### PR DESCRIPTION
**Pull request by masatake**

### CODE REVIEW

**Comment by hirooih** [comment]
https://github.com/universal-ctags/codebase/README.rst is well documented.
The followings are my comments.

The followings are my understanding (or guess).  Should be described.

- A codebase must have a git repository.
- If CTAGS_EXE is not defined `ctags` is used.
- ALIGNMENT in `*.lcopy` is mandatory or optional (HEAD)?
  - there are pros and cons

typo:

```
$ ./codebae clone C
```

### How to add your code to code base

"How to add a new code base" may be better.

BTW Which is correct, "codebase" or "core base"?

### How to add your profile to preset list

It took some minutes for me to understand this section.
First I thought this was something mandatory.

"How to add a new profile" may be better as above.

> You have to write a .ctags file and put it to profile.d directory.

Words "have to" confused me.
How about the following?

> Add a `.ctags` file under `profile.d` directory.

> A line started from "# @" is used as a description for the profile.

Does this mean a "comment line"?

> You may wan to use --options-maybe to extend profile without modifying existing .ctags files.

I don't understand this sentence.

**Comment by masatake** [comment]
Based on your comment, I made an issue at the codebase repo.

**Review by hirooih — APPROVED** [review]
Sorry I've missed this request.

LGTM.

**Comment by masatake** [comment]
I got comments from you in the issue about README.md on `codebase` repo side. I didn't reflect the comment yet.
However, we can merge this change before updating the README.md of `codebase`.

**Pull request merged**
