### PR TITLE
Clojure: skip metadata in namespace definition

### LINKED ISSUE #1657: Clojure parser should handle metadata tags
In Clojure we have custom readers and one of them adds metadata to the symbol it preceeds.

I have a file like this one:

```clojure
(ns ^{:doc "Utility functions."} ep-cloud.util)

(defn debug? ^boolean
  []
  goog.DEBUG)
```

produces:

```
!_TAG_FILE_FORMAT	3	/extended format with meta character escaping/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	0.0.0	/70dd618/
^{:doc	src/ep_cloud/util.cljc	/^(ns ^{:doc "Utility functions."} ep-cloud.util)$/;"	n
debug?	src/ep_cloud/util.cljc	/^(defn debug? ^boolean$/;"	f	namespace:^{:doc
```

it should produce:

```
!_TAG_FILE_FORMAT	3	/extended format with meta character escaping/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	0.0.0	/70dd618/
ep-cloud.util	src/ep_cloud/util.cljc	/^(ns ^{:doc "Utility functions."} ep-cloud.util)$/;"	n
debug?	src/ep_cloud/util.cljc	/^(defn debug? ^boolean$/;"	f	namespace:ep-cloud.util
```

The command is `ctags filename.cljs`

The metadata `^` is on the namespace AND before `debug?` and it can be before any symbol for that matter, so it should always be skipped. 

According to the Clojure specification, the opening char is always `^` and the metadata section finishes at a the first space.

I also wanted to point to a very nice [test project](https://github.com/kawas44/test-tags-for-clojure/blob/master/gen_tags.sh) for trying things out.

Thanks for your work!

### PR DESCRIPTION
**Pull request by masatake**
Close #1657.

Signed-off-by: Masatake YAMATO <yamato@redhat.com>

### CODE REVIEW

**Comment by arichiardi** [comment]
Will try it tomorrow for sure! Thank you :smile:

**Comment by arichiardi** [comment]
@masatake tried it and it is good for me!

```
$ cat tags 
!_TAG_FILE_FORMAT	3	/extended format with meta character escaping/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	0.0.0	/9342384/
ep-cloud.util	src/ep_cloud/util.cljc	/^(ns ^{:doc "Utility functions."} ep-cloud.util$/;"	n
js->clj*	src/ep_cloud/util.cljc	/^   (defn js->clj*$/;"	f	namespace:ep-cloud.util
js-merge	src/ep_cloud/util.cljc	/^   (defn js-merge$/;"	f	namespace:ep-cloud.util
local-invocation?	src/ep_cloud/util.cljc	/^   (defn local-invocation?$/;"	f	namespace:ep-cloud.util
offline-invocation?	src/ep_cloud/util.cljc	/^   (defn offline-invocation?$/;"	f	namespace:ep-cloud.util
spec-valid-as-promise	src/ep_cloud/util.cljc	/^   (defn spec-valid-as-promise$/;"	f	namespace:ep-cloud.util
through	src/ep_cloud/util.cljc	/^   (defn through$/;"	f	namespace:ep-cloud.util
transform-keys	src/ep_cloud/util.cljc	/^(defn transform-keys$/;"	f	namespace:ep-cloud.util
trim-ex-data	src/ep_cloud/util.cljc	/^   (defn trim-ex-data$/;"	f	namespace:ep-cloud.util
```

**Comment by masatake** [comment]
@arichiardi, thank you.

**Comment by masatake** [comment]
```
$ cat tags 
!_TAG_FILE_FORMAT	3	/extended format with meta character escaping/
```

I found I mistakenly merged format-3 branch.

**Comment by arichiardi** [comment]
Oh, didn't noticed that, the output was good to me :smirk:

**Comment by masatake** [comment]
Please, ignore what I wrote in the last comment; it is nothing to do with the clojure parser.
...I wonder what I should do for the mistake....

**Comment by arichiardi** [comment]
Can you revert the commit and apply the fix on master the old `HEAD`?

**Comment by masatake** [comment]
@arichiardi, thank you.

**Pull request merged**
