### PR TITLE
Add  --_interactive mode (take3?)

### PR DESCRIPTION
**Pull request by masatake**
See #1071.

What I did:

1. refactor getFileLanguage
2. rename --interactive to --_interactive ( I would like to go more feed back about this new interface.)

@tmm1, could you look at this?

### CODE REVIEW

**Comment by tmm1** [comment]
👍 looks good to me!

**Comment by masatake** [comment]
... It seems that the output of dictionary is not stable. Should I use jq?

**Comment by tmm1** [comment]
Hmm, we are using "JSON_PRESERVE_ORDER" already..

I did not notice any failures on existing json output tests before.

Using jq seems ok.

**Comment by tmm1** [comment]
Maybe only error writer is missing PRESERVE_ORDER option?

**Comment by masatake** [comment]
Thank you!

**Comment by masatake** [comment]
BTW, which editor do you use? atom?

**Comment by masatake** [comment]
(I used your name in the last commit.)

**Comment by tmm1** [comment]
Yes, atom with vim-mode plugin.

**Comment by masatake** [comment]
The identation depth in your change is very different from the other code of u-ctags. So I will rearrange the indentation when merging your change.

**Comment by tmm1** [comment]
Ah, sorry about that.

**Comment by masatake** [comment]
Please, look at this http://docs.ctags.io/en/latest/contributions.html#c-language before submitting next interesting pull request:-)

**Comment by masatake** [comment]
All clear, now!

**Comment by tmm1** [comment]
Yay!

**Comment by tmm1** [comment]
So are you happy to merge this now?

**Comment by masatake** [comment]
I'll merge this in soon. 
I wonder what kind of application will we see.
I'm still working on json-output side. I wonder how to handle boolean.

**Comment by masatake** [comment]
O.k. I will merge this.
@tmm1, I'm sorry to take long time for merging this.  

I think there are still areas we can improve after getting feed-back from users.

**Comment by tmm1** [comment]
Thank you! I appreciate all you help in making this happen. I plan to use
this feature for a project and will let you know how it works out.

Aman

**Comment by masatake** [comment]
BTW. how do you think #1232?
Now we have json based i/o so, I think building a database can be done well outside ctags.

**Pull request merged**
