### PR TITLE
Tmain: add missing --options=NONE to run.sh for making the cases environment independent

### PR DESCRIPTION
**Pull request by masatake**
Signed-off-by: Masatake YAMATO <yamato@redhat.com>

### CODE REVIEW

**Comment by leleliu008** [comment]
the Circle CI fedora docker Image reports following error:
```
/usr/bin/autoconf: This script requires a shell more modern than all
/usr/bin/autoconf: the shells that I found on your system.
/usr/bin/autoconf: Please tell bug-autoconf@gnu.org about your system,
/usr/bin/autoconf: including any error possibly output before this
/usr/bin/autoconf: message. Then install a modern shell, or manually run
/usr/bin/autoconf: the script under such a shell if you do have one.
autoreconf: /usr/bin/autoconf failed with exit status: 1
+ echo 'failed in running autoreconf'
failed in running autoreconf
+ exit 1
```
The Virtual Environment information is following:
```
Build-agent version 1.0.59003-03ae64b6 (2021-04-30T13:46:41+0000)
System information:
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: xfs
 Cgroup Driver: cgroupfs
 Kernel Version: 4.15.0-1092-aws
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
```
It is built at `2021-04-30T13:46:41+0000`, we encountered this problem today, the time matches.

so I guess this problem is introduced by the new version of Virtual Environment. 

use `macOS` or `Windows` or try older version of Linux Virtual Environment may resolve this problem.

**Comment by masatake** [comment]
@leleliu008, yes. I guess it is something to do with the release of Fedora34.

I will make a pull request for switching the base of the environment from fedora:latest to fedora:34.

**Comment by leleliu008** [comment]
@masatake  

Sorry, I didn't make myself clear enough. 

I mean the reason is `Circle CI Virtual Environment` (Ubuntu 18.04.5 LTS Kernel Version: 4.15.0-1092-aws), it's Linux Kernel is customlized. 

`fedora:latest` and `fedora:34` are the same docker image. It it released 3 days ago. here is the information: [https://hub.docker.com/_/fedora?tab=tags&page=1&ordering=last_updated](https://hub.docker.com/_/fedora?tab=tags&page=1&ordering=last_updated)

I have tested `fedora:latest` docker image on my local `macOS` and `GitHub Actions macOS Virtual Environment`, they both worked  well. 

if `Circle CI Virtual Environment` has `macOS` or `Windows`, you can try to change it to these, or try older version of `Circle CI  Linux Virtual Environment` may resolve this problem.

By the way, is it necessary to change `Circle CI` to `GitHub Actions` ?

**Comment by masatake** [comment]
@leleliu008 , you may be correct.

I have just found https://bugzilla.redhat.com/show_bug.cgi?id=1900021 .

**Pull request merged**
