### PR TITLE
fix lang_set to avoid a latter core dump

### PR DESCRIPTION
**Pull request by cyyever**

### CODE REVIEW

**Comment by masatake** [comment]
Do you have any example reproducing the core dump?
I would like you to add as a test case.

**Comment by masatake** [comment]
The fix looks correct. I would like to know how you find the original bug.

**Comment by cyyever** [comment]
> Do you have any example reproducing the core dump?
> I would like you to add it as a test case.

I used it together with vim-gutentags to index a python file on FreeBSD, and it cored. I am not in the work environment now.

**Comment by masatake** [comment]
> I used it together with vim-gutentags to index a python file on FreeBSD, and it cored. I am not in the work environment now.

Thanks. Did you have a configuration file under ~/.ctags.d/ at that time?

**Comment by cyyever** [comment]
> 
> 
> > I used it together with vim-gutentags to index a python file on FreeBSD, and it cored. I am not in the work environment now.
> 
> Thanks. Did you have a configuration file under ~/.ctags.d/ at that time?

I don't have.
Execute the command under the source directory to reproduce this bug On FreeBSD.

> ctags -f tags.temp  --recurse=yes  

And the following is backtrace:


```
[New LWP 100092]
Core was generated by `ctags -f tags.temp --recurse=yes'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004094e6 in getLanguageNameFull (language=-1515870811, noPretending=false) at main/parse.c:266
#0  0x00000000004094e6 in getLanguageNameFull (language=-1515870811, noPretending=false) at main/parse.c:266
#1  0x000000000040aa2a in getLanguageNameFull (noPretending=false, language=<optimized out>) at main/parse.c:262
#2  getLanguageName (language=<optimized out>) at main/parse.c:281
#3  0x000000000047b489 in guestRequestSubmit (r=0x800eb1470) at main/lregex.c:2756
#4  0x000000000047ed5a in matchMultitableRegexTable (start=<optimized out>, start=<optimized out>, offset=<optimized out>, table=<optimized out>, 
    lcb=<optimized out>) at main/lregex.c:2484
#5  matchMultitableRegex (lcb=0x800f022c0, allLines=allLines@entry=0x800f61680) at main/lregex.c:2675
#6  0x000000000040ef41 in matchLanguageMultilineRegexCommon (language=language@entry=52, func=0x47e7c0 <matchMultitableRegex>, allLines=0x800f61680)
    at main/parse.c:3719
#7  0x000000000040efad in matchLanguageMultitableRegex (language=language@entry=52, allLines=<optimized out>) at main/parse.c:3738
#8  0x0000000000410f54 in iFileGetLine () at main/read.c:903
#9  0x0000000000411e6a in readLineFromInputFile () at main/read.c:995
#10 0x000000000047dc2d in fileReadLineDriver () at main/lregex.c:1870
#11 findRegexTagsMainloop (driver=<optimized out>) at main/lregex.c:1864
#12 findRegexTags () at main/lregex.c:1875
#13 0x000000000040f233 in createTagsForFile (passCount=1, language=52) at main/parse.c:3261
#14 createTagsWithFallback1 (language=language@entry=52, exclusive_subparser=exclusive_subparser@entry=0x7fffffffe78c) at main/parse.c:3389
#15 0x000000000040f519 in createTagsWithFallback (mio=0x0, language=52, 
    fileName=0x800edb800 "cbuild/.internal/sources/neovim/.github/ISSUE_TEMPLATE/bug_report.md") at main/parse.c:3475
#16 parseMio (fileName=fileName@entry=0x800edb800 "cbuild/.internal/sources/neovim/.github/ISSUE_TEMPLATE/bug_report.md", language=language@entry=52, 
    mio=0x0, useSourceFileTagPath=useSourceFileTagPath@entry=true, clientData=clientData@entry=0x0) at main/parse.c:3634
#17 0x000000000040f647 in parseFileWithMio (fileName=fileName@entry=0x800edb800 "cbuild/.internal/sources/neovim/.github/ISSUE_TEMPLATE/bug_report.md", 
    mio=mio@entry=0x0, clientData=clientData@entry=0x0) at main/parse.c:3680
#18 0x000000000040f739 in parseFile (fileName=fileName@entry=0x800edb800 "cbuild/.internal/sources/neovim/.github/ISSUE_TEMPLATE/bug_report.md")
    at main/parse.c:3618
#19 0x0000000000403178 in createTagsForEntry (entryName=entryName@entry=0x800edb800 "cbuild/.internal/sources/neovim/.github/ISSUE_TEMPLATE/bug_report.md")
    at main/main.c:219
#20 0x000000000040304c in recurseUsingOpendir (dirName=0x800f22e40 "cbuild/.internal/sources/neovim/.github/ISSUE_TEMPLATE") at main/main.c:114
#21 recurseIntoDirectory (dirName=dirName@entry=0x800f22e40 "cbuild/.internal/sources/neovim/.github/ISSUE_TEMPLATE") at main/main.c:184
#22 0x00000000004031a0 in createTagsForEntry (entryName=entryName@entry=0x800f22e40 "cbuild/.internal/sources/neovim/.github/ISSUE_TEMPLATE")
    at main/main.c:215
#23 0x000000000040304c in recurseUsingOpendir (dirName=0x800f22f00 "cbuild/.internal/sources/neovim/.github") at main/main.c:114
#24 recurseIntoDirectory (dirName=dirName@entry=0x800f22f00 "cbuild/.internal/sources/neovim/.github") at main/main.c:184
#25 0x00000000004031a0 in createTagsForEntry (entryName=entryName@entry=0x800f22f00 "cbuild/.internal/sources/neovim/.github") at main/main.c:215
#26 0x000000000040304c in recurseUsingOpendir (dirName=0x800f22b80 "cbuild/.internal/sources/neovim") at main/main.c:114
#27 recurseIntoDirectory (dirName=dirName@entry=0x800f22b80 "cbuild/.internal/sources/neovim") at main/main.c:184
#28 0x00000000004031a0 in createTagsForEntry (entryName=entryName@entry=0x800f22b80 "cbuild/.internal/sources/neovim") at main/main.c:215
#29 0x000000000040304c in recurseUsingOpendir (dirName=0x800f61800 "cbuild/.internal/sources") at main/main.c:114
#30 recurseIntoDirectory (dirName=dirName@entry=0x800f61800 "cbuild/.internal/sources") at main/main.c:184
#31 0x00000000004031a0 in createTagsForEntry (entryName=entryName@entry=0x800f61800 "cbuild/.internal/sources") at main/main.c:215
#32 0x000000000040304c in recurseUsingOpendir (dirName=0x800f61740 "cbuild/.internal") at main/main.c:114
#33 recurseIntoDirectory (dirName=dirName@entry=0x800f61740 "cbuild/.internal") at main/main.c:184
#34 0x00000000004031a0 in createTagsForEntry (entryName=entryName@entry=0x800f61740 "cbuild/.internal") at main/main.c:215
#35 0x000000000040304c in recurseUsingOpendir (dirName=0x800f2c170 "cbuild") at main/main.c:114
#36 recurseIntoDirectory (dirName=dirName@entry=0x800f2c170 "cbuild") at main/main.c:184
#37 0x00000000004031a0 in createTagsForEntry (entryName=0x800f2c170 "cbuild") at main/main.c:215
#38 0x000000000040308f in recurseUsingOpendir (dirName=0x49ca49 ".") at main/main.c:114
#39 recurseIntoDirectory (dirName=dirName@entry=0x49ca49 ".") at main/main.c:184
#40 0x0000000000403363 in batchMakeTags (args=<optimized out>, user=<optimized out>) at main/main.c:371
#41 0x0000000000403642 in runMainLoop (args=0x800eb0000) at main/main.c:582
#42 ctags_cli_main (argc=<optimized out>, argv=<optimized out>) at main/main.c:582
#43 0x0000000000402cff in _start (ap=<optimized out>, cleanup=<optimized out>) at /usr/src/lib/csu/amd64/crt1.c:76
```

**Comment by masatake** [comment]
How about running with --verbose option like:
```
ctags --verbose -f tags.temp --recurse=yes
```

At the end of verbose output, we may see the name of the current input file like:
```
ignoring .uncrustify.cfg (unknown language/language disabled)
Get file language for config.h.in
	pattern: config.h.in
		#candidates: 0
		#candidates after sorting and filtering: 0
	pattern + template(.in): config.h
		#candidates: 2
			0: C++ (extension: "h")
			1: ObjectiveC (extension: "h")
		#candidates after sorting and filtering: 2
			0: C++ (extension: "h")
			1: ObjectiveC (extension: "h")
	selector: 0x49955d
		selection: C++
OPENING config.h.in as C++ language file [reused]
Get file language for ctags
	pattern: ctags
		#candidates: 0
		#candidates after sorting and filtering: 0
ignoring ctags (unknown language/language disabled)
```

In this output, config.h.in is the last input file.

**Comment by cyyever** [comment]
> 
> 
> How about running with --verbose option like:
> 
> ```
> ctags --verbose -f tags.temp --recurse=yes
> ```
> 
> At the end of verbose output, we may see the name of the current input file like:
> 
> ```
> ignoring .uncrustify.cfg (unknown language/language disabled)
> Get file language for config.h.in
> 	pattern: config.h.in
> 		#candidates: 0
> 		#candidates after sorting and filtering: 0
> 	pattern + template(.in): config.h
> 		#candidates: 2
> 			0: C++ (extension: "h")
> 			1: ObjectiveC (extension: "h")
> 		#candidates after sorting and filtering: 2
> 			0: C++ (extension: "h")
> 			1: ObjectiveC (extension: "h")
> 	selector: 0x49955d
> 		selection: C++
> OPENING config.h.in as C++ language file [reused]
> Get file language for ctags
> 	pattern: ctags
> 		#candidates: 0
> 		#candidates after sorting and filtering: 0
> ignoring ctags (unknown language/language disabled)
> ```
> 
> In this output, config.h.in is the last input file.

```
  Option: --recurse=yes
RECURSING into directory "."
Get file language for script.sh
	pattern: script.sh
		#candidates: 1
			0: Sh (extension: "sh")
		#candidates after sorting and filtering: 1
			0: Sh (extension: "sh")
OPENING script.sh as Sh language file [new]
Initialize parser: Sh
excluding ".git"
RECURSING into directory ".ctags.d"
Get file language for .ctags.d/exclusion.ctags
	pattern: exclusion.ctags
		#candidates: 1
			0: Ctags (extension: "ctags")
		#candidates after sorting and filtering: 1
			0: Ctags (extension: "ctags")
OPENING .ctags.d/exclusion.ctags as Ctags language file [new]
Initialize parser: Ctags
Get file language for .dir-locals.el
	pattern: .dir-locals.el
		#candidates: 1
			0: Lisp (extension: "el")
		#candidates after sorting and filtering: 1
			0: Lisp (extension: "el")
OPENING .dir-locals.el as Lisp language file [new]
Initialize parser: Lisp
Get file language for .editorconfig
	pattern: .editorconfig
		#candidates: 0
		#candidates after sorting and filtering: 0
ignoring .editorconfig (unknown language/language disabled)
Get file language for .gdbinit
	pattern: .gdbinit
		#candidates: 1
			0: Gdbinit (pattern: ".gdbinit")
		#candidates after sorting and filtering: 1
			0: Gdbinit (pattern: ".gdbinit")
OPENING .gdbinit as Gdbinit language file [new]
Initialize parser: Gdbinit
RECURSING into directory ".github"
Get file language for .github/ISSUE_TEMPLATE.md
	pattern: ISSUE_TEMPLATE.md
		#candidates: 1
			0: Markdown (extension: "md")
		#candidates after sorting and filtering: 1
			0: Markdown (extension: "md")
OPENING .github/ISSUE_TEMPLATE.md as Markdown language file [new]
Initialize parser: Markdown

input : "(" L1
match : '('            main[ 0] /^#/
match : '('            main[ 1] /^[ \t]*````*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^`\n]*[\n]/
match : '('            main[ 2] /^[ \t]*~~~~*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^~\n]*[\n]/
match : '('            main[ 3] /^([^\n]+)[\n]=+[\n]/
match : '('            main[ 4] /^([^\n]+)[\n]-+[\n]/
match : '('            main[ 5] /^[^\n]+[\n]/
result: matched 2 bytes
scope : 
action: NOP in {main}, stack: /

input : "Thank you for contacting us." L2
match : 'T'            main[ 0] /^#/
match : 'T'            main[ 1] /^[ \t]*````*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^`\n]*[\n]/
match : 'T'            main[ 2] /^[ \t]*~~~~*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^~\n]*[\n]/
match : 'T'            main[ 3] /^([^\n]+)[\n]=+[\n]/
match : 'T'            main[ 4] /^([^\n]+)[\n]-+[\n]/
match : 'T'            main[ 5] /^[^\n]+[\n]/
result: matched 29 bytes
scope : 
action: NOP in {main}, stack: /

input : "\n" L3
match :'\n'            main[ 0] / ^#/
match :'\n'            main[ 1] / ^[ \t]*````*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^`\n]*[\n]/
match :'\n'            main[ 2] / ^[ \t]*~~~~*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^~\n]*[\n]/
match :'\n'            main[ 3] / ^([^\n]+)[\n]=+[\n]/
match :'\n'            main[ 4] / ^([^\n]+)[\n]-+[\n]/
match :'\n'            main[ 5] / ^[^\n]+[\n]/
match :'\n'            main[ 6] / ^[\n]+/
result: matched 1 bytes
scope : 
action: NOP in {main}, stack: /

input : "If you are reporting an issue with the parsing output, please fill" L4
match : 'I'            main[ 0] /^#/
match : 'I'            main[ 1] /^[ \t]*````*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^`\n]*[\n]/
match : 'I'            main[ 2] /^[ \t]*~~~~*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^~\n]*[\n]/
match : 'I'            main[ 3] /^([^\n]+)[\n]=+[\n]/
match : 'I'            main[ 4] /^([^\n]+)[\n]-+[\n]/
match : 'I'            main[ 5] /^[^\n]+[\n]/
result: matched 67 bytes
scope : 
action: NOP in {main}, stack: /

input : "the following template.  As your custom CTags configuration can" L5
match : 't'            main[ 0] /^#/
match : 't'            main[ 1] /^[ \t]*````*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^`\n]*[\n]/
match : 't'            main[ 2] /^[ \t]*~~~~*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^~\n]*[\n]/
match : 't'            main[ 3] /^([^\n]+)[\n]=+[\n]/
match : 't'            main[ 4] /^([^\n]+)[\n]-+[\n]/
match : 't'            main[ 5] /^[^\n]+[\n]/
result: matched 64 bytes
scope : 
action: NOP in {main}, stack: /

input : "affect results, please always use `--options=NONE` as the first" L6
match : 'a'            main[ 0] /^#/
match : 'a'            main[ 1] /^[ \t]*````*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^`\n]*[\n]/
match : 'a'            main[ 2] /^[ \t]*~~~~*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^~\n]*[\n]/
match : 'a'            main[ 3] /^([^\n]+)[\n]=+[\n]/
match : 'a'            main[ 4] /^([^\n]+)[\n]-+[\n]/
match : 'a'            main[ 5] /^[^\n]+[\n]/
result: matched 64 bytes
scope : 
action: NOP in {main}, stack: /

input : "option when running `ctags`." L7
match : 'o'            main[ 0] /^#/
match : 'o'            main[ 1] /^[ \t]*````*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^`\n]*[\n]/
match : 'o'            main[ 2] /^[ \t]*~~~~*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^~\n]*[\n]/
match : 'o'            main[ 3] /^([^\n]+)[\n]=+[\n]/
match : 'o'            main[ 4] /^([^\n]+)[\n]-+[\n]/
match : 'o'            main[ 5] /^[^\n]+[\n]/
result: matched 29 bytes
scope : 
action: NOP in {main}, stack: /

input : "\n" L8
match :'\n'            main[ 0] / ^#/
match :'\n'            main[ 1] / ^[ \t]*````*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^`\n]*[\n]/
match :'\n'            main[ 2] / ^[ \t]*~~~~*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^~\n]*[\n]/
match :'\n'            main[ 3] / ^([^\n]+)[\n]=+[\n]/
match :'\n'            main[ 4] / ^([^\n]+)[\n]-+[\n]/
match :'\n'            main[ 5] / ^[^\n]+[\n]/
match :'\n'            main[ 6] / ^[\n]+/
result: matched 1 bytes
scope : 
action: NOP in {main}, stack: /

input : "Otherwise, delete the template and write your issue from scratch." L9
match : 'O'            main[ 0] /^#/
match : 'O'            main[ 1] /^[ \t]*````*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^`\n]*[\n]/
match : 'O'            main[ 2] /^[ \t]*~~~~*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^~\n]*[\n]/
match : 'O'            main[ 3] /^([^\n]+)[\n]=+[\n]/
match : 'O'            main[ 4] /^([^\n]+)[\n]-+[\n]/
match : 'O'            main[ 5] /^[^\n]+[\n]/
result: matched 66 bytes
scope : 
action: NOP in {main}, stack: /

input : "Examples may help developers understanding your issue better." L10
match : 'E'            main[ 0] /^#/
match : 'E'            main[ 1] /^[ \t]*````*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^`\n]*[\n]/
match : 'E'            main[ 2] /^[ \t]*~~~~*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^~\n]*[\n]/
match : 'E'            main[ 3] /^([^\n]+)[\n]=+[\n]/
match : 'E'            main[ 4] /^([^\n]+)[\n]-+[\n]/
match : 'E'            main[ 5] /^[^\n]+[\n]/
result: matched 62 bytes
scope : 
action: NOP in {main}, stack: /

input : "\n" L11
match :'\n'            main[ 0] / ^#/
match :'\n'            main[ 1] / ^[ \t]*````*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^`\n]*[\n]/
match :'\n'            main[ 2] / ^[ \t]*~~~~*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^~\n]*[\n]/
match :'\n'            main[ 3] / ^([^\n]+)[\n]=+[\n]/
match :'\n'            main[ 4] / ^([^\n]+)[\n]-+[\n]/
match :'\n'            main[ 5] / ^[^\n]+[\n]/
match :'\n'            main[ 6] / ^[\n]+/
result: matched 1 bytes
scope : 
action: NOP in {main}, stack: /

input : "Use GitHub web interface and markdown notation." L12
match : 'U'            main[ 0] /^#/
match : 'U'            main[ 1] /^[ \t]*````*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^`\n]*[\n]/
match : 'U'            main[ 2] /^[ \t]*~~~~*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^~\n]*[\n]/
match : 'U'            main[ 3] /^([^\n]+)[\n]=+[\n]/
match : 'U'            main[ 4] /^([^\n]+)[\n]-+[\n]/
match : 'U'            main[ 5] /^[^\n]+[\n]/
result: matched 48 bytes
scope : 
action: NOP in {main}, stack: /

input : "Using mail results broken text rendering that makes" L13
match : 'U'            main[ 0] /^#/
match : 'U'            main[ 1] /^[ \t]*````*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^`\n]*[\n]/
match : 'U'            main[ 2] /^[ \t]*~~~~*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^~\n]*[\n]/
match : 'U'            main[ 3] /^([^\n]+)[\n]=+[\n]/
match : 'U'            main[ 4] /^([^\n]+)[\n]-+[\n]/
match : 'U'            main[ 5] /^[^\n]+[\n]/
result: matched 52 bytes
scope : 
action: NOP in {main}, stack: /

input : "the developers go crazy." L14
match : 't'            main[ 0] /^#/
match : 't'            main[ 1] /^[ \t]*````*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^`\n]*[\n]/
match : 't'            main[ 2] /^[ \t]*~~~~*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^~\n]*[\n]/
match : 't'            main[ 3] /^([^\n]+)[\n]=+[\n]/
match : 't'            main[ 4] /^([^\n]+)[\n]-+[\n]/
match : 't'            main[ 5] /^[^\n]+[\n]/
result: matched 25 bytes
scope : 
action: NOP in {main}, stack: /

input : ")" L15
match : ')'            main[ 0] /^#/
match : ')'            main[ 1] /^[ \t]*````*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^`\n]*[\n]/
match : ')'            main[ 2] /^[ \t]*~~~~*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^~\n]*[\n]/
match : ')'            main[ 3] /^([^\n]+)[\n]=+[\n]/
match : ')'            main[ 4] /^([^\n]+)[\n]-+[\n]/
match : ')'            main[ 5] /^[^\n]+[\n]/
result: matched 2 bytes
scope : 
action: NOP in {main}, stack: /

input : "\n" L16
match :'\n'            main[ 0] / ^#/
match :'\n'            main[ 1] / ^[ \t]*````*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^`\n]*[\n]/
match :'\n'            main[ 2] / ^[ \t]*~~~~*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^~\n]*[\n]/
match :'\n'            main[ 3] / ^([^\n]+)[\n]=+[\n]/
match :'\n'            main[ 4] / ^([^\n]+)[\n]-+[\n]/
match :'\n'            main[ 5] / ^[^\n]+[\n]/
match :'\n'            main[ 6] / ^[\n]+/
result: matched 1 bytes
scope : 
action: NOP in {main}, stack: /

input : "*****" L17
match : '*'            main[ 0] /^#/
match : '*'            main[ 1] /^[ \t]*````*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^`\n]*[\n]/
match : '*'            main[ 2] /^[ \t]*~~~~*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^~\n]*[\n]/
match : '*'            main[ 3] /^([^\n]+)[\n]=+[\n]/
match : '*'            main[ 4] /^([^\n]+)[\n]-+[\n]/
match : '*'            main[ 5] /^[^\n]+[\n]/
result: matched 6 bytes
scope : 
action: NOP in {main}, stack: /

input : "\n" L18
match :'\n'            main[ 0] / ^#/
match :'\n'            main[ 1] / ^[ \t]*````*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^`\n]*[\n]/
match :'\n'            main[ 2] / ^[ \t]*~~~~*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^~\n]*[\n]/
match :'\n'            main[ 3] / ^([^\n]+)[\n]=+[\n]/
match :'\n'            main[ 4] / ^([^\n]+)[\n]-+[\n]/
match :'\n'            main[ 5] / ^[^\n]+[\n]/
match :'\n'            main[ 6] / ^[\n]+/
result: matched 1 bytes
scope : 
action: NOP in {main}, stack: /

input : "The name of the parser:" L19
match : 'T'            main[ 0] /^#/
match : 'T'            main[ 1] /^[ \t]*````*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^`\n]*[\n]/
match : 'T'            main[ 2] /^[ \t]*~~~~*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^~\n]*[\n]/
match : 'T'            main[ 3] /^([^\n]+)[\n]=+[\n]/
match : 'T'            main[ 4] /^([^\n]+)[\n]-+[\n]/
match : 'T'            main[ 5] /^[^\n]+[\n]/
result: matched 24 bytes
scope : 
action: NOP in {main}, stack: /

input : "\n" L20
match :'\n'            main[ 0] / ^#/
match :'\n'            main[ 1] / ^[ \t]*````*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^`\n]*[\n]/
match :'\n'            main[ 2] / ^[ \t]*~~~~*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^~\n]*[\n]/
match :'\n'            main[ 3] / ^([^\n]+)[\n]=+[\n]/
match :'\n'            main[ 4] / ^([^\n]+)[\n]-+[\n]/
match :'\n'            main[ 5] / ^[^\n]+[\n]/
match :'\n'            main[ 6] / ^[\n]+/
result: matched 2 bytes
scope : 
action: NOP in {main}, stack: /

input : "The command line you used to run ctags:" L22
match : 'T'            main[ 0] /^#/
match : 'T'            main[ 1] /^[ \t]*````*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^`\n]*[\n]/
match : 'T'            main[ 2] /^[ \t]*~~~~*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^~\n]*[\n]/
match : 'T'            main[ 3] /^([^\n]+)[\n]=+[\n]/
match : 'T'            main[ 4] /^([^\n]+)[\n]-+[\n]/
match : 'T'            main[ 5] /^[^\n]+[\n]/
result: matched 40 bytes
scope : 
action: NOP in {main}, stack: /

input : "\n" L23
match :'\n'            main[ 0] / ^#/
match :'\n'            main[ 1] / ^[ \t]*````*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^`\n]*[\n]/
match :'\n'            main[ 2] / ^[ \t]*~~~~*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^~\n]*[\n]/
match :'\n'            main[ 3] / ^([^\n]+)[\n]=+[\n]/
match :'\n'            main[ 4] / ^([^\n]+)[\n]-+[\n]/
match :'\n'            main[ 5] / ^[^\n]+[\n]/
match :'\n'            main[ 6] / ^[\n]+/
result: matched 1 bytes
scope : 
action: NOP in {main}, stack: /

input : "```" L24
match : '`'            main[ 0] /^#/
match : '`'            main[ 1] /^[ \t]*````*([a-zA-Z0-9][-#+a-zA-Z0-9]*)?[^`\n]*[\n]/
result: matched 4 bytes
scope : 
action: [enter] to {codeblockBacktick}, stack: /main

input : "$ ctags --options=NONE ..." L25
match : '$' codeblockBacktick[ 0] /^[ \t]*````*[ \t]*[\n]/
match : '$' codeblockBacktick[ 1] /^[^\n]+[\n]/
result: matched 27 bytes
scope : 
action: NOP in {codeblockBacktick}, stack: /main

input : "```" L26
match : '`' codeblockBacktick[ 0] /^[ \t]*````*[ \t]*[\n]/
result: matched 4 bytes
scope : 
```

**Comment by masatake** [comment]
Thank you.
I read your comment again. I found github/ISSUE_TEMPLATE/bug_report.md  triggers the issue.
I got https://raw.githubusercontent.com/neovim/neovim/master/.github/ISSUE_TEMPLATE/bug_report.md.
By running ctags under valgrind with the input file, valgrind reports 'Using uninitialised value'.

I will try to make a test case which extends your pull request.

Thank you again.

**Comment by masatake** [comment]
The core dump cannot be reproduced. So I cannot write a test case. I added more lines to the original commit log, and opened #2283.
I will close this after merging #2283.

**Comment by masatake** [comment]
Merged via #2283. Thank you.

**Pull request closed without merging**
