### PR TITLE
man: use --kinddef-<LANG> option in man optlib parser

### PR DESCRIPTION
**Pull request by masatake**

### CODE REVIEW

**Comment by k-takata** [comment]
Was the title of this PR correct?
The prefix is `man:`, but this PR changed `optlib/passwd.ctags`. It doesn't seem to related to man.

**Comment by masatake** [comment]
Ouch! You are correct. This is my mistake.

**Comment by k-takata** [comment]
What was the intended title then?

**Comment by masatake** [comment]
The title should be "passwd: use --kinddef-<LANG> option in passwd optlib parser ".

**Pull request merged**
