### PR TITLE
Add --maxdepth option for limiting the recursion depth

### PR DESCRIPTION
**Pull request by pragmaware**

### CODE REVIEW

**Comment by pragmaware** [comment]
Hum.. no clue about the coverage decrease. Is it something wrong with the code?

**Comment by masatake** [comment]
Good idea.

**Comment by pragmaware** [comment]
Hm.. don't really know how to test this. Should probably create directory hierarchies with files within it and check that the produced tags are correct, but that would require far more code/text than the implementation of the feature itself... not a good idea.

**Comment by masatake** [comment]
Thank you.

**Pull request closed without merging**
