### PR TITLE
Ruby: introduce mixin field

### PR DESCRIPTION
**Pull request by masatake**
See #2476.

@AmaiKinono, plesae look at 205052c. It is a test case showing how new code dealing with "include" mixin.

You may be interested in c4711e8 ..205052c.  
c4711e8 and 7af2181 are preparation for 0912d1e.

### CODE REVIEW

**Comment by masatake** [comment]
I thought nestingLevel was not needed because we have cork.
I find it is wrong. To manage information which is not suitable to attach to a tagEntryInfo, nestingLevel is still useful.

**Comment by masatake** [comment]
I didn't implement reference tags for X and Y because I'm not sure whether it is needed or not.

**Comment by AmaiKinono** [comment]
I think I've done the right changes, but now I don't know how to push it to this branch. Maybe you need to open some "push access" for me? Not sure if it can be done on a per branch basis.

**Comment by masatake** [comment]
> I think I've done the right changes, but now I don't know how to push it to this branch. Maybe you need to open some "push access" for me? Not sure if it can be done on a per branch basis.

> Edit: Oh I just got it. I can create a PR on your fork :D Is that the right way?
Merge state

I will merge this one first. Then you can open your pull request.

Before merging this, I would like to think about following case:
```
class A
  def hi
     include X
    p "Calling 'hi' in A."
  end
end
```

**Comment by AmaiKinono** [comment]
The code you given actually doesn't work on my side. A working code should look like:

- Use instance method:

``` ruby
class A
  def hi
    self.class.prepend X
    p "Calling 'hi' in A."
  end
end

# a = A.new
# a.hi
# => "Calling 'hi' in A."
# a.hi
# => "Calling 'hi' in X."
```

- Or use class method:

``` ruby
class A
  def self.hi
    self.include X
  end
end

# a = A.new
# a.hi
# => (undefined method error)
# A.hi
# a.hi
# => "Calling 'hi' in X."
```

I think we could not bother with this, because it can actually happen anywhere:

``` ruby
class A
end
a = A.new

# a.hi
# (undefined method error)
# A.prepend X
# a.hi
# => "Calling 'hi' in X."
```

**Comment by masatake** [comment]
@AmaiKinono , thank you for the explanation.

I found a pattern I would like to support:
```
module X
  def hi
    p "Calling 'hi' in X."
  end
end

class A
  def self.prep
    include X
  end
  def hi
    p "Calling 'hi' in A."
  end

end

a = A.new
A.prep
p A.ancestors
```

Recognizing include in the singleton method is not hard.

**Comment by masatake** [comment]
@AmaiKinono, give me an ack if you think it is ready to merge.
Tell me if you think the last commit should be removed.

**Comment by AmaiKinono** [comment]
Yes I think this is ready to merge.

About `include` in a singleton method: I can see this is useful. I like it. Currently I can't think about similar cases (as I said I am new to ruby), which might be better to add now. But maybe we could extend it in the future when these cases actually come up.

**Comment by masatake** [comment]
@AmaiKinono, thank you for reviewing.

Feel free to ask me questions about the changes here.

> About include in a singleton method: I can see this is useful. I like it. Currently I can't think about similar cases (as I said I am new to ruby), which might be better to add now. But maybe we could extend it in the future when these cases actually come up.

I agree with you.

**Pull request merged**
