### PR TITLE
AppVeyor: use Visual Studio 2019 image

### PR DESCRIPTION
**Pull request by leleliu008**

### CODE REVIEW

**Comment by leleliu008** [comment]
It's very intresting.

GitHub Actions use `Visual Studio 2019 Enterprise` has no warnnings.
AppVeyor use `Visual Studio 2019 Community` repots some warnnings. due to `/WX` option is used, these warrnings are treated as errors and abort the build process.

**Comment by leleliu008** [comment]
```
C:\projects\ctags\peg\peg_common.h(133): error C2220: the following warning is treated as an error
C:\projects\ctags\peg\peg_common.h(133): warning C4477: 'fprintf' : format string '%2lu' requires an argument of type 'unsigned long', but variadic argument 1 has type 'size_t'
C:\projects\ctags\peg\peg_common.h(133): note: consider using '%zu' in the format string
C:\projects\ctags\peg\peg_common.h(133): warning C4477: 'fprintf' : format string '%4lu' requires an argument of type 'unsigned long', but variadic argument 2 has type 'size_t'
C:\projects\ctags\peg\peg_common.h(133): note: consider using '%zu' in the format string
kotlin.c
C:\projects\ctags\peg\peg_common.h(133): error C2220: the following warning is treated as an error
C:\projects\ctags\peg\peg_common.h(133): warning C4477: 'fprintf' : format string '%2lu' requires an argument of type 'unsigned long', but variadic argument 1 has type 'size_t'
C:\projects\ctags\peg\peg_common.h(133): note: consider using '%zu' in the format string
C:\projects\ctags\peg\peg_common.h(133): warning C4477: 'fprintf' : format string '%4lu' requires an argument of type 'unsigned long', but variadic argument 2 has type 'size_t'
C:\projects\ctags\peg\peg_common.h(133): note: consider using '%zu' in the format string
thrift.c
C:\projects\ctags\peg\peg_common.h(133): error C2220: the following warning is treated as an error
C:\projects\ctags\peg\peg_common.h(133): warning C4477: 'fprintf' : format string '%2lu' requires an argument of type 'unsigned long', but variadic argument 1 has type 'size_t'
C:\projects\ctags\peg\peg_common.h(133): note: consider using '%zu' in the format string
C:\projects\ctags\peg\peg_common.h(133): warning C4477: 'fprintf' : format string '%4lu' requires an argument of type 'unsigned long', but variadic argument 2 has type 'size_t'
C:\projects\ctags\peg\peg_common.h(133): note: consider using '%zu' in the format string
elm.c
C:\projects\ctags\peg\peg_common.h(133): error C2220: the following warning is treated as an error
C:\projects\ctags\peg\peg_common.h(133): warning C4477: 'fprintf' : format string '%2lu' requires an argument of type 'unsigned long', but variadic argument 1 has type 'size_t'
C:\projects\ctags\peg\peg_common.h(133): note: consider using '%zu' in the format string
C:\projects\ctags\peg\peg_common.h(133): warning C4477: 'fprintf' : format string '%4lu' requires an argument of type 'unsigned long', but variadic argument 2 has type 'size_t'
C:\projects\ctags\peg\peg_common.h(133): note: consider using '%zu' in the format string
Generating Code...
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.EXE"' : return code '0x2'
```

the MSVC compiler tell us using `'%zu'` instead of `'%lu'`

**Review by masatake — APPROVED** [review]

**Comment by masatake** [comment]
I will merge this pull request because #3795 requires it.
@k-takata, your review, and comments are welcome even after merging.

**Comment by masatake** [comment]
@leleliu008 Can I ask you to update docs/windows.rst?
Just doing s/2013/2019/ is enough?

**Comment by k-takata** [comment]
LGTM.

**Comment by masatake** [comment]
@k-takata, thank you.

**Pull request merged**
