### PR TITLE
sh: Add support for extra Bash function identifiers

### PR DESCRIPTION
**Pull request by b4n**
Recognize all the crazy stuff Bash allows as function identifiers when
using the `function` keyword.

### CODE REVIEW

**Comment by b4n** [comment]
As is, the test case generates a lot of warnings because it includes low control characters:
```
ctags: Notice: Unexpected character (0 < *c && *c < 0x20) included in a tagEntryInfo: foobar
ctags: Notice: File: Units/parser-sh.r/function-identifiers-bash.d/input.bash, Line: 4, Lang: Sh, Kind: f
ctags: Notice: Escape the character
ctags: Notice: Unexpected character (0 < *c && *c < 0x20) included in a tagEntryInfo: foobar
ctags: Notice: File: Units/parser-sh.r/function-identifiers-bash.d/input.bash, Line: 7, Lang: Sh, Kind: f
ctags: Notice: Escape the character
ctags: Notice: Unexpected character (0 < *c && *c < 0x20) included in a tagEntryInfo: foobar
ctags: Notice: File: Units/parser-sh.r/function-identifiers-bash.d/input.bash, Line: 10, Lang: Sh, Kind: f
ctags: Notice: Escape the character
ctags: Notice: Unexpected character (0 < *c && *c < 0x20) included in a tagEntryInfo: foobar
ctags: Notice: File: Units/parser-sh.r/function-identifiers-bash.d/input.bash, Line: 13, Lang: Sh, Kind: f
ctags: Notice: Escape the character
ctags: Notice: Unexpected character (0 < *c && *c < 0x20) included in a tagEntryInfo: foobar
ctags: Notice: File: Units/parser-sh.r/function-identifiers-bash.d/input.bash, Line: 16, Lang: Sh, Kind: f
ctags: Notice: Escape the character
ctags: Notice: Unexpected character (0 < *c && *c < 0x20) included in a tagEntryInfo: foobar
ctags: Notice: File: Units/parser-sh.r/function-identifiers-bash.d/input.bash, Line: 19, Lang: Sh, Kind: f
ctags: Notice: Escape the character
ctags: Notice: Unexpected character (0 < *c && *c < 0x20) included in a tagEntryInfo: foobar
ctags: Notice: File: Units/parser-sh.r/function-identifiers-bash.d/input.bash, Line: 22, Lang: Sh, Kind: f
ctags: Notice: Escape the character
ctags: Notice: Unexpected character (0 < *c && *c < 0x20) included in a tagEntryInfo: foobar
ctags: Notice: File: Units/parser-sh.r/function-identifiers-bash.d/input.bash, Line: 34, Lang: Sh, Kind: f
ctags: Notice: Escape the character
ctags: Notice: Unexpected character (0 < *c && *c < 0x20) included in a tagEntryInfo: foobar
ctags: Notice: File: Units/parser-sh.r/function-identifiers-bash.d/input.bash, Line: 37, Lang: Sh, Kind: f
ctags: Notice: Escape the character
ctags: Notice: Unexpected character (0 < *c && *c < 0x20) included in a tagEntryInfo: foobar
ctags: Notice: File: Units/parser-sh.r/function-identifiers-bash.d/input.bash, Line: 44, Lang: Sh, Kind: f
ctags: Notice: Escape the character
ctags: Notice: Unexpected character (0 < *c && *c < 0x20) included in a tagEntryInfo: foobar
ctags: Notice: File: Units/parser-sh.r/function-identifiers-bash.d/input.bash, Line: 47, Lang: Sh, Kind: f
ctags: Notice: Escape the character
ctags: Notice: Unexpected character (0 < *c && *c < 0x20) included in a tagEntryInfo: foobar
ctags: Notice: File: Units/parser-sh.r/function-identifiers-bash.d/input.bash, Line: 50, Lang: Sh, Kind: f
ctags: Notice: Escape the character
ctags: Notice: Unexpected character (0 < *c && *c < 0x20) included in a tagEntryInfo: foobar
ctags: Notice: File: Units/parser-sh.r/function-identifiers-bash.d/input.bash, Line: 53, Lang: Sh, Kind: f
ctags: Notice: Escape the character
ctags: Notice: Unexpected character (0 < *c && *c < 0x20) included in a tagEntryInfo: foobar
ctags: Notice: File: Units/parser-sh.r/function-identifiers-bash.d/input.bash, Line: 56, Lang: Sh, Kind: f
ctags: Notice: Escape the character
ctags: Notice: Unexpected character (0 < *c && *c < 0x20) included in a tagEntryInfo: foobar
ctags: Notice: File: Units/parser-sh.r/function-identifiers-bash.d/input.bash, Line: 59, Lang: Sh, Kind: f
ctags: Notice: Escape the character
ctags: Notice: Unexpected character (0 < *c && *c < 0x20) included in a tagEntryInfo: foobar
ctags: Notice: File: Units/parser-sh.r/function-identifiers-bash.d/input.bash, Line: 62, Lang: Sh, Kind: f
ctags: Notice: Escape the character
ctags: Notice: Unexpected character (0 < *c && *c < 0x20) included in a tagEntryInfo: foobar
ctags: Notice: File: Units/parser-sh.r/function-identifiers-bash.d/input.bash, Line: 65, Lang: Sh, Kind: f
ctags: Notice: Escape the character
ctags: Notice: Unexpected character (0 < *c && *c < 0x20) included in a tagEntryInfo: foobar
ctags: Notice: File: Units/parser-sh.r/function-identifiers-bash.d/input.bash, Line: 68, Lang: Sh, Kind: f
ctags: Notice: Escape the character
ctags: Notice: Unexpected character (0 < *c && *c < 0x20) included in a tagEntryInfo: foobar
ctags: Notice: File: Units/parser-sh.r/function-identifiers-bash.d/input.bash, Line: 71, Lang: Sh, Kind: f
ctags: Notice: Escape the character
ctags: Notice: Unexpected character (0 < *c && *c < 0x20) included in a tagEntryInfo: foobar
ctags: Notice: File: Units/parser-sh.r/function-identifiers-bash.d/input.bash, Line: 74, Lang: Sh, Kind: f
ctags: Notice: Escape the character
ctags: Notice: Unexpected character (0 < *c && *c < 0x20) included in a tagEntryInfo: foobar
ctags: Notice: File: Units/parser-sh.r/function-identifiers-bash.d/input.bash, Line: 77, Lang: Sh, Kind: f
ctags: Notice: Escape the character
ctags: Notice: Unexpected character (0 < *c && *c < 0x20) included in a tagEntryInfo: foobar
ctags: Notice: File: Units/parser-sh.r/function-identifiers-bash.d/input.bash, Line: 80, Lang: Sh, Kind: f
ctags: Notice: Escape the character
ctags: Notice: Unexpected character (0 < *c && *c < 0x20) included in a tagEntryInfo: foobar
ctags: Notice: File: Units/parser-sh.r/function-identifiers-bash.d/input.bash, Line: 83, Lang: Sh, Kind: f
ctags: Notice: Escape the character
ctags: Notice: Unexpected character (0 < *c && *c < 0x20) included in a tagEntryInfo: foobar
ctags: Notice: File: Units/parser-sh.r/function-identifiers-bash.d/input.bash, Line: 86, Lang: Sh, Kind: f
ctags: Notice: Escape the character
ctags: Notice: Unexpected character (0 < *c && *c < 0x20) included in a tagEntryInfo: foobar
ctags: Notice: File: Units/parser-sh.r/function-identifiers-bash.d/input.bash, Line: 89, Lang: Sh, Kind: f
ctags: Notice: Escape the character
ctags: Notice: Unexpected character (0 < *c && *c < 0x20) included in a tagEntryInfo: foobar
ctags: Notice: File: Units/parser-sh.r/function-identifiers-bash.d/input.bash, Line: 92, Lang: Sh, Kind: f
ctags: Notice: Escape the character
ctags: Notice: Unexpected character (0 < *c && *c < 0x20) included in a tagEntryInfo: foobar
ctags: Notice: File: Units/parser-sh.r/function-identifiers-bash.d/input.bash, Line: 95, Lang: Sh, Kind: f
ctags: Notice: Escape the character
```

Should I disallow this, leave it out of the tests or do something so that parsers can output this without generating warnings?

**Comment by masatake** [comment]
@b4n, how about using `--quiet'?

**Comment by b4n** [comment]
@masatake could do to hide them, but that doesn't change the fact that these are "valid" but would abort CTags if run with `--fatal-warnings` -- e.g. abort on valid input.
IMO, we should either not output any warning, or reject those constructs (as they are *very* unlikely, although technically valid), not to have known potential for breakage.

**Comment by masatake** [comment]
@b4h, thank you for advising. Current the warning is printed via notice(). I will change it to verbose().

**Comment by konsolebox** [comment]
I find this good enough, even using pointers to map functions seems less friendly to optimization for me, and that it doesn't invalidate names purely made up of digits.

I think you could also just exclude the control characters to remove the warnings, as they probably would never be used. Currently, the only characters I find useful are `[[:alnum:]_!?:.]`.

**Pull request merged**
