### PR TITLE
main: Completely remove trashBox implementation

### PR DESCRIPTION
**Pull request by vhda**
Hopefully everything should be ok. For some reason Travis is not running OSX related tests in my personal repository, so I didn't test that.
@b4n you're great at finding mistakes, so could I kindly ask you for a review?
@masatake you're the FUZZ testing master, could I kindly ask you to make a new run focused on Fortran?

Thanks in advance for all your help.

### CODE REVIEW

**Comment by masatake** [comment]
Testing fortran.c will take long time.
How about splitting the PR into one for main and one for fortran?
I would like to look at one for main.c first.

**Comment by masatake** [comment]
I will add valgrind check to tmain for testing this patch set.

**Comment by vhda** [comment]
These patches are very closely related because they are all required to completely solve memory leakage issues. In particular, if setjmp use is not remove from Fortran memory leaks will still exist.

Is patch splitting really necessary?

**Comment by b4n** [comment]
(BTW, not that it matters, but ideally I'd have the commit removing trashbox at the very end, when nothing needs it anymore.  but well, not important to me)

**Comment by vhda** [comment]
I just need to review the possible infinite loop in more detail. Will try to do that still today.

I understand your point regarding the commit history, but that was not the way I implemented the changes. I started by removing the trashBox and then cleaning up incrementally with Valgrind's help.

I know I could rebase everything to have it look like I'm a perfect engineer that planned everything ahead :P Nevertheless, I still prefer to leave things as they are because it allows me to replicate the Valgrind results after trashBox removal if I ever need to justify or review any of these changes.

**Comment by vhda** [comment]
BTW, thanks a lot for your review @b4n. Invaluable, as ever! :)

**Comment by vhda** [comment]
Everything should be corrected now.

**Comment by masatake** [comment]
I wanted split the PR 2.

1. removing code from option.c of main
2.1 removing code from fortran.c
2.2 removing code from parse.c of main
2.3 removing trashbox code itself.

One reason is for making a test separately (as I wrote.)
Another reason is for bisecting. When you remove the trashbox itself first, ctags cannot be compiled.

A person took the similar mistake here:
https://groups.google.com/forum/#!topic/linux.kernel/dr2xBM36l7c
http://lists.openwall.net/netdev/2013/03/20/133
http://lists.openwall.net/netdev/2013/03/21/79

**Comment by vhda** [comment]
@masatake please check if this helps.
Should also make @b4n happier :)

**Comment by masatake** [comment]
@vhda , thank you. I will check 950f8ba first; and I will ask you to merge it first.

**Comment by masatake** [comment]
Could you merge 950f8ba first?
It passed "make units VG=1".

**Comment by masatake** [comment]
(In this week I'm a bit busy but I can run tests.)

**Comment by masatake** [comment]
For understanding git, I merge 950f8ba to master.
If this breaks your workflow, forgive me.
I will look at the rest of patches.

**Comment by vhda** [comment]
I've rebased the remaining commits on master.

**Comment by masatake** [comment]
$ make fuzz LANGUAGES=Fortran VG=1
is passed. However, noise found a memory leak.



noise-1.f
```
module t
  type, xtends(s) :: r
```

$ valgrind --leak-check=full ./ctags -o - noise-1.f 
```
valgrind --leak-check=full ./ctags -o - noise-1.f 
==19110== Memcheck, a memory error detector
==19110== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==19110== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==19110== Command: ./ctags -o - noise-1.f
==19110== 
t	noise-1.f	/^module t$/;"	m
==19110== 
==19110== HEAP SUMMARY:
==19110==     in use at exit: 240 bytes in 5 blocks
==19110==   total heap usage: 7,602 allocs, 7,597 frees, 650,389 bytes allocated
==19110== 
==19110== 136 (80 direct, 56 indirect) bytes in 1 blocks are definitely lost in loss record 5 of 5
==19110==    at 0x4A06C10: malloc (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==19110==    by 0x411E85: eMalloc (routines.c:226)
==19110==    by 0x42118A: newToken (fortran.c:457)
==19110==    by 0x42281D: parseQualifierSpecList (fortran.c:1419)
==19110==    by 0x423277: parseDerivedTypeDef (fortran.c:1913)
==19110==    by 0x423277: parseTypeSpec (fortran.c:1323)
==19110==    by 0x4232F7: parseTypeDeclarationStmt (fortran.c:1588)
==19110==    by 0x423650: parseDeclarationConstruct (fortran.c:2121)
==19110==    by 0x423650: parseSpecificationPart (fortran.c:2183)
==19110==    by 0x423C6E: parseModule (fortran.c:2272)
==19110==    by 0x423C6E: parseProgramUnit (fortran.c:2469)
==19110==    by 0x423C6E: findFortranTags (fortran.c:2497)
==19110==    by 0x40F135: createTagsForFile (parse.c:1692)
==19110==    by 0x41062E: createTagsWithFallback (parse.c:1734)
==19110==    by 0x41062E: parseFile (parse.c:1875)
==19110==    by 0x40962D: createTagsForEntry (main.c:241)
==19110==    by 0x402C2F: createTagsForArgs (main.c:286)
==19110==    by 0x402C2F: makeTags (main.c:432)
==19110==    by 0x402C2F: main (main.c:517)
==19110== 
==19110== LEAK SUMMARY:
==19110==    definitely lost: 80 bytes in 1 blocks
==19110==    indirectly lost: 56 bytes in 2 blocks
==19110==      possibly lost: 0 bytes in 0 blocks
==19110==    still reachable: 104 bytes in 2 blocks
==19110==         suppressed: 0 bytes in 0 blocks
==19110== Reachable blocks (those to which a pointer was found) are not shown.
==19110== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==19110== 
==19110== For counts of detected and suppressed errors, rerun with: -v
==19110== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```

**Comment by vhda** [comment]
Should have seen this before!
It should be corrected now, but I did not create a test case. Should I? Where should I place it and how should I name it?

**Comment by masatake** [comment]
You don't have to this to Units if you have a plan to fix it.
In some reason, for example you don't have time to fix it now, I want you to add the input triggers a bug to Units.

Thank you for fixing. I restart "make noise VG=1 SHRINK=1 LANGUAGES=Fortran".
It takes long time. Please wait for a while.

(This is the special case. Generally, I will not run the noise target with VG. It takes too long time.)

**Comment by masatake** [comment]
(noise target is still running.)

**Comment by vhda** [comment]
As long as it's not finding errors I'm happy ;)
@ffes could I ask you to compile this in windows? I had to modify some files related to that.

**Comment by masatake** [comment]
@ffes, I will merge this. If you find a trouble on Windows, please, reopen this or open new one.

**Comment by ffes** [comment]
Did test this morning, but didn't have time to mention it here yet. Everything works as expected.

Although #462 is "needed" to get a VS build (the unistd.h in lxcmd.c breaks the build), but that is unrelated to this item and about to be fixed.

**Comment by masatake** [comment]
@ffes, thank you.

**Comment by masatake** [comment]
@ffes, I'm afraid what you are talking about is related to https://github.com/universal-ctags/ctags/commit/b1c7d6c06f7a413fa20b23f39a026f18b6d10418

**Comment by ffes** [comment]
@masatake No, that one solves a warning, so +1 for that

It is this line:
https://github.com/universal-ctags/ctags/blob/master/main/lxcmd.c#L56

But #462 adds a define to solve it.

**Pull request merged**
