### PR TITLE
Test case for 807

### PR DESCRIPTION
**Pull request by masatake**
@focalintent, I wrote a test case.
Could you verify it?
https://github.com/universal-ctags/ctags/commit/8f71f3a87b327813f5db3e1b6096b9e80a7443bc

### CODE REVIEW

**Comment by masatake** [comment]
Sorry, I cannot image expected output for the input.
What is `12`?

**Comment by focalintent** [comment]
Gah, sorry - typo'd my test case when cleaning it up here (this is what I get for being up at 3am) - that should be:

```
template<int X> f12( c< 1<<X> & aVar) { };
```

(making sure that signatures of functions that have templated parameters that have shift operators in their template parameter lists are correct).

**Comment by focalintent** [comment]
The full output:

```
Xantico:u-ctags dgarcia$ cat /tmp/x.cpp 
template <int P> class c {};
c< 8 > bVar;
c< 1<<8 > aVar;

template<int X> func( c< 1<<X> & aVar) {
}

Xantico:u-ctags dgarcia$ !./
./ctags -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives /tmp/x.cpp
ctags: Warning: Unsupported parameter 'T' for "fields" option
bVar	/tmp/x.cpp	/^c< 8 > bVar;$/;"	kind:variable	line:2
aVar	/tmp/x.cpp	/^c< 1<<8 > aVar;$/;"	kind:variable	line:3
func	/tmp/x.cpp	/^template<int X> func( c< 1<<X> & aVar) {$/;"	kind:function	line:5	signature:( c< 1<<X> & aVar)
Xantico:u-ctags dgarcia$ 
```

(And now I know how to add test cases to the setup here - next time I put together a PR, i'll be sure to add tests as well)

**Comment by masatake** [comment]
> template<int X> f12( c< 1<<X> & aVar) { };
Oh, I see.
I will add this to the case.

> (And now I know how to add test cases to the setup here - next time I put together a PR, i'll be sure to add tests as well)

Thank you. I wrote documents: http://docs.ctags.io/en/latest/units.html#units .

**Pull request merged**
