### PR TITLE
WIP: Minimize entry.h visibility

### PR DESCRIPTION
**Pull request by JonathonReinhart**
*Not yet ready for merge*

I would like to eventually add different storage backends to ctags. First, `entry.h` needs cleaned up to allow for an appropriate level of abstraction.

I'm opening this low-level PR for a few reasons:
- So people can see what's being worked on
- So these improvements can be integrated even if I don't finish the whole project
- So I can take advantage of your CI setup :-)

### CODE REVIEW

**Comment by masatake** [comment]
Basically I support this PR.
I would like to hear more about the background of this PR.
 

Could you add `main: ` as prefix to the subject of commit if your change is mainly about files under `main/*` ?

Could you add `refactor: ` as prefix to the subject of commit if your change doesn't intent changing the runtime behaviour of ctags.

These are not required rules, but these help me to review your code.
The most of all commits, you will add `main, refactor: `.

If a commit introduces an incompatible change, add "INCOMPATIBLE" or something to the subject.

**Comment by masatake** [comment]
https://github.com/universal-ctags/ctags/blob/docs-for-sharing-parsers/docs/how-to-share-parsers.rst
I wonder you will be interested in this document or not.

**Comment by b4n** [comment]
> https://github.com/universal-ctags/ctags/blob/docs-for-sharing-parsers/docs/how-to-share-parsers.rst
> I wonder you will be interested in this document or not.

OT, sorry, but I don't really know where to start this now, I can redirect if you point me:  For Geany's generic kinds point, I was rather thinking about having mappings from (u-)CTags kinds to Geany's generic ones, instead of adding/altering the ones in the parsers.
However, maybe this mapping should rather be somewhere in (u-)CTags itself so it can be reused by other tools, not only Geany.
But anyway, I'd probably rather implement a translation of parser/generic kinds than adding new kinds builtin in each parser.  E.g. put the translation on an upper layer the parser really don't care about.

**Comment by JonathonReinhart** [comment]
>> I would like to eventually add different storage backends to ctags. 

> I would like to hear more about the background of this PR.

I want to try writing the tags to an SQLite database, so I can leverage SQL to query against a large set of tags.

I could write a utility to read a `tags` file and convert it to SQLite, but I figured it may be just as easy to cut out the middle-man, and have `ctags` insert the tags directly.

**Comment by masatake** [comment]
I can merge your commit incrementally.
The commits marked LGTM are ready to merge. Please, ask me merging them if you want.

**Comment by masatake** [comment]
> I want to try writing the tags to an SQLite database, so I can leverage SQL to query against a large set of tags.

Just a question. How larget your tags file?

> I could write a utility to read a tags file and convert it to SQLite, but I figured it may be just as easy to cut out the middle-man, and have ctags insert the tags directly.

I see.

https://github.com/universal-ctags/ctags/blob/master/docs/output-tag-stream.svg
I wonder how this figure changes.

**Comment by masatake** [comment]
@JonathonReinhart, how do you do?
Putting tags to sqlite db is quite interesting. I would like you to continue the challenge.
Could you try #842?

**Comment by masatake** [comment]
Merged. Thank you.

**Comment by JonathonReinhart** [comment]
@masatake Hi, sorry for the absence; work has taken over recently. Yes, this is still on my radar and hope to pursue it in the near future.

**Comment by masatake** [comment]
@JonathonReinhart, see #1010. We are working on adding json output.
As a by-product, API for output format is implemented. That mean you can write code for:
`ctags --output-format=sqlite`.

**Comment by JonathonReinhart** [comment]
@masatake Thank you, this is still something I want to pursue as time permits.

**Comment by masatake** [comment]
I got another request: https://github.com/universal-ctags/ctags/issues/1232.

**Pull request closed without merging**
