### PR TITLE
docs(web): update SQL man page

### PR DESCRIPTION
**Pull request by masatake**
Signed-off-by: Masatake YAMATO <yamato@redhat.com>

### CODE REVIEW

**Comment by masatake** [comment]
In the last commit, I directly push a commit. This cause a trouble.
I must make a branch and a pull request even when I think a change is so simple and easy.

**Comment by k-takata** [comment]
Is this you really wanted to do?
It seems that you fixed mistakes in 1469a65ff404b21e9245c39b0791c54ed0b03d7c, but you didn't fix `man/ctags-lang-sql.7.rst.in`. So, it caused CI failure.
This PR reverted the changes in `docs/man/ctags-lang-sql.7.rst` instead of fixing `man/ctags-lang-sql.7.rst.in`.
Are you going to create a new PR to re-apply the changes?

**Comment by masatake** [comment]
!!!! You may be correct.
I will revise what I have done.

**Comment by masatake** [comment]
@k-takata, thank you. You are correct.
I took mistakes. #3077 may recover.

**Pull request merged**
