### PR TITLE
Initial pass at OS X documentation

### PR DESCRIPTION
**Pull request by cweagans**
Per https://github.com/universal-ctags/ctags/issues/340#issuecomment-108603580

### CODE REVIEW

**Comment by masatake** [comment]
Could you add an entry for osx.rst to docs/universal-ctags.rst?
Then, please, merge osx.rst.

Thank you.

**Comment by cweagans** [comment]
@masatake I don't have access to merge, but this is ready.

**Comment by masatake** [comment]
o.k. Please, wait for awhile. @ffes may arrange it. (@ffes, am I correct?)

**Comment by ffes** [comment]
I forgot @cweagans to add to the Developers group. Invite is on this way.

@masatake you are owner of the org as well, so you can manager all rights and users of the org as well.

**Pull request merged**
