### PR TITLE
CXX: Mitigate problem with preprocessor macros when emitting types.

### PR DESCRIPTION
**Pull request by pragmaware**
Attempt to filter out types that contain too many macros or other oddities gathered by mistake.

### CODE REVIEW

**Comment by masatake** [comment]
Do you have any test case?

**Comment by pragmaware** [comment]
Heh... it's still not really a fix, so I don't have added one.

This code filters out some obvious cases like the ones referenced in #1120.
( See https://github.com/torvalds/linux/blob/master/lib/locking-selftest.c for an example).

However the real underlying issue is not fixed. The parser will still mistake (few/short) macros for parts of typenames.. Don't know if it's meaningful to add a test. I have just verified that this code does not break the old ones, that is it does not filter out too much.

**Comment by pragmaware** [comment]
A better fix would be to filter out the macros from type names, but that would still work only in files in that the macros are defined. So I don't know if it's worth the effort.

**Comment by masatake** [comment]
Oh, I see.

**Pull request merged**
