### PR TITLE
appveyor: Create html docs

### PR DESCRIPTION
**Pull request by k-takata**
Create html docs on AppVeyor.
I put the html docs in `docs/html/`, but I'm not sure this is the right directory structure.

```
 .
├── COPYING
├── COPYING.MinGW-w64-runtime.txt
├── ctags.exe
├── docs
│   ├── *.rst
│   └── html
│       └── *.html
├── iconv.dll
├── README.md
└── readtags.exe
```

### CODE REVIEW

**Comment by masatake** [comment]
> but I'm not sure this is the right directory structure.

It is the right directory if you think it is the right directory:-P.

BTW, does pacman provide libxml2? u-ctags utilizes it if it is available.

**Comment by k-takata** [comment]
> It is the right directory if you think it is the right directory:-P.

Haha, BTW, should we provide both rst and html docs?

> BTW, does pacman provide libxml2?

Yes. It also provides jansson and libyaml.
However they cannot be used from VC.
Switching the official build from VC to MSYS2 is the easiest way to provide json-, xml- and yaml-enabled ctags binary.

**Comment by masatake** [comment]
Providing only the html files is enough.  The rst files are kinds of source file. 
SVG files like http://docs.ctags.io/en/latest/_images/output-tag-stream.svg should be included.

How different they (ctags built with VC and ctags built with MSYS2) are from users view?
I understand that the users may have preferences of build-tool and environment if they built a ctags binary by themselves.
However, I guess users may not have preferences of build-tool and environment if they just use existing ctags binary. Am I wrong? Are there big gap in execution performance?

**Comment by k-takata** [comment]
> Providing only the html files is enough.

Okay, I will update later. It seems that `_static` directory is also needed.

> How different they (ctags built with VC and ctags built with MSYS2) are from users view?

Maybe not much difference. One thing I noticed is filesize.
VC: 500 KB + PDB
MSYS2 unstripped: 4 MB
MSYS2 stripped: 600 KB

**Comment by k-takata** [comment]
Updated.

**Comment by k-takata** [comment]
Can I merge this?

After this, I will create a new PR to change the compiler for creating zip package from VC to MSYS2.

**Comment by masatake** [comment]
> Can I merge this?


Sure. Please, merge this.

**Pull request merged**
