### PR TITLE
docs(web): Rephrase introduction about --input-encoding

### PR DESCRIPTION
**Pull request by k-takata**
* No need to focus on Japanese. Remove the sentence.
  I, as a Japanese, felt that this sentence was to specific to Japanese.
* Mention UTF-8 and some other actual encodings.

### CODE REVIEW

**Comment by masatake** [comment]
Could you use "docs(web)" instead of "docs" as prefix for the first line of commit log?
Other than this, the change looks good for me. THANK YOU.

**Comment by k-takata** [comment]
It's okay, but what is "docs(web)" for and "docs" for?

**Comment by masatake** [comment]
> It's okay, but what is "docs(web)" for and "docs" for?

Well,... docs(web) means  "documents published as web pages".
Alternative one is docs(man) which means "documents published as man pages".

If you change both web pages and man pages in a commit, "docs" can be used.

**Comment by k-takata** [comment]
Then, when we edit a file in docs/, normally we should use "docs(web)".

**Comment by k-takata** [comment]
I added one more sentence: "These options are useful for such files."

**Pull request merged**
