### PR TITLE
Add Qingming He to docs/developers.rst

### PR DESCRIPTION
**Pull request by QingmingHe**
I'm a Fortran programmer and would like to be one of the developers of universal-ctags.

### CODE REVIEW

**Comment by masatake** [comment]
Welcome!

I have some requests.

0. Please, join the reviewing patches, especially about Fortran parser.
1. If your change is small,  you can commit without making a PR. If not small, please, make a PR.
   @b4n is the authority of parsers/.
2. check geany's code base before trying to fix a bug. We want to make the code gap between ctags and geany small.
3. See #361. When you have time, please, review Units/review-needed.r/*.f.t, fortran related test cases.

BTW, M-x c-guess helps you teach emacs indentation style of the current buffer. It is quite handy and is one of my main work in GNU emacs.

Happy tagging!

**Comment by masatake** [comment]
I sent an invitation. But I'm new to the operation of github organization. So I'm not sure it works as I expected. If you can, please merge this change by yourself. If you get a trouble, write here. @ffes may help us.

**Comment by ffes** [comment]
If needed I gladly help

**Comment by QingmingHe** [comment]
> Please, join the reviewing patches, especially about Fortran parser.

This is what I should do here.

> If your change is small, you can commit without making a PR. If not small, please, make a PR. @b4n is the authority of parsers/.

Just ok, I can determine what is small and what is not.

> check geany's code base before trying to fix a bug. We want to make the code gap between ctags and geany small.

Some of the patches can be imported directly but some are not as there is already gap between these two repos. If there is difference I'll open a PR.

> See #361. When you have time, please, review Units/review-needed.r/*.f.t, fortran related test cases.

Glad to do so.

**Comment by masatake** [comment]
BTW, do you use scheme daily task? If yes, which is your favourite implementation?
I use gauche. I'm looking for readtags.scm.

**Comment by QingmingHe** [comment]
Not daily task, just use it for fun. I use guile.

I really think the elisp parser should be split from lisp.c and re-write an elisp parser. Current implementation is too simple.

**Comment by QingmingHe** [comment]
What do you mean by **readtags.scm**?

**Comment by masatake** [comment]
"Too simple" is also applicable to clojure.c.

As far as I know Python and Perl have a library to load tags file and make data structure.
readtags.c in ctags can do the same thing.

It is handy for me if gauche can load tags file.

**Pull request merged**
