### PR TITLE
Asciidoc: tag inline anchors in one-line titles

### PR DESCRIPTION
**Pull request by hadrielk**

### CODE REVIEW

**Comment by masatake** [comment]
I wodner why 7ab22c6  is included here...

**Comment by hadrielk** [comment]
> I wonder why 7ab22c6 is included here...

Huh. I must have created the branch off of that one instead of master. Ugh.
I fixed it now.

**Comment by hadrielk** [comment]
Sure, will do in the future. I have another PR up (#1857) that has some commits that are refactors  -do you want me to modify the commits and repost the PR?

**Comment by masatake** [comment]
> do you want me to modify the commits and repost the PR?
Yes, please. Asciidoc parser comes from Geany, so making the commit log understandable may help Geany's people.

**Comment by masatake** [comment]
LGTM. Please, merge the changes.

**Pull request merged**
