### PR TITLE
pull the latest libreadtags and packcc

### PR DESCRIPTION
**Pull request by masatake**

### CODE REVIEW

**Comment by masatake** [comment]
A mysterious error is reported on  `compiler=msys2, ARCH=x86, MSYS2_ARCH=i686, MSYS2_DIR=msys64, MSYSTEM=MINGW32`.

**Comment by masatake** [comment]
The values returned from ftell and _ftelli64 are different even for a small file.
https://sourceforge.net/p/mingw-w64/mailman/mingw-w64-public/thread/7a3fd59f-9f83-cc63-5a6e-740aa195069d%40126.com/#msg36082696 explains what I'm seeing well.

**Comment by masatake** [comment]
On the platform `compiler=msys2, ARCH=x86, MSYS2_ARCH=i686, MSYS2_DIR=msys64, MSYSTEM=MINGW32`, `_ftelli64` returns storange values.
In the test case (Tmain/readtags-list-simple-tags), readtags reads a small (< 2GB) tags file.
The file is enough small, so a value returned from ftell and that from ftelli64 for a position must be the same. However, I observed gaps between the two.

In a commit for debugging in this pull request, I put the following code:
```
#ifdef _WIN32
		off_t o0 = ftell (file->fp);
		long long o1 = _ftelli64 (file->fp);
		fprintf(stderr, "unmatch: %ld, ftell: %ld, _ftelli64: %ld\n", (long)(((long long)o0) - ((long long)o1)), (long)o0, (long)o1);
#endif

On the platform I got the following output:
```
C:/projects/ctags/Tmain\readtags-simple-listing.d\stderr-diff.txt
	--- "./Tmain\\readtags-simple-listing.d/stderr-expected.txt"	2022-05-29 16:21:23.687770900 +0000
	+++ C:/projects/ctags/Tmain/readtags-simple-listing.d/stderr-actual.txt	2022-05-29 16:24:19.931677500 +0000
	@@ -0,0 +1,27 @@
	+unmatch: 0, ftell: 0, _ftelli64: 0
	+unmatch: 13, ftell: 94, _ftelli64: 81
	+unmatch: 12, ftell: 165, _ftelli64: 153
	+unmatch: 11, ftell: 229, _ftelli64: 218
	+unmatch: 10, ftell: 292, _ftelli64: 282
	+unmatch: 9, ftell: 355, _ftelli64: 346
	+unmatch: 8, ftell: 416, _ftelli64: 408
	+unmatch: 7, ftell: 498, _ftelli64: 491
	+unmatch: 6, ftell: 566, _ftelli64: 560
	+unmatch: 5, ftell: 621, _ftelli64: 616
	+unmatch: 0, ftell: 0, _ftelli64: 0
	+unmatch: 0, ftell: 94, _ftelli64: 94
	+unmatch: -1, ftell: 165, _ftelli64: 166
	+unmatch: -2, ftell: 229, _ftelli64: 231
	+unmatch: -3, ftell: 292, _ftelli64: 295
	+unmatch: -4, ftell: 355, _ftelli64: 359
	+unmatch: -5, ftell: 416, _ftelli64: 421
	+unmatch: -6, ftell: 498, _ftelli64: 504
	+unmatch: 6, ftell: 566, _ftelli64: 560
	+unmatch: 5, ftell: 621, _ftelli64: 616
	+unmatch: 0, ftell: 621, _ftelli64: 621
	+unmatch: 0, ftell: 715, _ftelli64: 715
	+unmatch: -1, ftell: 810, _ftelli64: 811
	+unmatch: -2, ftell: 905, _ftelli64: 907
	+unmatch: 0, ftell: 907, _ftelli64: 907
	+unmatch: 1, ftell: 1037, _ftelli64: 1036
	+unmatch: 0, ftell: 1146, _ftelli64: 1146
```

https://sourceforge.net/p/mingw-w64/mailman/mingw-w64-public/thread/7a3fd59f-9f83-cc63-5a6e-740aa195069d%40126.com/#msg36082696 explains the issue I observed well.

It seems that on some platforms, msys2? provides the implementation of _ftelli64, and the bug is in the implementation. On the page of the URL, the term "race condition" is used. 
A strange thing is that our test case doesn't use any threads.

@k-takata, as usual, I need your help. do you have any ideas to overcome this issue?

**Comment by k-takata** [comment]
I ran this branch in my local environment (MINGW32), and I see no problems:

```
--- ../Tmain/readtags-simple-listing.d/stderr-expected.txt	2022-05-31 17:11:17.194122900 +0900
+++ C:/work/universal-ctags/build-mingw/Tmain/readtags-simple-listing.d/stderr-actual.txt	2022-05-31 17:13:03.656920700 +0900
@@ -0,0 +1,27 @@
+unmatch: 0, ftell: 0, _ftelli64: 0
+unmatch: 0, ftell: 94, _ftelli64: 94
+unmatch: 0, ftell: 165, _ftelli64: 165
+unmatch: 0, ftell: 229, _ftelli64: 229
+unmatch: 0, ftell: 292, _ftelli64: 292
+unmatch: 0, ftell: 355, _ftelli64: 355
+unmatch: 0, ftell: 416, _ftelli64: 416
+unmatch: 0, ftell: 498, _ftelli64: 498
+unmatch: 0, ftell: 566, _ftelli64: 566
+unmatch: 0, ftell: 621, _ftelli64: 621
+unmatch: 0, ftell: 0, _ftelli64: 0
+unmatch: 0, ftell: 94, _ftelli64: 94
+unmatch: 0, ftell: 165, _ftelli64: 165
+unmatch: 0, ftell: 229, _ftelli64: 229
+unmatch: 0, ftell: 292, _ftelli64: 292
+unmatch: 0, ftell: 355, _ftelli64: 355
+unmatch: 0, ftell: 416, _ftelli64: 416
+unmatch: 0, ftell: 498, _ftelli64: 498
+unmatch: 0, ftell: 566, _ftelli64: 566
+unmatch: 0, ftell: 621, _ftelli64: 621
+unmatch: 0, ftell: 621, _ftelli64: 621
+unmatch: 0, ftell: 715, _ftelli64: 715
+unmatch: 0, ftell: 810, _ftelli64: 810
+unmatch: 0, ftell: 905, _ftelli64: 905
+unmatch: 0, ftell: 905, _ftelli64: 905
+unmatch: 0, ftell: 1037, _ftelli64: 1037
+unmatch: 0, ftell: 1146, _ftelli64: 1146
```

This doesn't happen on the MINGW32 environment in GitHub Actions, right? 
The MINGW32 environment in AppVeyor might be old, and we need to update the environment by pacman?

**Comment by k-takata** [comment]
Could you try this workaround?

```diff
diff --git a/win32/appveyor.bat b/win32/appveyor.bat
index c6360469..5df64b92 100755
--- a/win32/appveyor.bat
+++ b/win32/appveyor.bat
@@ -141,6 +141,10 @@ if "%normalbuild%"=="no" (
   @rem Also install packages needed for creating zip package
   bash -lc "for i in {1..3}; do pacman --noconfirm --noprogressbar -S --needed mingw-w64-%MSYS2_ARCH%-python3-sphinx && break || sleep 15; done"
 )
+@rem Synchronize package databases and upgrade the core system
+C:\%MSYS2_DIR%\usr\bin\pacman --noconfirm --noprogressbar -Syu
+@rem Run again to update the rest of packages
+C:\%MSYS2_DIR%\usr\bin\pacman --noconfirm --noprogressbar -Su
 :: Install necessary packages
 bash -lc "for i in {1..3}; do pacman --noconfirm --noprogressbar -S --needed mingw-w64-%MSYS2_ARCH%-{jansson,libxml2,libyaml,pcre2} autoconf automake && break || sleep 15; done"
 
```

**Comment by masatake** [comment]
@k-takata thank you for the comment.

The unmatched are still reproduced.

```
C:/projects/ctags/Tmain\readtags-simple-listing.d\stderr-diff.txt
	--- "./Tmain\\readtags-simple-listing.d/stderr-expected.txt"	2022-05-31 12:28:16.405368300 +0000
	+++ C:/projects/ctags/Tmain/readtags-simple-listing.d/stderr-actual.txt	2022-05-31 12:32:33.578373700 +0000
	@@ -0,0 +1,27 @@
	+unmatch: 0, ftell: 0, _ftelli64: 0
	+unmatch: 13, ftell: 94, _ftelli64: 81
	+unmatch: 12, ftell: 165, _ftelli64: 153
	+unmatch: 11, ftell: 229, _ftelli64: 218
	+unmatch: 10, ftell: 292, _ftelli64: 282
	+unmatch: 9, ftell: 355, _ftelli64: 346
	+unmatch: 8, ftell: 416, _ftelli64: 408
	+unmatch: 7, ftell: 498, _ftelli64: 491
	+unmatch: 6, ftell: 566, _ftelli64: 560
	+unmatch: 5, ftell: 621, _ftelli64: 616
	+unmatch: 0, ftell: 0, _ftelli64: 0
	+unmatch: 0, ftell: 94, _ftelli64: 94
	+unmatch: -1, ftell: 165, _ftelli64: 166
	+unmatch: -2, ftell: 229, _ftelli64: 231
	+unmatch: -3, ftell: 292, _ftelli64: 295
	+unmatch: -4, ftell: 355, _ftelli64: 359
	+unmatch: -5, ftell: 416, _ftelli64: 421
	+unmatch: -6, ftell: 498, _ftelli64: 504
	+unmatch: 6, ftell: 566, _ftelli64: 560
	+unmatch: 5, ftell: 621, _ftelli64: 616
	+unmatch: 0, ftell: 621, _ftelli64: 621
	+unmatch: 0, ftell: 715, _ftelli64: 715
	+unmatch: -1, ftell: 810, _ftelli64: 811
	+unmatch: -2, ftell: 905, _ftelli64: 907
	+unmatch: 0, ftell: 907, _ftelli64: 907
	+unmatch: 1, ftell: 1037, _ftelli64: 1036
	+unmatch: 0, ftell: 1146, _ftelli64: 1146
```

**Comment by k-takata** [comment]
Oh, it looks that the base environment is too old:

```
C:\projects\ctags>C:\msys64\usr\bin\pacman --noconfirm --noprogressbar -Syu 
:: Synchronizing package databases...
downloading mingw32.db...
downloading mingw32.db.sig...
error: mingw32: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" is unknown
error: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" could not be looked up remotely
error: failed to update mingw32 (invalid or corrupted database (PGP signature))
downloading mingw64.db...
downloading mingw64.db.sig...
error: mingw64: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" is unknown
error: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" could not be looked up remotely
error: failed to update mingw64 (invalid or corrupted database (PGP signature))
downloading msys.db...
downloading msys.db.sig...
error: msys: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" is unknown
error: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" could not be looked up remotely
error: failed to update msys (invalid or corrupted database (PGP signature))
error: failed to synchronize all databases
```

This might be related?
https://www.msys2.org/news/#2020-06-29-new-packagers

**Comment by masatake** [comment]
@k-takata, thank you. I will update this pull request.

**Comment by masatake** [comment]
It seems that the state of vagrantcloud.com is changed.

**Pull request merged**
