### PR TITLE
perl: added support for method keyword

### PR DESCRIPTION
**Pull request by jimmygoogle**
I added Perl support for the method keyword used in the Function::Parameters class.

### CODE REVIEW

**Comment by masatake** [comment]
Thank you for this pull request.

Don't you want to support "fun" keyword?

**Comment by jimmygoogle** [comment]
I should add 'fun' as well. My use case what primarily for 'method'.

**Comment by masatake** [comment]
I have two requests:

* supporting fun
* adding test cases
Could you look at https://docs.ctags.io/en/latest/testing.html#units-test-facility for adding a test case?

**Comment by jimmygoogle** [comment]
Yes I can do this.

**Comment by masatake** [comment]
I must write my plan.
I would like to convert your change to a sub parser like a parser for Moose instead of merging your code directly. See parsers/moose.c.

The test cases for "method" and "fun" is quite important to make the subparser work as you, the original author of the change, expected.

About the concept of sub parser,  see
https://docs.ctags.io/en/latest/running-multi-parsers.html?highlight=subparser#tagging-definitions-of-higher-upper-level-language-sub-base .

**Comment by masatake** [comment]
See #2841.

**Comment by jimmygoogle** [comment]
Looking at things, I am way out of my depth in making this a subparser. I
could do a unit test but thats about it.

**Comment by masatake** [comment]
I would like you to see the test case in #2841.
fun and method are detected only in files where Function::Parameters is used.

**Comment by masatake** [comment]
I found I didn't the test case to my #2841 though I merged the pull request.
I made a new pull request that includes only the test case I forgot to add to #2841.
Could you look at #2846?

**Comment by jimmygoogle** [comment]
I am still working on the test case. I didn't have time to finish it last
night.

**Pull request closed without merging**
