### PR TITLE
GitHub Actions: vagrant box using cache

### PR DESCRIPTION
**Pull request by leleliu008**
Reference: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows

Thanks to `Masatake YAMATO` comment in https://github.com/universal-ctags/ctags/pull/3491#issuecomment-1260089341

Signed-off-by: leleliu008 <leleliu008@gmail.com>

### CODE REVIEW

**Comment by masatake** [comment]
Excellent! I'm surprised at the change for caching is much smaller than I assumed.

**Comment by leleliu008** [comment]
> Excellent! I'm surprised at the change for caching is much smaller than I assumed.

I first time to use this action, what confused me is that BSD workflows is not run.

**Review by masatake — APPROVED** [review]

**Comment by masatake** [comment]
We don't need serializing testing on BSDs anymore, do we?

**Comment by leleliu008** [comment]
@masatake we can use [gh-actions-cache](https://github.com/actions/gh-actions-cache) to manage these caches

Screenshot from 2022-09-28 17-41-50

**Comment by masatake** [comment]
> 

> @masatake we can use [gh-actions-cache](https://github.com/actions/gh-actions-cache) to manage these caches
> 
> Screenshot from 2022-09-28 17-41-50

Does it mean we HAVE to manage the life cycle of caches?
e.g. when releasing a new version of xBSD, we have to throw away the cache for the old one?

**Comment by leleliu008** [comment]
> We don't need serializing testing on BSDs anymore, do we?

Yes, we do not need `.github/workflows/testing-bsds.yml.bak` any more  in theory, but I keep it  without deleting it, if this pull request run well, we can delete it.

**Comment by masatake** [comment]
> Yes, we do not need .github/workflows/testing-bsds.yml.bak any more in theory, but I keep it without deleting it, if this pull request run well, we can delete it.

I strongly agree with you.

**Comment by masatake** [comment]
The testing on S390 is enough slow, so serializing the testing on BSDs cannot be a bottle neck:-P.

**Comment by leleliu008** [comment]
> The testing on S390 is enough slow, so serializing the testing on BSDs cannot be a bottle neck:-P.

`.github/workflows/testing-big-endian.yml` is using `KVM+qemu`, codes run in virtual machine is slower, I will look into this.

**Pull request merged**
