### PR TITLE
Reject more non alnum chars in langdef

### PR DESCRIPTION
**Pull request by masatake**
All changes about --langdef option.

The main change is for rejecting characters like @, $, % as a parser name.

### CODE REVIEW

**Comment by masatake** [comment]
optlib2c is not done yet.

**Comment by k-takata** [comment]
This means that if someone create a language named C%, u-ctags doesn't accept it, right?
C++ and C# use symbols in their names. Why should other symbols be rejected?

**Comment by masatake** [comment]
> This means that if someone create a language named C%, u-ctags doesn't accept it, right?

Right. It doesn't accept it with this change.

> C++ and C# use symbols in their names. Why should other symbols be rejected?

I would like to keep some graph characters as metacharacters for extending ctags command line.

Currently, [-:{=]  cannot be used because the command line parser is confused.
So there is no strong reason for disallowing using the graph character other than [-:{=+#].

Do you think this is to restrict?

**Comment by masatake** [comment]
I wrote above comment to the commit log.

**Comment by masatake** [comment]
https://en.wikipedia.org/wiki/List_of_programming_languages

**Comment by masatake** [comment]
Comments are welcome. However, we can shrink the disallowing-character list even after releasing 6.0.0.
So I think we can start the more restricted one and can wait feedback.

**Comment by k-takata** [comment]
I understand your intention.

**Comment by masatake** [comment]
I updated ctags-incompatibilities.7.rst.in.

**Pull request merged**
