### PR TITLE
GitHub Actions: set HOMEBREW_NO_INSTALL_CLEANUP

### PR DESCRIPTION
**Pull request by masatake**

### CODE REVIEW

**Comment by leleliu008** [comment]
You do not need to set that, that already has been done for you. https://github.com/actions/runner-images/issues/2466

**Comment by masatake** [comment]
@leleliu008 Thank you. How can we avoid the failure on "run units target on macOS / testing (macos-13) (pull_request)" ?

**Comment by leleliu008** [comment]
```
brew install --overwrite python@3.12
```

**Comment by masatake** [comment]
However, I found the following comment that you wrote in testing-mac.yml:
```
    # NOTE: DO NOT try to install python3 package via brew, it has already been included in macos-xx runner images
```

Should I delete the comment and add `brew install --overwrite python@3.12` instead?

**Comment by leleliu008** [comment]
There are many python packages like python@3.10 python@3.11 python@3.12 in brew, they always conflict with each other.

**Comment by masatake** [comment]
??? So what should we do? 
Should we specify the version of python explicitly though though a version of python has already been included in macos-xx runner images?

**Comment by leleliu008** [comment]
> However, I found the following comment that you wrote in testing-mac.yml:
> 
> ```
>     # NOTE: DO NOT try to install python3 package via brew, it has already been included in macos-xx runner images
> ```
> 
> Should I delete the comment and add `brew install --overwrite python@3.12` instead?


we do not install a python package though, but many packages may depend on different version of python packages. HomeBrew Team update their package formula frequently, it's very unstable, but it usually canbe fix via `brew install --overwrite python@x.y`

**Comment by leleliu008** [comment]
> ??? So what should we do? Should we specify the version of Python explicitly, though a version of Python has already been included in macos-xx runner images?

Yes, no good solution. It is not a stable package manager after all.

**Comment by leleliu008** [comment]
let me fix it. I will file a new PR to fix it.

**Comment by leleliu008** [comment]
fixed as https://github.com/universal-ctags/ctags/pull/3955

**Pull request closed without merging**
