### PR TITLE
build-sys: don't use libxml-2 if its CRLF handling is broken

### PR DESCRIPTION
**Pull request by masatake**
See #3851 .

### CODE REVIEW

**Comment by masatake** [comment]
??? Why the errors of the test case is not reproduced?

**Comment by masatake** [comment]
It seems that I must cherry-pick #3854.

**Comment by masatake** [comment]
@leleliu008 I added AC_RUN_IFELSE to configure.ac.
What do you think about this? I'm afraid of breaking the cross-compiling infrastructure you have polished.

**Comment by masatake** [comment]
As I am afraid, running configure on s390x has failed.

**Comment by masatake** [comment]
@leleliu008 thank you.

```
 -- Macro: AC_RUN_IFELSE (INPUT, [ACTION-IF-TRUE], [ACTION-IF-FALSE],
          [ACTION-IF-CROSS-COMPILING = ‘AC_MSG_FAILURE’])
 ```

O.K. I will fill the 4th parameter.

**Comment by leleliu008** [comment]
About the macos-13 workflow fails, please rebase master branch, I have merge https://github.com/universal-ctags/ctags/pull/3861 to branch, it should be fixed.

**Comment by masatake** [comment]
@leleliu008 Thank you.

**Comment by masatake** [comment]
What I studied while developing this puu request is that `pkg-config` doesn't support `&&` operator.

**Comment by masatake** [comment]
I won!

**Pull request merged**
