### PR TITLE
GitHub Actions: update freebsd vm

### PR DESCRIPTION
**Pull request by masatake**
Signed-off-by: Masatake YAMATO <yamato@redhat.com>

### CODE REVIEW

**Review by leleliu008 — APPROVED** [review]

**Comment by leleliu008** [comment]
this action has problem. so I file a new PR to replace this actions. #3336

**Comment by masatake** [comment]
> this action has problem. so I file a new PR to replace this actions. https://github.com/universal-ctags/ctags/pull/3336

@leleliu008, though my pull request has the problem, this pull request can make all "green" on all environments. So I would like to merge this.
Your much better solutions can be merged later.

The "red" of FreeBSD stops the development of ctags now.
I would like to rid it as soon as possible.

**Comment by leleliu008** [comment]
OK, no problem.

**Comment by masatake** [comment]
Thank you.
I will merge this one after the tests are completed.

**Comment by masatake** [comment]
@leleliu008, could you rebase your pull requests on the latest master branch?

**Comment by leleliu008** [comment]
Ok,I will do it.

**Comment by leleliu008** [comment]
I have rebased PR #3337 with the latest master branch, let's handle #3337 first.

**Pull request merged**
