### PR TITLE
docs: improve the examples about how to run specified cases under Units

### PR DESCRIPTION
**Pull request by masatake**
Add an exapmle to run more than one test cases under Units.

Signed-off-by: Masatake YAMATO <yamato@redhat.com>

### CODE REVIEW

**Comment by masatake** [comment]
This closes #783.

**Comment by masatake** [comment]
Surprisingly, the way to run a specified case under Units has written already in units.rst.
In this commit, I have just added one more example.

**Comment by blueyed** [comment]
Thanks!

s/exapmle/example/

Can this be linked to / referred from the main readme?

**Comment by masatake** [comment]
Thank you for checking. I must run anytime writing English.
I updated README.md.

**Comment by blueyed** [comment]
The "exapmle" typo is still in there.

**Pull request merged**
