### PR TITLE
build-sys,mvc: generate rules for running packcc from source.mak

### PR DESCRIPTION
**Pull request by masatake**

### CODE REVIEW

**Comment by masatake** [comment]
A temporary issue?

```
Installing additional packages through pacboy...
  C:\Windows\system32\cmd.exe /D /S /C D:\a\_temp\setup-msys2\msys2.cmd -c "'pacboy' '--noconfirm' '-S' '--needed' 'toolchain:p' 'python3-sphinx:p' 'jansson:p' 'libxml2:p' 'libyaml:p' 'pcre2:p'"
  :: There are 13 members in group mingw-w64-i686-toolchain:
  :: Repository mingw32
     1) mingw-w64-i686-binutils  2) mingw-w64-i686-crt-git  3) mingw-w64-i686-gcc  4) mingw-w64-i686-gdb  5) mingw-w64-i686-gdb-multiarch  6) mingw-w64-i686-headers-git  7) mingw-w64-i686-libmangle-git  8) mingw-w64-i686-libwinpthread-git  9) mingw-w64-i686-make  10) mingw-w64-i686-pkgconf  11) mingw-w64-i686-tools-git  12) mingw-w64-i686-winpthreads-git  13) mingw-w64-i686-winstorecompat-git
  
  Enter a selection (default=all): error: target not found: mingw-w64-i686-python3-sphinx
```

**Comment by leleliu008** [comment]
It seems that python3-sphinx has been renamed to python-sphinx.

**Comment by masatake** [comment]
Thank you. I'll prepend a commit to this pull request.

**Comment by leleliu008** [comment]
try to change python3-sphinx:p to python-sphinx:p will do the trick.

**Comment by masatake** [comment]
@leleliu008 Thank you.

**Pull request merged**
