### PR TITLE
Fix that writing tags to stdout didn't work with MSYS2(masatake: till Aug 23)

### PR DESCRIPTION
**Pull request by k-takata**
There were two problems with tempfile handling on MSYS2.

1. MinGW-w64 has mkstemp(), but it deletes a tempfile automatically when the file descriptor is closed. However u-ctags expects that the file remains.
2. tempdir was set to '/tmp', but it's not prefer for Windows. Use `TMP` environment for the temporary directory.

Related: #494

### CODE REVIEW

**Comment by masatake** [comment]
How about mkstemp? mkstemp tells a caller the name of created file.
As you wrote in the initial message, it removes the file when closing it. For this behavior we can make the closing delayed.

Does I miss anything?

**Comment by k-takata** [comment]
I confirmed that other processes cannot open the temporary file created by `mkstemp` (and not closed yet) on MSYS2.

So, [your proposal](https://github.com/k-takata/ctags/commit/6b38524db47e1972bc7b3fb2eaef4864d590b934#commitcomment-12693349) can be used for internal sort mode but it cannot be used for external sort mode.

Additionally, MSVC doesn't have `mkstemp`.

**Comment by masatake** [comment]
I see.
How about popen instead of system in externalSortTags? 
(I strongly believe sort on the platform accept standard in.:-)

**Comment by k-takata** [comment]
Updated. I used `dup2` and `system` to redirect the stdin.

**Comment by masatake** [comment]
I will review. these changes.

**Comment by k-takata** [comment]
Updated. I will squash the commits later.

**Comment by k-takata** [comment]
Squashed. (Some parts are moved to another commit.)

**Pull request merged**
