### PR TITLE
Typescript: fixes #2175, #2176

### LINKED ISSUE #2175: The typescript parser does not handle properly expressions that end with a curly brace not separated by a space
The typescript parser stops parsing the file at the line with the call to `g`.
Adding a space before the closed brace in the argument of `g` makes the parser work correctly.

The name of the parser: TypeScript
The command line you used to run ctags:

```
$ ctags --options=NONE file.ts
```

The content of input file:

```TypeScript
class X {
    public f(a: T): number {
        return g({ a: a});
    }

    public g(a: T): number {
        return 1;
    }
}
```

The tags output you are not satisfied with:

```
x.ts,52
class X {^?X^A1,0
    public f(a: T): number {^?f^A2,10
```

The tags output you expect:

```
x.ts,88
class X {^?X^A1,0
    public f(a: T): number {^?f^A2,10
    public g(a: T): number {^?g^A6,74
```

The version of ctags:

```
$ ctags --version
Universal Ctags 0.0.0(b818539), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Aug 14 2019, 16:54:57
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +packcc
```

How do you get ctags binary:

Building it locally, via GNU/Linux distribution, as BSD's package,

### PR DESCRIPTION
**Pull request by ksamborski**
Both issues are related to functions but in different way. I added test cases for them and this PR should now fix all of them.  @masatake please take a look if you have a moment

### CODE REVIEW

**Comment by masatake** [comment]
LGTM.

**Comment by ksamborski** [comment]
OK, I've changed commit messages for those with `close #n`.

**Comment by masatake** [comment]
Well... I expected just adding "Close #n" like:

```
Typescript: fixed parsing variables that are functions
Close #2176.
```

However, you did
```
Typescript: close #2176 
Fixed parsing variables that are functions
```

I like the former style.

**Comment by ksamborski** [comment]
Thanks, fixed.

**Pull request merged**
