### PR TITLE
Repair --line-directive option

### LINKED ISSUE #402: line directive and extra language
During previewing 
Units/review-needed.r/line_directives.c.d/input.c
I got a coredump.

```
[yamato@x201]~/var/ctags-github% cat /tmp/input.c 
#line 2 f.f
#define x
[yamato@x201]~/var/ctags-github% ./ctags -o - --fields='+l' --line-directives /tmp/input.c 
ctags: main/parse.c:1279: isLanguageKindEnabled: Assertion `kindOpt = langKindOption (language, kind)' failed.
zsh: abort (core dumped)  ./ctags -o - --fields='+l' --line-directives /tmp/input.c
```

With `#line` directive, ctags changes the values of global variables for input file name and its language. In the above example the language is changed from c to fortran.
Though the values are changed, C parser continues parsing and making a tag.
The kind of a tag created by c parser is verified by comparing with fortran's kind table.
`x` has a kind `d`, macro definition while fortran parser doesn't know `d` .
This gap makes the assertion failure.

I was afraid that a code I introduced ago triggers this assertion. However, it does not.
The exuberant ctags doesn't have the assertion line in its source code.
 As the result it generates a bit strange  tags file.

```
[yamato@x201]~/var/ctags-github% ctags -o - --fields='+l' --line-directives /tmp/input.c 
ctags: Warning: Ignoring non-option in ./.ctags

x	/tmp/f.f	2;"	d	language:Fortran	file:
```

Though the language is Fortran, a kind `d`, which Fortran parser doesn't know, is used.

This is a blocker for moving 
Units/review-needed.r/line_directives.c.d to Units/parser-c.r/.

### PR DESCRIPTION
**Pull request by masatake**
Close #402.

Universal-ctags --line-directive option is broken as reported in #402.
This patch set fixes it. Though the many areas are changed, the patch set
just makes the behaviour of u-ctags with --line-directive option as the same as
e-ctags. Nothing interesting feature like adding new role for reference tags is added here.

However, in this patch set, macros, types, and functions  in read.h are reorganized.
See docs/internal.rst for more details.

### CODE REVIEW

**Comment by masatake** [comment]
@k-takata, I have a question.

Is there way to detect whether a test is run on Appveyor or not from an environment variable or something?

About on Travis TRAVIS is defined. So I can use it in Makefile like:

```
ifdef TRAVIS
SHOW_DIFF_OUTPUT=--show-diff-output
endif
```

I need the same on Appveyor.

**Comment by masatake** [comment]
Maybe I should modify appveyor.bat.

**Comment by k-takata** [comment]
http://www.appveyor.com/docs/environment-variables
`APPVEYOR` is set to `True`.

**Comment by masatake** [comment]
@k-takata, thank you. I will withdraw acd188f when merging.

**Comment by masatake** [comment]
Finally I got the diff output of failed case.

```
+ sed -e 's/./	\0/' /c/projects/ctags/Units/parser-c.r/line_directives.c.d/DIFF.tmp
	--- ./Units/parser-c.r/line_directives.c.d/expected.tags	2015-11-27 07:49:18.369964400 +0000
	+++ /c/projects/ctags/Units/parser-c.r/line_directives.c.d/FILTERED.tmp	2015-11-27 07:53:14.307741300 +0000
	@@ -1,5 +1,5 @@
	-a	a.c	10;"	v	language:C
	-b	b.c	20;"	v	language:C
	-c	c.c	30;"	v	language:C
	-d	OK.zzz	2;"	v	language:NEWLANG
	-e	OK.y	100;"	v	language:YACC
	+a	line_directives.c.d\\a.c	10;"	v	language:C
	+b	line_directives.c.d\\b.c	20;"	v	language:C
	+c	line_directives.c.d\\c.c	30;"	v	language:C
	+d	line_directives.c.d\\OK.zzz	2;"	v	language:NEWLANG
	+e	line_directives.c.d\\OK.y	100;"	v	language:YACC
+ echo
 
+ '[' 5 = 0 ']'
```

**Comment by masatake** [comment]
@k-takata, @ffes, on  "Environment: compiler=msys2, MSYS2_ARCH=x86_64, MSYS2_DIR=msys64, MSYSTEM=MINGW64" what kind of file separator should ctags use when emitting a file path to tags file?
/ or \\ ? 

Search "RAWOUT" in https://ci.appveyor.com/project/masatake/ctags/build/1.0.351/job/jkllof55cpun23cm 
New code it seems that new code I introduced uses both / and \\.

**Comment by masatake** [comment]
old-docs/NEWS.exuberant:
```
* Added compile time option to separate path components with a unix-style path
  separator for sharing tag file across platforms, enabled by defining the
  label UNIX_PATH_SEPARATOR [Win32].

```

**Comment by masatake** [comment]
The separator issue is not new in this patch set.
I decide to inject a filter as a workaround. 
https://github.com/masatake/ctags/blob/repair-line-directive-option/Units/parser-c.r/line_directives.c.d/filter

**Pull request merged**
