### PR TITLE
Use mkdir-p without checking its availablity

### PR DESCRIPTION
**Pull request by masatake**
Signed-off-by: Masatake YAMATO <yamato@redhat.com>

### CODE REVIEW

**Comment by vhda** [comment]
Do you think there's no problem in doing this?

**Comment by p-montanus** [comment]
In unit: target
```
units: $(CTAGS_TEST)
        @ \
        builddir=$$(pwd); \
        mkdir -p $${builddir}/Units && \
```
and tmain: target
```
tmain: $(CTAGS_TEST)
        @ \
        \
        builddir=$$(pwd); \
        mkdir -p $${builddir}/Tmain && \
```
use 'mkdir -p', It seems no problem.

**Comment by masatake** [comment]
o.k. Let's assume mkdir -p is always available.

> Do you think there's no problem in doing this?
I don't know but there is a race conditoin. I will do as @p-montanus wrote.
I cannot ignore your request about RHEL5:-)

**Comment by masatake** [comment]
I will prepare a new patch.

**Comment by masatake** [comment]
If  continuous-integration/appveyor  and  continuous-integration/travis-ci/pr say O.k., I will merge this commit.

**Pull request merged**
