### PR TITLE
Store the results of tmain and units to separeted builddir

### PR DESCRIPTION
**Pull request by masatake**

### CODE REVIEW

**Comment by masatake** [comment]
How I tested the change:
```
$ mkdir /tmp/b
$ cd /tmp/b
$ ~/ctags/configure --srcdir=/home/masatake/ctags
$ make tmain
```

**Comment by k-takata** [comment]
Does this PR stores only tmain results to separated directory?
How about units results?

**Comment by masatake** [comment]
About Units, I have not implemented yet. But I would like to get feed-back about this change.

**Comment by k-takata** [comment]
I confirmed that this PR works fine for tmain.

**Comment by masatake** [comment]
Is there portable way to get the first character of a string in a shell script?
```${x:0:1}```` is not portable available in dash.
```$(expr substr $x 1 1)``` doesn't work on macosx.

Do I have to use sed here?

**Comment by masatake** [comment]
I should use grep.

**Comment by masatake** [comment]
It works. I'm a bit tired.

**Comment by vhda** [comment]
https://wiki.ubuntu.com/DashAsBinSh

And have done rest :)

**Comment by masatake** [comment]
I trued the changes with dash. I found "source" is not available dash.

**Comment by masatake** [comment]
@k-takata, these changes for units target solves #511?

**Comment by k-takata** [comment]
Yes. I confirmed that the changes works fine.

**Comment by masatake** [comment]
Thank you for confirmation.

**Pull request merged**
