### PR TITLE
docs: minor fixes: emphasize lines option, etc.

### PR DESCRIPTION
**Pull request by hirooih**
Minor fixes after #2916.

### CODE REVIEW

**Review by masatake — APPROVED** [review]

**Comment by hirooih** [comment]
Thank you for your prompt review.

The fail on FreeBSD is as follows;

```
...
Sync FreeBSD time
exec ssh: ntpdate -b pool.ntp.org
/usr/bin/ssh -t freebsd
Pseudo-terminal will not be allocated because stdin is not a terminal.
Warning: Permanently added '[localhost]:2222' (ECDSA) to the list of known hosts.
Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
22 Mar 14:59:05 ntpdate[800]: no server suitable for synchronization found
Error: The process '/usr/bin/ssh' failed with exit code 1
...
```

It seems an ntp related issue. I saw this error many times.  It should be OK for this PR.
Let me merge this PR.

**Comment by masatake** [comment]
https://github.com/vmactions/freebsd-vm/commit/457af7345642e154a79d219971a2d4a7c7fe2118 may mitigate the failure on FreeBSD. v0.1.3 includes the patch.

**Comment by masatake** [comment]
See #2921.

**Comment by hirooih** [comment]
I rerun the failed test and it passed.
Thanks!

**Pull request merged**
