### PR TITLE
Tweak some messages.

### PR DESCRIPTION
**Pull request by adoxa**
Adjust the length of help messages to stay within 80 columns.
Add a space before a bracket.
Update the list of include extensions.
Fix typos.
Also adjusts some source indentation.  BTW, there's a mixture of tabs and spaces, so (de)tabbing the lot might be nice.

### CODE REVIEW

**Comment by masatake** [comment]
Thank you. Could you tell me how do you find these and make the patch for them?
Though we introduce your fix, we may introduce similar issues in the future.
I would like to prevent the same mistakes.

**Comment by adoxa** [comment]
Find what? Long messages I found by simply viewing the help and seeing what wrapped. I noticed the definition of the include extensions had two more than the help. Typos I fix as I happen to come across them. Noticing indentation was a side-effect of a string search (looking for brackets). Tabs I noticed because I default to tabs, so the diff picked up the change from space. If you mean tabs/spaces, my editor ([TDE](http://tde.adoxa.vze.com/)) has commands to detab and entab leading spaces.

**Comment by masatake** [comment]
Thank you for explanation.
Can I ask you to update the test cases? Both Travis and appveyor  report failures.

You can run the test cases with "make tmain".

**Comment by masatake** [comment]
@k-takata, thank you.

**Comment by adoxa** [comment]
MSYS (the "original") does not support any sort of command line override, as far as I can tell. This might finally push me to use MSYS2...

**Comment by masatake** [comment]
O.k. I will merge your change partially.

**Comment by masatake** [comment]
(Surprisingly  MSYS2_ARG_CONV_EXCL hack is already installed to tmain; prepare_environment function is called before main function. @k-takata, thank you for great work.)

**Comment by masatake** [comment]
@adoxa., I merged many part of your change into master directly. (I rebased your changes on master.)

Following changes are nor merged because these changes are nothing todo with "Tweak some messages".  The changes are related to running test cases on MSYS. I don't know well about MSYS, so I split your change into two and merge the part of them. If you think I should merge the rest of part, could you make a new pull request? So the windows expert(s) may review it. Thank you for the contribution.

```
diff --git a/Tmain/lregex-accept-reserved-kind.d/run.sh b/Tmain/lregex-accept-reserved-kind.d/run.sh
index 326e23c..f286856 100644
--- a/Tmain/lregex-accept-reserved-kind.d/run.sh
+++ b/Tmain/lregex-accept-reserved-kind.d/run.sh
@@ -3,4 +3,4 @@
 
 CTAGS=$1
 
-${CTAGS} --quiet --options=NONE -o - --langdef=foo'{fileKind=!}' --regex-foo=/a/\0/F/ run.sh
+${CTAGS} --quiet --options=NONE -o - --langdef=foo'{fileKind=!}' --regex-foo=:a:\0:F: run.sh
diff --git a/Tmain/lregex-list-kind-full.d/run.sh b/Tmain/lregex-list-kind-full.d/run.sh
index c5b892d..8262517 100644
--- a/Tmain/lregex-list-kind-full.d/run.sh
+++ b/Tmain/lregex-list-kind-full.d/run.sh
@@ -5,9 +5,9 @@ CTAGS=$1
 
 ${CTAGS} --quiet --options=NONE -o - \
         --langdef=foo \
-        --regex-foo='/a/\0/a,x y,x y z/' --kinds-foo=-a --foo-kinds=+a \
-        --regex-foo=/b/\0/b/ --foo-kinds=-b \
-        --regex-foo=/c/\0/c/ \
+        --regex-foo=':a:\0:a,x y,x y z:' --kinds-foo=-a --foo-kinds=+a \
+        --regex-foo=:b:\0:b: --foo-kinds=-b \
+        --regex-foo=:c:\0:c: \
         --kinds-foo=-c \
-        --regex-foo=/d/\0/d/ \
+        --regex-foo=:d:\0:d: \
         --_list-kinds-full=foo
diff --git a/Tmain/lregex-list-kinds.d/run.sh b/Tmain/lregex-list-kinds.d/run.sh
index 247b594..3ff0a2e 100644
--- a/Tmain/lregex-list-kinds.d/run.sh
+++ b/Tmain/lregex-list-kinds.d/run.sh
@@ -5,10 +5,10 @@ CTAGS=$1
 
 ${CTAGS} --quiet --options=NONE -o - \
         --langdef=foo \
-        --regex-foo=/a/\0/a/ --kinds-foo=-a --foo-kinds=+a \
-        --regex-foo=/b/\0/b/ --foo-kinds=-b \
-        --regex-foo=/c/\0/c/ \
+        --regex-foo=:a:\0:a: --kinds-foo=-a --foo-kinds=+a \
+        --regex-foo=:b:\0:b: --foo-kinds=-b \
+        --regex-foo=:c:\0:c: \
         --kinds-foo=-c \
-        --regex-foo=/d/\0/d/ \
+        --regex-foo=:d:\0:d: \
         --list-kinds=foo
 
diff --git a/Tmain/lregex-reject-reserved-kind.d/run.sh b/Tmain/lregex-reject-reserved-kind.d/run.sh
index 7bc2948..dc44bb8 100644
--- a/Tmain/lregex-reject-reserved-kind.d/run.sh
+++ b/Tmain/lregex-reject-reserved-kind.d/run.sh
@@ -3,4 +3,4 @@
 
 CTAGS=$1
 
-${CTAGS} --quiet --options=NONE -o - --langdef=foo --regex-foo=/a/\0/F/ run.sh
+${CTAGS} --quiet --options=NONE -o - --langdef=foo --regex-foo=:a:\0:F: run.sh
diff --git a/Tmain/regex-for-unknown-language.d/run.sh b/Tmain/regex-for-unknown-language.d/run.sh
index 5866a5c..1f7e1bb 100644
--- a/Tmain/regex-for-unknown-language.d/run.sh
+++ b/Tmain/regex-for-unknown-language.d/run.sh
@@ -3,5 +3,5 @@
 
 CTAGS=$1
 
-${CTAGS} --quiet --options=NONE --regex-nosuchlang=/a/
+${CTAGS} --quiet --options=NONE --regex-nosuchlang=:a:
 exit $?

```

**Pull request closed without merging**
