### PR TITLE
C improve c++ scope keywords handling in c

### PR DESCRIPTION
**Pull request by masatake**
C: deal with C++ scope keywowrds as identifiers

In *.h file if [: \t] don't follows after protect|private|public,
deal with the token as an identifier, not a keywowrd.

TODO: The language for each tag entry is still C++. It should be C.
Signed-off-by: Masatake YAMATO <yamato@redhat.com>

### CODE REVIEW

**Comment by codebrainz** [comment]
Does it handle these?

```c++
struct Foo {
private/*foo*/:
};
```

```c
struct Foo {
int private       ;
};
```

```c
void foo(void) {
  goto private;
private:
  return;
}
```

**Comment by pragmaware** [comment]
I think this is a good idea.

For the @codebrainz comments:

Case1: comments should be stripped out by the preprocessor, so this should work (in theory).
Case 2: we might require the current token chain to be empty? (might have counterexamples?)
Case 3: we might require the current scope to be != function?

**Comment by masatake** [comment]
Thank you for  the comments.
The change is just a workaround; these things should be done in upper layer.
Anyway I will try to improve my change.

**Comment by masatake** [comment]
All cases suggesetd by @codebrainz are added to Units.

Though I got hits from @pragmaware , I implemented the iead in lower level. Using higher level knowledges in the tokenizer may be not good idea.

**Pull request merged**
