### PR TITLE
appveyor: Use MSYS2 for packaging

### PR DESCRIPTION
**Pull request by k-takata**
* Use MSYS2 to create zip packages and stop using VC for it.
* Enable following libraries with MSYS2:
  jansson, libxml2, libyaml.
* Enable static link with MSYS2.

### CODE REVIEW

**Comment by k-takata** [comment]
This fails because of #1411. It should be fixed before merging this.

**Comment by k-takata** [comment]
I think static link is suitable for distributing Windows binary for portability.
If we distribute a binary linked with jansson, libxml2 and libyaml, I think we should include license files of the libraries.
I couldn't find the license files under the MSYS2 installation directory, so maybe we should store the copies of them in our repository.

The license files are found at here:
https://github.com/akheron/jansson/blob/master/LICENSE
https://git.gnome.org/browse/libxml2/tree/Copyright
https://bitbucket.org/xi/libyaml/src/default/LICENSE?fileviewer=file-view-default

**Comment by k-takata** [comment]
The directory structure of a zip package is:

```
.
├── ctags.exe
├── docs
│   ├── _images
│   │   └── *.svg
│   ├── _static
│   │   └── *.css, *.js, etc.
│   └── *.html
├── license
│   ├── COPYING
│   ├── COPYING.MinGW-w64-runtime.txt
│   ├── Copyright.libxml2
│   ├── LICENSE.janssen
│   └── LICENSE.libyaml
├── README.md
└── readtags.exe
```

**Comment by k-takata** [comment]
I stopped testing VC binaries in this PR, because it takes long time (2 x ~5 minutes), but stopping it has a risk that we cannot catch bugs only occurs with VC.
So, should we still test VC binaries on AppVeyor?

**Comment by masatake** [comment]
Stopping tesing VC binaries during updating this PR is o.k.
When all updating are done, let's turn the testing on again.

**Comment by k-takata** [comment]
Rebased upon the fix of #1418.
Now both stripped/unstripped binaries are available.
The size of ctags.exe is now:

Stripped: ~ 3 MB
Unstripped: ~ 8 MB
(See: https://ci.appveyor.com/project/masatake/ctags/build/1.0.2098/job/hpf3dq305vulj2se/artifacts)

Test of VC binaries are enabled again, but it is only x64. Test of VC x86 is disabled to reduce the CI time.
Now AppVeyor takes about 20 minutes.

**Comment by k-takata** [comment]
I think it's ready to be merged.

**Comment by k-takata** [comment]
This also fixes #1312.

**Comment by k-takata** [comment]
And  also #660.

**Comment by k-takata** [comment]
I updated the docs and added how to build static link binary using MSYS2.

**Pull request merged**
