### PR TITLE
FrontMatter: new subparser parser run from Markdown parser

### LINKED ISSUE #3032: Forntmatter parser
@masatake 
>Is this written in the standard markdown syntax?

No it's not markdown, it's it's frontmatter language yaml. Special information(meta data) used by static site generators like [hugo](https://gohugo.io/content-management/front-matter#readout) and how you mentioned jekyll. Pandoc, vuepress and many other's use it. This is extra information that is needed to create html documents.

Your default [markdown.ctags](https://github.com/universal-ctags/ctags/blob/e82e9e07ad4c84ce4d7a1c39080eaabddfaba48a/optlib/markdown.ctags) ignores it because it does not match the patterns.

> Could you tell me a web page where the syntax is explained?

You found it that's a good example.

This is an example template:

```yaml
 ---
title: "{{ replace .Name "-" " " | title }}"
date: {{ .Date }}
draft: false
tags: ['code','{{.Name}}']
menu:
    main:
        parent: 'code'
---
```

Then this would be created:

```markdown
---
title: "Example"
date: 2021-05-17T23:20:21-05:00
draft: false
tags: ['code','example']
menu:
    main:
        parent: 'code'
---

## Introduction

Markdown starts here.
```
> I want to fix the markdown parser of ctags not to make the tag for "parent: 'code'".

I agree the command ```ctags/ctags --options=NONE --options=mymd.ctags  --extras=+'{pseudo}' --fields=+'{extras}' -o - input.md ``` should not be capturing the front matter tags, it should ignore front matter, anything
in between the  3 dashes```---```.

I already have another tags file that I create that captures  the frontmatter (the 'code' and 'example' tags).

frontmatter.ctags
```text
--langdef=frontmatter
--map-frontmatter=+.md

--kinddef-frontmatter=t,tags,front matter tags
--_tabledef-frontmatter=toplevel
--_tabledef-frontmatter=tag

--_mtable-regex-frontmatter=toplevel/\ntags:[ \t]*\[[ ]?['"]//{tenter=tag}

--_mtable-regex-frontmatter=toplevel/.//

--_mtable-regex-frontmatter=tag/([a-zA-Z0-9]+)/\1/t/
--_mtable-regex-frontmatter=tag/['"]\]//{tquit}


--_mtable-regex-frontmatter=tag/.//

--exclude=.git
--exclude=vim.md
```

_Originally posted by @rickalex21 in https://github.com/universal-ctags/ctags/issues/3027#issuecomment-842818011_

### PR DESCRIPTION
**Pull request by masatake**
In this version, just extracting "foo" in "title: foo" written
in Yaml. JSON(;;;) and TOML(+++) are not supported yet.

Tagging `a`, `b`, and `c` in `tags: [ a b c ]` is another TODO item.
Much more work is needed in the Yaml parser.

Close #3032.

### CODE REVIEW

**Comment by helins** [comment]
How is this meant to be used? I tried several ways but the `title:` in the frontmatters of my Markdown files is never parsed.

Are there currently efforts to extend parsing to full YAML?

**Comment by masatake** [comment]
Could you show the input file? I also want to know the name of the file.

**Comment by helins** [comment]
Just a quick try with a file name `foo.md` and that kind of content: 

```markdown
---
title: Some title
---

# Foo

This is a test.
```

I am running on version 6.1.0.

**Comment by masatake** [comment]
```
$ ctags --options=NONE --extras=+g -o - /tmp/foo.md 
ctags: Notice: No options will be read from files or environment
Foo     /tmp/foo.md     /^# Foo$/;"     c
Some title      /tmp/foo.md     /^title: Some title$/;" t
```

You may have to add `--extras=+g`.

**Comment by helins** [comment]
Indeed, it works with `--extras=+g`, thanks!

**Pull request merged**
